### PR TITLE
Issue #1672

### PR DESCRIPTION
**Pull request by NikolayPianikov**
Fix Issue #1672 - allows TeamCity to parse service messages inside other service messages.

### CODE REVIEW

**Comment by rprouse** [comment]
As far as I understand the TeamCity integration, looks good to me. I am going to leave this for a second review since I don't feel strong in this area.

**Comment by CharliePoole** [comment]
I'm pretty confused by this - I don't understand why it is needed. See my comment on #1672

**Comment by NikolayPianikov** [comment]
@CharliePoole,  is it possible to add this PR to new repo? If it is not, I could do it myself.

**Comment by CharliePoole** [comment]
@NikolayPianikov See my answer on nunit/teamcity-event-listener#1, where I posted it by mistake.

Since I didn't merge this before creating the new repo, I think it's easiest if you create a branch in the new repo, duplicate your code there and create a new PR.

**Comment by NikolayPianikov** [comment]
@CharliePoole ok

**Pull request closed without merging**
