### PR TITLE
CollectionIntersectConstraint added

### PR DESCRIPTION
**Pull request by slawwan**
Hi guys!
I've found solution on stackoverflow, but I think it is better to have such constraint as built in.

http://stackoverflow.com/questions/4501598/nunit-assertion-for-an-empty-intersection-between-collection

### CODE REVIEW

**Comment by CharliePoole** [comment]
I marked this as an idea for discussion, since we really need to decide if we want this feature before doing the actual code review.

My vew... this allows writing

```C#
Assert.That(expected, Is.IntersectsWith(actual));
```

rather than

```C#
Assert.That(expected.Intersect(actual), Is.Not.Empty);
```

I'm not sure that it's justified as a built-in item, especially since it's easy to create as a user extension.

@nunit/core-team @nunit/framework-team What do you think?

**Comment by jnm2** [comment]
I wish there was a community extensions library, because I understand your desire not to bloat the framework and yet there's so much richness that could be expressed by things like this that you currently have to reinvent time and again, or just live without.

**Comment by rprouse** [comment]
@jnm2 you could always start a community extensions library 😄 

Personally, I agree with @CharliePoole that this might be more than we want in the framework. Whenever we add stuff like this, we need to think about all of the possible combinations of uses that might be possible and it ends up bloating the code and potentially confusing users.

**Comment by slawwan** [comment]
There is a difference not only in syntax. Console output for failed tests is more detailed with CollectionIntersectConstraint

Some examples of code and console output

`Assert.That(new[] {1, 2, 3}, Is.Not.IntersectsWith(new[] {3, 4, 5}));`
>   Expected: not intersects with < < 3, 4, 5 > >
  But was:  < 1, 2, 3 >

`Assert.That(new[] {1, 2, 3}.Intersect(new[] {3, 4, 5}), Is.Empty);`
>   Expected: < empty >
>   But was:  < 3 >

`Assert.That(new[] {1, 2, 3}.Intersect(new[] {4, 5, 6}), Is.Not.Empty);`
>   Expected: not < empty >
>   But was:  < empty >

Similar situation with built in SupersetOf and SubsetOf constraints
I can use it

`Assert.That(new[] {1, 2, 3}, Is.SubsetOf(new[] {3, 4}));`
>   Expected: superset of < 3, 4 >
>   But was:  < 1, 2, 3 >

Or use Except method from LINQ like this
`Assert.That(new[] {3, 4}.Except(new[] {1, 2, 3}), Is.Empty);`
>   Expected: < empty >
>   But was:  < 4 >

Of course, at first we added CollectionIntersectConstraint in our library and we faced two unpleasant moments:
1. Syntax
We can write extensions for ConstraintExpression and use constraint this way:
`Is.Not.IntersectsWith(...)`
But we can not write
`Is.IntersectsWith(...)`
because `Is` - static class
2. Collection formating for console output
There is `MsgUtils.FormatValue(...)` method to format values for console output
But `MsgUtils` is internal class and it is invisible for external libraries
The simplest way to format values like NUnit - call this method with reflection

So, before creating "community extensions library", I think, some сontroversial issue should be solved

Some IL to call `MsgUtils.FormatValue(...)` from external library
```
public static class NUnitFormatter
{
    private static readonly Func<object, string> formatValue;

    static NUnitFormatter()
    {
        var msgUtilsType = typeof(Constraint).Assembly.GetType("NUnit.Framework.Constraints.MsgUtils");
        var formatValueMethodInfo = msgUtilsType.GetMethod("FormatValue", BindingFlags.Public | BindingFlags.Static, null, new[] {typeof(object)}, null);

        var dynamicMethod = new DynamicMethod("formatValue", typeof(string), new[] {typeof(object)}, true);
        var ilGenerator = dynamicMethod.GetILGenerator();
        ilGenerator.Emit(OpCodes.Ldarg_0);
        ilGenerator.Emit(OpCodes.Call, formatValueMethodInfo);
        ilGenerator.Emit(OpCodes.Ret);

        formatValue = (Func<object, string>) dynamicMethod.CreateDelegate(typeof(Func<object, string>));
    }

    public static string FormatValue(object value)
    {
        return formatValue(new[] {value});
    }
}
```

**Comment by jnm2** [comment]
@slawwan Hey, did you know that code can be replaced by:

```c#
public static class NUnitFormatter
{
    private static readonly Func<object, string> formatValue;

    static NUnitFormatter()
    {
        var msgUtilsType = typeof(Constraint).Assembly.GetType("NUnit.Framework.Constraints.MsgUtils");
        var formatValueMethodInfo = msgUtilsType.GetMethod("FormatValue", BindingFlags.Public | BindingFlags.Static, null, new[] { typeof(object) }, null);

        formatValue = (Func<object, string>)formatValueMethodInfo.CreateDelegate(typeof(Func<object, string>));
    }

    public static string FormatValue(object value)
    {
        return formatValue(new[] { value });
    }
}
```

**Comment by JustinRChou** [comment]
I remember there was a issue for something like this. #1151 
So wouldn't the intersect solve that issue?

**Comment by CharliePoole** [comment]
@JustinRChou That issue relates to the display format of errors from the existing CollectionsEquivalentConstraint and doesn't introduce any new constraint.

@slawwan I'll try to get back to this today with some further ideas about how we could make it easier to create an extension. However, one thing you might consider is creating your own static "Is" class, deriving from NUnit.Framework.Is. In some cases you may need to have a using alias, but most of the time I have been successful working this way by putting the "Is" class in the same namespace as my tests.

**Comment by ChrisMaddock** [comment]
@nunit/framework-team - I think we should make a decision on this one, before it goes any more stale.

I personally think it might be worthwhile. I'd normally not be a fan of adding 'niche' API methods, but given we already have CollectionSubsetConstraint, CollectionSupersetConstraint, and CollectionContainsConstraint, I wonder if it fits that set quite nicely.

Initial opinion here seems to disagree though. What do other people think?

**Comment by jnm2** [comment]
It seems to fit well with the other `Collection*Constraint`s.

**Comment by CharliePoole** [comment]
As commented way back, neither @rprouse nor I were crazy about this one as an addition to our API. As a meta-point, we don't do well in resolving discussion items - they just seem to stay open. I'm still pretty lukewarm about it, but could go along if others really want it badly. If so, we need to get it updated and do a real code review.

**Comment by ChrisMaddock** [comment]
Courtesy of our new governance docs, I think this is a decision that falls to @rprouse to make, as 'Project Leader'. 😄

**Comment by rprouse** [comment]
I am also not very enthusiastic about this feature. Adding niche features like this becomes a very slippery slope and eventually the API becomes so large that it is nearly impossible for developers to find what they are looking for. @slawwan we appreciate your effort, but I am going to close this one without merging.

**Pull request closed without merging**
