### PR TITLE
Indicate that SetupFixtureAttribute should not be used on base-classes

### PR DESCRIPTION
**Pull request by x789**
As discussed in #4158. This PR contains the changes for NUnit v3.

### CODE REVIEW

**Review by jnm2 — APPROVED** [review]

**Comment by jnm2** [comment]
The build failures are because the `v3.13.-dev` branch is currently in a bad state.

**Review by stevenaw — APPROVED** [review]
Thanks!
I'm a little puzzled by the build failures myself though they're definitely not related to your changes. Will take a bit of digging to sort out

**Comment by x789** [comment]
@mikkelbu gave a hint how to fix the `System.ValueTuple` build-error.

**Comment by jnm2** [comment]
Maybe we don't need that package reference at all? Eventually it'll be bringing the package version backwards.

**Pull request merged**
