### PR TITLE
Merge 3.4 Back Into Master

### PR DESCRIPTION
**Pull request by rprouse**
This merges all changes from the 3.4 release branch back into master and increments the development version to 3.5.

### CODE REVIEW

**Comment by rprouse** [comment]
Just in case it wasn't clear, this is ready to merge after a review. :smile:

**Comment by CharliePoole** [comment]
Sorry, I missed that. Looks good.

**Comment by CharliePoole** [comment]
I forget... are we keeping release branches? Is this different from the release branch? I'll let you clean it up as you see fit. :-)

**Comment by rprouse** [comment]
Yes, we are keeping the release branch, but I am creating a branch after the release off the release branch to merge the changes back in. Works to update the version without changing the release branch.

**Pull request merged**
