### PR TITLE
WIP: Issue4421 net6

### LINKED ISSUE #4421: Add support for native .NET-6.0 target
To track the work in #4420

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #4421 

This is a net6 only solution for conditional formatting of messages.

I found a way to also do this for net462.
Will push that later.
This is parked for comparison

### CODE REVIEW

**Comment by OsirisTerje** [comment]
Awesome!  

About Assert and Assert.That files:  Be careful with too many changes there, as I am changing a lot there for the CallerArgumentExpression in #4427 
These changes also affects a lot of the tests, as many of them check on the assert messages.

**Comment by manfred-brands** [comment]
> About Assert and Assert.That files: Be careful with too many changes there, as I am changing a lot there for the CallerArgumentExpression in #4427
> These changes also affects a lot of the tests, as many of them check on the assert messages.

I saw you creating that and it will certainly conflict.  I thought it was on my list after this. You were too keen.
Especially with the conditional formatting it needs work.

**Comment by manfred-brands** [comment]
The code example from #4429:
```csharp
Assert.That(1 + 1, Is.EqualTo(2), $"{text} {formatCounter}");
```

Gets for .net6.0+ compiled into:

```csharp
AssertingInterpolatedStringHandler<int> assertingHandler = new AssertingInterpolatedStringHandler<int>(1, 2, num, resolveConstraint, out isEnabled);
if (isEnabled)
{
	assertingHandler.AppendFormatted("String was formatted");
	assertingHandler.AppendLiteral(" ");
	assertingHandler.AppendFormatted(formatCounter);
}
Assert.That(actual, expression, assertingHandler);
```

This is normally done to prevent the boxing of `struct` objects, but as these are only evaluated on failure, performance is not an issue and I think this solution is too complex.
But it was a nice exercise.

**Comment by manfred-brands** [comment]
This solution is too complex, it requires the `Assert` to be done inside the `InterpolatedStringHandler` constructor only so the `isEnabled` out parameter can be set.
Limited benchmarking only show a slight improvement on the `FormattableString` solution:
```
|                       Method |      Mean | Ratio | Allocated | Alloc Ratio |
|----------------------------- |----------:|------:|----------:|------------:|
|        UseFormatAndArguments |  3.981 ns |  1.00 |      56 B |        1.00 |
|       UsePreformattedMessage | 27.599 ns |  6.95 |     104 B |        1.86 |
|        UseFormattableMessage |  9.216 ns |  2.32 |      88 B |        1.57 |
| UseInterpolatedStringHandler |  7.813 ns |  1.96 |         - |        0.00 |
```

The weirdness of doing the assertion in a string handler constructor and the fact that it doubles the code base with conditional compiles make it not worthwhile to consider.

**Comment by manfred-brands** [comment]
Not worthwhile.

**Pull request closed without merging**
