### PR TITLE
Fix for Issue #1373 - Setting with a null value

### PR DESCRIPTION
**Pull request by matt40k**
Fix for Issue #1373

### CODE REVIEW

**Comment by CharliePoole** [comment]
Your fix looks reasonable but nobody has ever provided a repo of the problem. Can you add a test that fails without your fix and passes after it?

My biggest concern would be that we not mask a problem in the calling code. How do we get a null here?

**Comment by ChrisMaddock** [comment]
I agree re: this wanting a test. What does this actually look like, when you try and write null with `XmlWriter.WriteAttributeValue`?

> My biggest concern would be that we not mask a problem in the calling code. How do we get a null here?

I couldn't see a way we would require this currently - however, it's a situation @oznetmaster came across in production - and it seems sensible to me that this should work as expected, when it's only currently crashing on the result-writing stage.

**Comment by matt40k** [comment]
Thanks for the feedback - so just to check. We're happy to handle nulls in this way - ie it should handle it and not throw an exception.

And I need to add a unit test(s) to src/NUnitFramework/tests/Api/FrameworkControllerTests.cs

Is this correct?

**Comment by CharliePoole** [comment]
Yes to the first question.

As for tests, we need to test both ways that the framework can be invoked: through `FrameworkController` and directly through `NUnitTestAssemblyRunner` as NUnitLite does it. I think the second test may lead you to either moving or duplicating your fix.

**Comment by mikkelbu** [comment]
Hi @matt40k the new test is failing at the build server
https://ci.appveyor.com/project/CharliePoole/nunit/build/3.9.0-ci-04583-pr-2493#L1777.

**Comment by matt40k** [comment]
Mmm, not sure why its returning empty rather then null

**Comment by jnm2** [comment]
Probably because it's writing the XML `key="key1" value=""` when you give it `null`.
The usual way to preserve the null would be to prevent the `value ` attribute from being shown, but I'm not sure `null` vs empty is important in run settings?

**Comment by rprouse** [comment]
@matt40k just update your tests to look for the empty string. I am pretty sure @jnm2 is correct.

**Pull request merged**
