### PR TITLE
Removed not used rebracer.xml file settings

### PR DESCRIPTION
**Pull request by pandualuvala**
removed the Rebracer.xml settings file based on issue #2685

### CODE REVIEW

**Comment by rprouse** [comment]
Looks good, but can you remove the `Nunit.dotsettings` file also? Thanks.

**Comment by mikkelbu** [comment]
@rprouse But @ChrisMaddock only asked for the Rebracer.xml in https://github.com/nunit/nunit/issues/2685#issuecomment-360794664?

**Comment by ChrisMaddock** [comment]
Yup - please see Terje's comment on that thread, Rob.

I'm not sure myself how much ReSharper does by default which will go against what we currently have - so maybe better to leave it in and investigate further if Terje thinks it might cause a problem.

**Comment by rprouse** [comment]
I missed that last comment, thanks. I have approved and merged. Thanks for another contribution  @pandualuvala.

**Pull request merged**
