### PR TITLE
Nuget Restore

### PR DESCRIPTION
**Pull request by chris-smith-zocdoc**
Addresses #125

This removes a single package Microsoft.Bcl.1.1.10 from the packages folder and relies on nuget restore to download it before building the project.

The four use cases that @CharliePoole mentioned in the issue are all working with this solution.

Should I remove the rest of the packages from git in this branch or another one?

### CODE REVIEW

**Comment by CharliePoole** [comment]
I think you should remove all of them and then we should test quite thoroughly before merging. As you know, the CI tests only cover the desktop versions. @rprouse Can you test this for the Xamarin runner builds when it's ready? I'll look at CF.

**Comment by chris-smith-zocdoc** [comment]
I removed the other packages

**Comment by rprouse** [comment]
The Xamarin runners are in another repository and don't have a build script or CI configuration yet. They are using the NuGet packages though, so once I create the build scripts, I will use what was done here for reference.

I've reviewed the code and it looks good.

**Comment by CharliePoole** [comment]
@chris-smith-zocdoc Since the runners are separate, please go ahead and remove all the packages. Also, I realized after thinking about it that there is no relation to CF, since we have no NuGet packages and VS 2008 doesn't even support NuGet.

**Comment by chris-smith-zocdoc** [comment]
@CharliePoole the packages have been removed, I believe this is ready to merge

**Pull request merged**
