### PR TITLE
Remove some usings

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by manfred-brands** [comment]
Thanks Simon. I hope you didn't do this manually but used the quick fix for IDE0055 to remove unnecessary usings.
We should enable that rule as an error so these don't creep back in.

**Comment by manfred-brands** [comment]
@SimonCropp  I have added a commit to your branch, enabling rule IDE0005.
It found some usings that should have been conditional, one that could be removed and one that needed re-instating for DEBUG builds.

**Comment by SimonCropp** [comment]
LGTM but i cant approve my own pr

**Review by manfred-brands — APPROVED** [review]

**Review by mikkelbu — APPROVED** [review]
LGTM

**Pull request merged**
