### PR TITLE
Adds support for Nullable<bool> to Assert.IsTrue and Assert.IsFalse

### PR DESCRIPTION
**Pull request by JohanLarsson**

### CODE REVIEW

**Comment by CharliePoole** [comment]
This looks good to me in general. It's a pleasant surprise to see that TrueConstraint and FalseConstraint, to which the Nullable argument is passed, handle it correctly without change.

I have one concern, which is the replacement of bool with bool? rather than adding new entry points. C# apparently converts bools, but does this involve boxing? Will C++, VB, etc. handle it the same way? One of us should check this before merging unless @JohanLarsson has already checked.

**Comment by CharliePoole** [comment]
A further comment regarding boxing... eventually, the value gets boxed, because we cast everything to an object in the depths of the framework. However, we are working to eliminate this, so I'd prefer not to add another instance of it.

**Comment by JohanLarsson** [comment]
It does not box.

**Comment by rprouse** [comment]
Looks good to me @CharliePoole. Do you still want to check for boxing?

**Comment by CharliePoole** [comment]
No, I'll take @JohanLarsson 's answer that it doesn't.

**Comment by JohanLarsson** [comment]
Do I have to keep the fork in my repo for this discussion to survive?

**Comment by CharliePoole** [comment]
No the discussion is independent of the branch.

**Comment by JohanLarsson** [comment]
Thank you sir.

**Pull request merged**
