### PR TITLE
Add support for DateTime comparison with TimeSpan tolerance

### LINKED ISSUE #4600: Add `DateTime`/`TimeSpan` support for inequality tolerance
It would be nice if the following code worked:

``` csharp
public static DateTime LastDateAccessed { get; set; } // simulate a remote value

[Test]
public void TestMe()
{
    DateTime beforeUpdate = DateTime.UtcNow;

    // Do operation
    LastDateAccessed = DateTime.UtcNow.AddMilliseconds(-50); // some kind of timing imperfection on the server

    // This fails because of the timing issue
    Assert.That(LastDateAccessed, Is.GreaterThan(beforeUpdate));

    // It would be nice to do this
    Assert.That(LastDateAccessed, Is.GreaterThan(beforeUpdate).Within(TimeSpan.FromSeconds(1)));
}
```

For consistency, this should probably be done on all constraints that extend [`ComparisonConstraint`](https://github.com/search?q=repo%3Anunit%2Fnunit+%22%3A+ComparisonConstraint%22&type=code).

I am willing to take up the task. I just want to make sure this is kind of change would be accepted.

### PR DESCRIPTION
**Pull request by RenderMichael**
Fixes #4600

### CODE REVIEW

**Comment by RenderMichael** [comment]
I had to pull out the test data into a source method because `DateTime`/`TimeSpan` are not allowed in attributes.

Also DateTime's formatting in the error messages is different from the normal `ToString()` is for the existing `double` and `int` tests, so I called `MsgUtils.FormatValue` directly like the exception message formatting itself does.

**Review by manfred-brands — CHANGES_REQUESTED** [review]
Thanks @RenderMichael.

The code changes are nice and simple.

However as it also affects other areas where `Tolerance` is used, could you also please update the other constraint tests: `GreaterThanOrEqualConstraintTests`,  `LessThanConstraintTests` and `LessThanOrEqualConstraintTests` by adding use cases for `TimeSpan`.

**Comment by RenderMichael** [comment]
Thanks for the feedback @manfred-brands 

The PR has been updated, I also added an equality test to the existing Greater Than tests.

**Review by manfred-brands — APPROVED** [review]
Thanks again @RenderMichael for adding those extra tests.

Nothing more from me.

**Comment by RenderMichael** [comment]
Sorry for the update after the fact, I noticed I used some terrible variable names in the tolerance method. Fixed with no functional changes

**Review by stevenaw — APPROVED** [review]
Thanks for the contribution @RenderMichael ! Appreciate the final cleanup you did too :)

**Comment by stevenaw** [comment]
I'm going to try converting this to a draft and back to see if it un-sticks the WIP check

**Comment by OsirisTerje** [comment]
@stevenaw Merged.

**Comment by stevenaw** [comment]
Thanks @OsirisTerje

**Pull request merged**
