### PR TITLE
Add workaround for outdated Microsoft.Bcl.Build validation

### LINKED ISSUE #2663: Building NUnit .NET 4.5 in VS2017 fails
>6>------ Build started: Project: nunit.framework.tests, Configuration: Debug Any CPU ------
6>nunit.framework.tests -> C:\GitRepos\nunit\bin\Debug\net45\nunit.framework.tests.dll
6>C:\Users\wheel\.nuget\packages\microsoft.bcl.build\1.0.21\build\Microsoft.Bcl.Build.targets(243,5): error : Could not locate C:\GitRepos\nunit\src\NUnitFramework\testdata\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.
6>Done building project "nunit.testdata.csproj".

However, the solution as a whole reports building having succeeded:
>========== Build: 6 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #2663

### CODE REVIEW

**Comment by OmicronPersei** [comment]
Maybe not the best forum for this question but: isn't the label `awaiting:review` a bit redundant in the context of a pull request?

**Comment by jnm2** [comment]
@OmicronPersei No problem. See https://github.com/nunit/nunit/issues/2658 for the rationale. tldr; the PRs around here spend a lot of time *not* waiting for reviews. 😜

**Comment by OmicronPersei** [comment]
Well, looks like we're waiting on CI again.  Did Travis get worse?

**Comment by CharliePoole** [comment]
Yes. 😄

**Comment by ChrisMaddock** [comment]
There was a Travis breakdown yesterday - and still a backlog. 😞 That normally seems to have been the case, when they're on a go-slow.

https://www.traviscistatus.com/

**Pull request merged**
