### PR TITLE
Suppress reason in xml if null or whitespace

### PR DESCRIPTION
**Pull request by cristobalito**
This should address issue #1896.

First commit to the project (and a novice to git(hub) to boot), so please feel free to point out any issues - I'll do my best to address promptly.

Issue only mentions a problem with the Success case (e.g. using Assert.Pass), but it appears that Inconclusive and Ignore can also produce reason elements in the xml and therefore would also have this issue. It's possible other states could be a problem, but I was basing the work of existing tests that check for reason.

There is a fair bit of duplication across the (existing) tests - I've not really tried to address that, aside from some low hanging fruit.

Changes should be relatively self explanatory, but please let me know if you'd like any more details.

Chris

### CODE REVIEW

**Comment by CharliePoole** [comment]
@cristobalito We're in the midst of putting out the next nunit release, so this will probably need to wait for review until afterwards. We'll be back to you!

**Comment by cristobalito** [comment]
@CharliePoole No worries - good luck with the release.

**Comment by CharliePoole** [comment]
@ChrisMaddoc That makes sense to me.

**Comment by ChrisMaddock** [comment]
@cristobalito - would you mind expanding this PR to cover the `Assert.Fail()` case also? If not - no worries, we can merge this and make that a separate issue. Thanks! 😄

**Comment by cristobalito** [comment]
Sure - happy to fix that as part of this PR.

**Comment by rprouse** [comment]
Please hold off on merging this one until after the release and whomever merges, please do a squash from the merge dropdown. I don't mind a few commits, but over 20 is a bit much 😄

**Comment by ChrisMaddock** [comment]
I think we should merge this in before it gets too stale and needs rebasing. @nunit/core-team - someone mind doing a second review?

We can then make the `Assert.Fail()` case a separate issue (it wasn't originally part of #1896 anyway). @cristobalito - if you're still interested, we can assign the new issue to you, and it can be done as a separate pull request?

**Comment by cristobalito** [comment]
Hi Chris, still happy to do the work. Apologies I've been sidetracked a
little in the last few weeks.

Congrats on getting the recent release out btw.

Chris

**Comment by ChrisMaddock** [comment]
Great, @cristobalito! No rush at all, I just thought it would be best if we get this in before we have merge problems. Although actually, maybe it's a good job this was delayed, I'm not entirely sure if our thinking was right here...

The [xml spec](https://github.com/nunit/docs/wiki/Test-Result-XML-Format#failure) states that `<reason>` is optional, and can be omitted like has just been done in this PR.  It seems to suggest however that `<message>` is a required child-element for `<failure>`.

The current code omits failure-messages when the message is null, but not when it is an empty string. I think we should change one way or the other. If we decide the element is required, then if message=null, an empty element should be put in. On the other hand we could make failure messages match other cases and be optional - I don't know how much is depending on its existence, and how strict this spec is.

@CharliePoole - any thoughts?

**Comment by CharliePoole** [comment]
@ChrisMaddock I think it's slightly easier for those who want to read and process the XML if there are no empty elements. 

The document is not a specification to be followed. It's something I wrote after the fact describing what NUnit3 implemented. So, it's not in the least strict. 😄

**Comment by ChrisMaddock** [comment]
Great - I updated the spec and created https://github.com/nunit/nunit/issues/2005. 😄

**Pull request merged**
