### PR TITLE
Preparing the RC2 release

### PR DESCRIPTION
**Pull request by rprouse**
**Do not merge**

Starting to make the updates for RC2. I dated it for tomorrow (Sunday), but if we get the last outstanding issue done today we can change the date.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Release notes are here: https://github.com/nunit/nunit/wiki/Release-Notes-for-RC2
When we are ready they can be cut and pasted to the top of the actual release notes and the temp page can be deleted.

I'd like to try something. Let's make changes on this branch, rather than master. If we fix any more issues, do the merge with this branch as a target. We can actually release from this branch, and then merge it into master afterward. That's how I'm hoping to do it in the future, so I'd like to give it a try. (@rprouse if you think there is a risk, we can experiment on a dummy repository later on.)

As a further test, if we merge the change deleting TeamCityEventHandler directly to master first, we can subsequently learn something: whether pulling the tagged release includes or excludes that change. Hopefully it will be excluded from the tag and we can use this approach for our further 3.0 releases.

**Comment by rprouse** [comment]
Charlie, sounds good and I think it will work fine.

**Comment by rprouse** [comment]
I think we are ready to release based on this branch. I merged in the NUnit console issue, but not the teamcity issue. I checked the history and it looks correct even though there are changes showing in this PR for issues that are already merged into master. I think it is because they got pulled in again by #988?

I am heading out soon. I will do the release in the morning.

**Comment by CharliePoole** [comment]
I closed one more documentation issue and updated CHANGES and Release Notes. PR #1006 is still pending.

**Pull request merged**
