### PR TITLE
change ITypeInfo.Namespace to be nullable

### PR DESCRIPTION
**Pull request by SimonCropp**
since in .net namespace can be null

### CODE REVIEW

**Review by manfred-brands — COMMENTED** [review]
Your changes look fine.
The build fails because of an existing issue detected now because a later version of the SDK is used.
There seems to be two different references to System.ValueTuple

**Comment by SimonCropp** [comment]
@manfred-brands thanks. let me know if i need to do anything to help resolve the build issue.

**Comment by manfred-brands** [comment]
@SimonCropp Please change in 'src/NUnitFramework/testdata.fsharp/nunit.testdata.fsharp.fsproj' as per below:

image

**Comment by SimonCropp** [comment]
@manfred-brands done

**Review by mikkelbu — APPROVED** [review]
LGTM

**Review by stevenaw — APPROVED** [review]
LGTM, thanks for your contribution @SimonCropp !

**Pull request merged**
