### PR TITLE
expose more members on TestAdapter

### PR DESCRIPTION
**Pull request by SimonCropp**
Adds

 * Namespace
 * DisplayName
 * Method
 * Type

### CODE REVIEW

**Comment by SimonCropp** [comment]
context: i need these extension point in Verify to avoid reflection

**Comment by SimonCropp** [comment]
any chance of getting this one included in the next release?

**Comment by stevenaw** [comment]
Thanks @SimonCropp 
I'm not against this myself, especially if it can help tooling, but given it increases the API surface I'd like to hear from others on the @nunit/framework-team for their thoughts as well as release timing (3.13.x or 4.0).

**Comment by SimonCropp** [comment]
seems there are no objections :)

**Comment by SimonCropp** [comment]
bump

**Review by rprouse — APPROVED** [review]
This looks good to me too.

As for releases, I'd like to get another 3 release out around the end of the month. Give us some time to clean up. For 4.0, I would like to scale back our ambitions a bit and start working on it in earnest. The changes I wanted to do were massive and rippled out to the engine, console, adapter and other runners. Coordinating all that will be really difficult and cause confusion for our users so I want to scale it back some.

More to follow on that...

**Pull request merged**
