### PR TITLE
Update app.manifest

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by CharliePoole** [comment]
Thanks for your contribution. It's customary to provide some explanatory description of the purpose of a pull request. :-)

In this case, it appears you are trying to make it work under Windows 10... I thought we already had that working, however. @rprouse Can you comment?

Also, you appear to have submitted two pull requests that do the same thing. Are they different?

I also wonder why we have comments in the manifest saying to remove comments when the lines are not actually commented out.

**Comment by rprouse** [comment]
We do work with Windows 10 in that our platform code returns the correct information whether or not this manifest setting is set. If it is not set, then .NET reports an earlier supported version of Windows. Very odd behaviour.

We should include this change so that code under test behaves as expected. I am fine with the comments, they are usually generated and everyone leaves them in. If we want to we can fix them later, but fairly low priority.

**Comment by rprouse** [comment]
Travis CI failure is unrelated. I have restarted the failed build,

1) Failed : NUnit.Framework.Internal.Execution.WorkItemQueueTests.StopQueue_WithWorkers
		  Worker thread 3 did not stop
		  Expected: False
		  But was:  True
		at NUnit.Framework.Internal.Execution.WorkItemQueueTests.StopQueue_WithWorkers () [0x00000] in <filename unknown>:0
		Tests Not Run

**Comment by rprouse** [comment]
CI is passing now, merging.

**Comment by CharliePoole** [comment]
"Worker thread 3 does not stop" is our one remaining (I hope) persistent
intermittent error.

**Comment by CharliePoole** [comment]
Looks like you merged both PRs. Hopefully the last one merged was the correct one. :-)

**Comment by rprouse** [comment]
It was hard to notice, but one was for the agent and one for the console. I
nearly closed the one as a duplicate! They should have been one PR. Odd
that this guy didn't submit better PR's, he works for Xamarin on the mono
team.

On 22 September 2015 at 12:25, CharliePoole <notifications@github.com>
wrote:

> Looks like you merged both PRs. Hopefully the last one merged was the
> correct one. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/pull/832#issuecomment-142340190>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by Therzok** [comment]
Sorry, I went away after I set the patches. This is a result of the deprecation of GetVersionEx that Environment.OSVersion uses. This is so we trick the app into being manifested for Windows 10, similar to how this is done for the other platforms.

This dependency appeared once Windows 8.1 came out, but Windows 8 and 8.1 version difference allowed it to not be noticed by many applications.

I submitted two different PRs for two different manifests that generate different files.

Really sorry for the quick PR-and-leave, I did them from the github UI.

My bad. :(

**Comment by Therzok** [comment]
See more details here: https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx

Once again, really sorry. :(

**Comment by Therzok** [comment]
I also wanted to include the removal of [this hack](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/OSPlatform.cs#L100-L136) in the PR, but this got merged and reviewed too fast. :P

**Comment by CharliePoole** [comment]
So, here's a quick briefing on how we do PRs here - I realize that it can be different from how other projects do it...

1. We try to put things that belong together in one PR. Generally, that means something we would like to make one decision about.

2. We try NOT to put things that don't belong together in the same PR. This really goes with item 1, but it's the most common mistake - people do two different things, we like one of them but not the other, so it takes extra work to split the PR. What you did is less of a problem, though momentarily confusing.

3. Submitting a PR means you are ready to merge unless you put some notice that you are still working on it in the description. We sometimes use **Not Ready to Merge** when we want folks to see the interim work and comment on it but we still have more to do. Otherwise, if you submit it and we like it it gets merged. Note that you can always have multiple commits to the same branch without submitting a PR for it.

At this point, your changes are in master, so if you think the hack is no longer needed (I didn't write it) then feel free to do a new branch and PR, explaining what it's about. :-)

Thanks for your contribution.

**Comment by CharliePoole** [comment]
A further comment... Isn't the "hack" still needed, given that we have no control over whether the user of NUnit has properly manifested the app being tested?

**Comment by Therzok** [comment]
> We try to put things that belong together in one PR. Generally, that means something we would like to make one decision about.

Yeah, that's naturally what I usually do, but the github UI is messy and I didn't have an opportunity to clone locally. I'll keep it in mind for future things though.

> We try NOT to put things that don't belong together in the same PR. This really goes with item 1, but it's the most common mistake - people do two different things, we like one of them but not the other, so it takes extra work to split the PR. What you did is less of a problem, though momentarily confusing.

They should've been one commit, easier to see they weren't targeting the same file. :)

> Submitting a PR means you are ready to merge unless you put some notice that you are still working on it in the description. We sometimes use Not Ready to Merge when we want folks to see the interim work and comment on it but we still have more to do. Otherwise, if you submit it and we like it it gets merged. Note that you can always have multiple commits to the same branch without submitting a PR for it.

Yep, I know, but `propose file change` automatically opened a PR for me, which shouldn't have happened. :/

> At this point, your changes are in master, so if you think the hack is no longer needed (I didn't write it) then feel free to do a new branch and PR, explaining what it's about. :-)

Yup.

> Thanks for your contribution.

You're welcome.

> A further comment... Isn't the "hack" still needed, given that we have no control over whether the user of NUnit has properly manifested the app being tested?

What do you mean? It's the NUnit runner which has to be properly manifested. So that's why `nunit-console` is now safe from it. Custom test runners should be able to manifest their own applications.

I don't think the OSPlatform check happens in the user's application? I might be wrong, but I'll test it out and report my findings!

**Comment by CharliePoole** [comment]
Ah! Now I see what you meant by using the GitHub UI. I've never tried to do
a pr that way. I can see it would be messy.

OSPlatform is a helper class used primarily by the PlatformAttribute, which
allows running or skipping a test on certain platforms where it may not
apply. So we need to know what platform we are actually running tests on.
Up to now that's the same platform that NUnit-console is running on, since
we don't support remote execution yet. But even so, the manifest only tells
me what platforms I'm capable of running on, not the actual platform.

Charlie

On Tue, Sep 22, 2015 at 12:01 PM, Marius Ungureanu <notifications@github.com

**Comment by rprouse** [comment]
I also think the hack is still needed unless you can see problems with leaving it in. Our runners and most third party runners will hopefully be properly manifested (partially thanks to you :+1:), but we cannot guarantee that every runner will be properly manifested and we want our platform attribute to always return the correct value. One example is our nunitlite runners which allow users to create their own self-executing tests. They may choose to manifest it as non-windows 10 for whatever reason, but our platform attribute should still work correctly.

If you can think of reasons it should be otherwise, then I am open to listening :smile:

**Comment by CharliePoole** [comment]
Even better, I'd listen to a test. :-)

**Pull request merged**
