### PR TITLE
Rename console to nunit3-console.exe - Fixes #929

### LINKED ISSUE #929: Rename nunit-console.exe
This is an idea I wanted to put up for discussion. I am looking at build systems like [Cake](http://cakebuild.net/) that assume NUnit is in the path or installed as a NuGet package in the tools directory. In either case, those tools cannot determine if the nunit-console.exe that it finds is a v2 or v3 nunit-console, so it does not know which command line parameters to use.

A possible workaround for this would be to rename the console to something unique to NUnit 3. Possibilities are `nunit3-console.exe`, `nunit.console.exe`, `nunit.exe`, `nunit3.exe`, ???

Thoughts?

### PR DESCRIPTION
**Pull request by rprouse**
I disliked `nunit-cmd.exe` because I thought it might be confused with `nunit.cmd` in documentation, so I went with your earlier suggestion of `nunit3-console`.

Everything builds, all tests run and everything packages.

### CODE REVIEW

**Comment by NikolayPianikov** [comment]
What was the reason to change the console's name. Is it really needed? It it not very friendly change for backward compatibility. All current versions of the TeamCity can't run this console.  When we plan to make a release of NUnit 3?

**Comment by CharliePoole** [comment]
@NikolayPianikov See the issue this resolves, #929.

Essentially, we thought it was confusing to have two different programs with the same name. We don't expect the NUnit 3.0 console to replace NUnit 2.6.4. Many people will keep using the old program - I guess for a couple of years. So we felt that when a user types nunit-console, they should know what they are going to get!

Of course, we would have wanted your input on this before the change was complete. That's why we discussed it publicly over several days. It's a big frustration to me that many of these discussions, even though open to all, are only between me and @rprouse.

I don't mean to pick on you. You are not the first person to be silent in the discussion and only speak up after the change is made. And you probably won't be the last. :-(

On the general issue of backward compatibility, I have noticed that you are much more focused on this than we are. We treat NUnit 3.0 as an entirely new program, with 95% compatibility to the predecessor. Is there a particular reason, do you think, that CI apps like TeamCity might want it to be more compatible? Don't you already have to pass different options to the nunit3 console compared to the old one?

**Comment by CharliePoole** [comment]
The release candidate for NUnit 3.0 should be out in a few days.

**Comment by NikolayPianikov** [comment]
We are trying to make a moving from NUnit 2 to NUnit 3 smooth. We have one build step for any version of the NUnit. When user wants to use NUnit 3 instead 2 he just changes the path to the console and all should work as before. Any thing that will force him think can get him to postpone the transition to the new version :)

**Comment by NikolayPianikov** [comment]
We are trying to make a moving from NUnit 2 to NUnit 3 smooth. We have one build step for any version of the NUnit. When user wants to use NUnit 3 instead 2 he just changes the path to the console and all should work as before. Any thing that will force him think can get him to postpone the transition to the new version :)

**Pull request merged**
