### PR TITLE
Nunit issue 1004

### PR DESCRIPTION
**Pull request by oznetmaster**
Add different format for DateTimeOffset in messages to show offset.

### CODE REVIEW

**Comment by CharliePoole** [comment]
So is DTO not available in CF then?

**Comment by CharliePoole** [comment]
Your branch build failed due to some mixup in the build script. However, the pr build succeeded and the code looks good, so I'm merging it.

**Comment by CharliePoole** [comment]
PRs need a comment that  refers to the issue. The naming convention for branches works only for us humans. Using "Fixes" causes automatic closure: like so...

Fixes #1004

**Comment by oznetmaster** [comment]
DTO is not available in normal CF.  I support it in my CF builds, however, and have a library with it in it.

**Comment by oznetmaster** [comment]
I did not know about the Fixes thing.. sorry.

**Pull request merged**
