### PR TITLE
Fixed unit tests for CF

### LINKED ISSUE #515: OSPlatform.IsMacOSX doesn't work
The implementation of OSPlatform.IsMacOSX depends on Environment.OSVersion.Platform == 6 on MacOSX.  As of Mono 2.2, the implementation changed to NOT return this value:

http://www.mono-project.com/docs/faq/technical/#how-to-detect-the-execution-platform

"Notice that as of Mono 2.2 the version returned on MacOS X is still 4 for legacy reasons, too much code was written between the time that the MacOSX value was introduced and the time that we wrote this text which has lead to a lot of user code in the wild to not cope with the newly introduced value."

Here is a discussion about this issue and a solution to call uname libc function to determine Mac vs. Linux.
https://mhut.ch/journal/2010/01/25/integrating_gtk_application_mac

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #515

### CODE REVIEW

**Comment by oznetmaster** [comment]
Looks good.

**Comment by CharliePoole** [comment]
@oznetmaster Did you run the tests before merging? I'm getting a test failure for TestCaseAttributeTests.CanExcludePlatform() on CF 3.5 using the PocketPC WM 5.0 emulator.

**Comment by oznetmaster** [comment]
They worked in my build :(  Not sure what is going on here.

**Comment by rprouse** [comment]
I am seeing it too. I will look into it. It is the new MacOSX exclusion that is failing on some platforms. I am debugging it and will report back.

**Comment by rprouse** [comment]
Not sure how this is working for you @oznetmaster. I debugged it and have the fix, see #878. PR to follow. This bug was always there, just exposed by my new tests. My fault, I did not have a computer with CF available at the time.

**Pull request merged**
