### PR TITLE
issue #1971

### PR DESCRIPTION
**Pull request by smwentum**
# Title

fixed some typos in the change.txt file and made change.md file

## Summary

fixed some typos in the change.txt file and made change.md file 

## Details
this is related to issue #1971  there were typos in the change .txt file and i made a change.md file

### CODE REVIEW

**Comment by CharliePoole** [comment]
Issue #1971 is marked as an idea and is under discussion. When we decide which way to go, we will either close it as won't fix or change it to something else - probably documentation. You shouldn't put time in on ideas because it could be wasted. However, this is looking like it will go ahead and if so we'll review the PR.

FYI, there are typos in the CHANGES file because that's how users created their issues. I for one have always kept them as (mis)spelled by the users, so long as they are understandable. But there's something to be said for correct spelling too. 😄 

Again... we'll review this if we decide to go ahead with the change.

BTW, you can see more info about where a particular issue is in the pipleline if you use ZenHub.

**Comment by rprouse** [comment]
If we go forward with this, I think we should be renaming changes.txt to .md, not maintaining two copies going forward. The MD file also needs the headers specified to match what we use in [the release notes](https://github.com/nunit/docs/wiki/Release-Notes).

Hold off on making the changes until we come to a decision on the future of #1971 though 😄

**Comment by ChrisMaddock** [comment]
@smwentum - we've finished up the discussion on issue #1971 - sorry it wasn't clear that was still in progress when you submitted this! I've added a proper spec of what we think needs to be done in the comment below - are you still interested in making the changes? You could just add them as an extra commit on this branch. 

https://github.com/nunit/nunit/issues/1971#issuecomment-274031803

**Comment by ChrisMaddock** [comment]
This is replaced by #2002

**Pull request closed without merging**
