### PR TITLE
Draft experiment: Docs via docfx

### PR DESCRIPTION
**Pull request by SeanKilleen**
Inspired by discussion at https://github.com/nunit/docs/issues/337

Exploring the option of generating world-class docs in a maintainable and welcoming way using docfx.

## What other projects are using docfx? 

* [Akka.NET](https://getakka.net/)'s docs are built using docfx.

## Work Remaining

Wiki Content to Port:

* [x] NUnit Docs
* [x] NUnit Xamarin Runners
* [x] VS Test Adapter
* [x] VS Test Generator
* [x] NUnit Analyzers
* [x] Developer Info

As part of the initial effort: 

* [x] Get a docfx build going
* [x] Generate API documentation for publicly documented NUnit API surface
* [x] Allow browsing of multiple versions? (if docfx allows this well)
* [ ] Add contribution guide for docs
* [ ] Add readme for building docs
* [x] Add logos etc. as appropriate.
* [x] Check wiki references (e.g. links within `[[ ]]`) to point them to the right spot.
* [x] Ensure all warnings are resolved
* [ ] Check wiki repo to ensure all content has migrated
* [x] Breadcrumb navigation
* [x] Add copyright / license to footer
* [ ] Add home page
* [ ] Check links for pointers to wiki and change to markdown references

Decisions to be made by NUnit team representatives:

* [ ] Decide where docs should live (whether to have this live at `nunit/docs` or somewhere other than in this folder.)
* [ ] Whether to include generated source code docs
* [ ] If there's an attribute name they'd like to use to hide certain code from docs publication
* [ ] Whether additional articles (e.g. VS test runner) should be captured in this site as well or done separately.
* [ ] Decide what to do about potential 404s (URLs will be changing)

Once those decisions have been made: 

* [ ] Exclude any internal public methods using filter config and an attribute (maybe a new `MeantForInternalConsumptionAttribute` or something along those lines?)
* [ ] Generate docs for additional APIs outside of this repo?
* [ ] Update build to utilize console docs builder
* [ ] Update azure pipelines to build and push docs.
* [ ] Ensure wiki content changes since this PR are reflected in the new docs

Formatting after full contents have been ported:

* [ ] Ensure all pages have title frontmatter (for title bar)
* [ ] Ensure all pages have top headings (for web page -- use title if possible?)
* [ ] Call out info, warnings, cautions, etc. using docfx syntax
* [x] Replace `C#` code snippet language with `csharp`
* [ ] Clean up the navigation
* [ ] Check alignment of code samples
* [ ] Pass for markdown linting

Potential follow-up issues to create: 

* [ ] Consider SEO aspects 
* [ ] Programmatic "See Also"? (vs text in individual files)
* [ ] Prettier, Jekyll-style URLs?
* [ ] Run html-proofer or similar to check for dead links and images
* [ ] Turn todos within wiki into actual issues in `nunit/docs`

## How to build this PR

* Prerequisite: Install docfx (using chocolatey? `choco install docfx -y`)
* `cd docs`
* Run `docfx build`
* Run `docfx serve` and navigate to <http://localhost:8080/_site>

### CODE REVIEW

**Comment by SeanKilleen** [comment]
FYI @ChrisMaddock -- a decent amount of progress so far with not too much time invested.

**Comment by ChrisMaddock** [comment]
I'll have to pull the branch at some point, and take a look. Glad you're making progress - so long as you're happy that this really needs the rest of the team to take a look before we can really make a decision about doing anything! 🙂 I just wouldn't want you to put in a lot of work for others on the team to then disagree that this is the right direction - it has only been 24 hours since we started the discussion! 😅

**Comment by SeanKilleen** [comment]
@ChrisMaddock 

>  So long as you're happy that this really needs the rest of the team to take a look before we can really make a decision about doing anything! 🙂

Absolutely. This is partially my own exploration of docfx and I've enjoyed the learning I've done so far. I'd never expect this PR to be merged in a vacuum. I just know these discussions are a little clearer when there's something tangible to reason about.

**Comment by SeanKilleen** [comment]
As of this point, the NUnit content has been ported with all links resolved.

**Comment by SeanKilleen** [comment]
As of this point, all of the remaining content I'm aware of has been ported and all links resolved.

While I wait for the NUnit team's decision on where this content should live, I'll be continuing along with the rest of the plan -- doing cleanup, markdown linting, ensuring pages have front-matter to start with, adding a draft home page / contributing guide, etc.

As always, PRs to this PR are welcome. 👍

**Comment by ChrisMaddock** [comment]
> While I wait for the NUnit team's decision on where this content should live, I'll be continuing along with the rest of the plan -- doing cleanup, markdown linting, ensuring pages have front-matter to start with, adding a draft home page / contributing guide, etc.

Awesome! 🎉 Let's keep this moving, I'll comment back on the other issue. 😄

**Comment by SeanKilleen** [comment]
Closing this in favor of https://github.com/nunit/docs/pull/339 -- please follow along with the adventure there!

**Pull request closed without merging**
