### PR TITLE
#685 Support build problem service message for TeamCity

### PR DESCRIPTION
**Pull request by NikolayPianikov**
See #685

### CODE REVIEW

**Comment by rprouse** [comment]
This looks good to me although I am surprised that NUnit returns 0 if there are failures. I will need to look at the code for that, in what situations does NUnit return 0 when it can't run tests?

**Comment by NikolayPianikov** [comment]
For example:

[18:56:06][Step 4/6] Starting: "C:\Program Files\NUnit 3.0.0 b2\bin\nunit-console.exe" C:\Projects\TeamServer\BuildServer\.idea_artifacts\agent_deployment_debug\temp\agentTmp\FwndJdLbHTCYvMyzqGzuxUqkqoeZg9KH\project.nunit "--work=C:\Program Files\NUnit 3.0.0 b2\bin" --noresult --framework=4.0 --workers=10 --verbose
[18:56:06][Step 4/6] in directory: C:\Projects\TeamServer\BuildServer\.idea_artifacts\agent_deployment_debug\work\33abfa34feab3e5d
[18:56:06][Step 4/6] NUnit Console Runner 3.0.5610 
[18:56:06][Step 4/6] Copyright (C) 2014 Charlie Poole
[18:56:06][Step 4/6] 
[18:56:07][Step 4/6] Test Files
[18:56:07][Step 4/6]     C:\Projects\TeamServer\BuildServer\.idea_artifacts\agent_deployment_debug\temp\agentTmp\FwndJdLbHTCYvMyzqGzuxUqkqoeZg9KH\project.nunit
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Runtime Environment
[18:56:07][Step 4/6]    OS Version: Microsoft Windows NT 6.3.9600.0
[18:56:07][Step 4/6]   CLR Version: 4.0.30319.0
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Options
[18:56:07][Step 4/6]     ProcessModel: Default    DomainUsage: Default
[18:56:07][Step 4/6]     Execution Runtime: 4.0
[18:56:07][Step 4/6]     Worker Threads: 10
[18:56:07][Step 4/6]     Work Directory: C:\Program Files\NUnit 3.0.0 b2\bin
[18:56:07][Step 4/6]     Internal Trace: Off
[18:56:07][Step 4/6]     Display TeamCity Service Messages
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Agent process 1464 starting
[18:56:07][Step 4/6] Running under version 2.0.50727.8009, Net 3.5
[18:56:07][Step 4/6] Agent process 1464 exiting
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Test Run Summary
[18:56:07][Step 4/6]     Overall result: Failed
[18:56:07][Step 4/6]    Tests run: 0, Passed: 0, Errors: 0, Failures: 0, Inconclusive: 0
[18:56:07][Step 4/6]      Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
[18:56:07][Step 4/6]   Start time: 2015-06-11 14:56:07Z
[18:56:07][Step 4/6]     End time: 2015-06-11 14:56:07Z
[18:56:07][Step 4/6]     Duration: 0,007 seconds
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Errors and Failures
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] 1) Failed : C:\Projects\TeamServer\BuildServer\.idea_artifacts\agent_deployment_debug\temp\agentTmp\FwndJdLbHTCYvMyzqGzuxUqkqoeZg9KH\project.nunit
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] 2) Invalid : C:\Projects\TeamServer\BuildServer\.idea_artifacts\agent_deployment_debug\work\33abfa34feab3e5d\trunk\HelloWorld.Tests\bin\Debug\HelloWorld.Tests.dll
[18:56:07][Step 4/6] Could not load file or assembly 'file:///C:\Projects\TeamServer\BuildServer\.idea_artifacts\agent_deployment_debug\work\33abfa34feab3e5d\trunk\HelloWorld.Tests\bin\Debug\HelloWorld.Tests.dll'; or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Process exited with code 0

**Comment by CharliePoole** [comment]
Since the problem is that NUnit is no longer returning an error code in certain cases, I believe we should first discuss that problem and decide what to do about it. This PR doesn't solve the problem for anyone except when running under TeamCity with --teamcity specified. That's a small subset of use cases.

NUnit used to throw an exception in the situation described (could not load the test file due to an invalid runtime). The console caught the exception and reported it, returning (if I remember correctly) -100 for an unexpected exception. Of course, this stopped all execution so no tests were run.

Now NUnit doesn't do that. Since there could be many assemblies, we decided to allow the valid ones to run and we report the problem as a console message. We don't return any error in this situation, but obviously we could do so. In keeping with our standard codes, it should probably be a negative value.

I think that solving this problem at the source would eliminate the need for an added TC message here. These messages are basically a kluge that will be eliminated (I hope) in the future when TC has native support for NUnit 3.0.

@NikolayPianikov It may help to give the team a little time to review an issue before you work on a solution. We may not feel it's an issue or we may have plans you don't know about. We are all around the world, so there is some delay but usually we will respond within a 24 hour cycle. 

Also, as we already discussed, I feel that we are making these changes for TC without any overall plan. In an earlier discussion, you agreed to create a spec on the wiki which we would then review. I created a stub page at https://github.com/nunit/dev/wiki/TeamCity-Service-Messages and gave you editing authority. Is this still something you feel you can do?

**Comment by NikolayPianikov** [comment]
Ok, I've added the content to this page. We can mix these approaches, from my point of view: the sending messages provides detailed info about build problem and exit code could provide final status

**Comment by NikolayPianikov** [comment]
TC service messages page done:
https://github.com/nunit/dev/wiki/TeamCity-Service-Messages/

**Comment by rprouse** [comment]
@NikolayPianikov, could you email me at rob@prouse.org? I've tried contacting you through LinkedIn and GitHub, but neither allow me to directly contact you. We would like to talk offline about JetBrains' plans for supporting NUnit 3.

Thanks

**Comment by NikolayPianikov** [comment]
Should I create issue about "Process exited with code 0"?

**Comment by rprouse** [comment]
Yes, could you? I think that is the proper way to fix this issue.

**Comment by NikolayPianikov** [comment]
I have renamed #685

**Pull request closed without merging**
