### PR TITLE
update namespacespace corrections for AssertFailFixture class and Ass…

### PR DESCRIPTION
**Pull request by pandualuvala**
…ertFailTests

### CODE REVIEW

**Comment by CharliePoole** [comment]
What problem are you trying to solve here? This seems like an arbitrary change.

**Comment by pandualuvala** [comment]
Yes it doesn't fix anything. I just saw there are namespace conflicts for most of the classes in Nunit.TestData i don't know if you had intentionally kept them or no one noticed them. I just wanted to try see if i clean one class if you were merging it. If you feel that it is fine with you to clean the namespace conflicts. I can clean all the classes and make a pull request.

**Comment by rprouse** [comment]
This is a fairly arbitrary change, but the namespace was possibly a mistake? Do you see any issues with accepting the change @CharliePoole ?

**Comment by CharliePoole** [comment]
@pandualuvala What do you mean by a "namespace conflict?" Are you saying that because all the classes are not in the same namespace?

@rprouse I too feel it's somewhat arbitrary. Of course, the way I set it up was arbitrary as well. 😄 Depends how you want it organized. Certain tests do depend on the structure, however. Certainly the SetUpFixture tests, maybe others.

**Comment by pandualuvala** [comment]
@CharliePoole yes i just saw they were not in correct namespace. It really doesn't fix anything. I thought it will make more meaning if the namespaces are correctly referred. I don't know if you have them intentionally left in the previous namespace.

**Comment by CharliePoole** [comment]
I still don't understand what you mean by "not correct." However, it's up to @rprouse .

**Comment by jnm2** [comment]
> I still don't understand what you mean by "not correct."

I think the impression is due to ReSharper putting a suggestion squiggly under namespaces that don't match the folder location of the file. You do have to fight VS tooling a bit with new files when the namespace doesn't match (root namespace) + (folder structure).

**Comment by rprouse** [comment]
Even without Resharper, I've had issues with class names being the same as their namespace forcing me to qualify. It isn't an issue in this case because of the way the code is used.

I'll accept this PR @pandualuvala. I hope to see more from you in the future @pandualuvala. If you are looking for issues to work on, check out the `good first issue` and `help wanted` labels on the issues.

**Comment by pandualuvala** [comment]
Thank you @rprouse @CharliePoole @jnm2 for accepting my pull request. I am really exicited for contributing more to the Nunit framework. Yes, often i had issues with namespaces. Now i have something todo for my Passion. Thank you all once again:smile:

**Comment by rprouse** [comment]
@pandualuvala glad to have you on-board. For future reference, we prefer that people work off issues in our backlog so that the work has been discussed and approved. Just avoid issues marked `discussion` or `idea` as we are still working out the details for those. It is also best to post a comment in an issue saying that you are working on it to prevent someone else from taking it.

We look forward to your next PR. If you ever need help, just reach out to us on the mailing list or in an issue. Welcome. 😄

**Pull request merged**
