### PR TITLE
Require test run id to be 2, per docs

### PR DESCRIPTION
**Pull request by jnm2**
https://github.com/nunit/docs/wiki/Test-Result-XML-Format#test-run

> - **Attributes:**
>   - **id** The unique ID of this test. For the test-run, it is hard-coded as "2".

### CODE REVIEW

**Comment by jnm2** [comment]
Found this old branch and thought I had never pushed it, but GitHub helpfully brought up Charlie's commit comments and now I know why this commit isn't in master.

**Comment by CharliePoole** [comment]
Funny that nobody ever changed the docs. IMO the word "currently" added to the sentence would clarify it.

**Comment by jnm2** [comment]
@CharliePoole Are you okay with the idea of removing the mention of the value "2" from the docs? The conclusions I imagine the reader could come to range from "this is a distraction" to "I'll depend on this."

**Comment by CharliePoole** [comment]
That's probably the best idea.

**Comment by jnm2** [comment]
Done: https://github.com/nunit/docs/wiki/Test-Result-XML-Format/_compare/427e2237c6de086eb5807339d517ceecfa03f047...1af10f1ab99fd8502edde30d13bb2dbdb9425eb4

**Pull request closed without merging**
