### PR TITLE
Parallel TeamCity Service Messages

### PR DESCRIPTION
**Pull request by chris-smith-zocdoc**
Fixes https://github.com/nunit/nunit/issues/583

Allows TC to understand parallel test execution output. 

Depends on https://github.com/nunit/nunit/issues/582 for parallel assemblies to be parsed correctly.

### CODE REVIEW

**Comment by CharliePoole** [comment]
By depends on #582, I think you mean that this can't actually be tested until #582 is fixed. You'll have to merge or rebase in a way that allows testing and you'll probably need to do a new PR because of the way GitHub handles updates: the "changed files" display seems to only reflect changes to your branch but not changes to the underlying master branch. We can wait and see, however.

**Comment by chris-smith-zocdoc** [comment]
This could be merged before #582 is fixed, that wouldn't harm anything. But you are correct in that we cannot accurately test it until #582 is fixed.

**Comment by CharliePoole** [comment]
I think we'd like to test it first. I'm changing the entire structure of TestPackages for #582, so I'm afraid it's taking a while.

**Comment by rprouse** [comment]
This looks good to me. Once 582 is merged, if necessary, master should be merged into this PR. Once that is done and this is tested, then we can probably merge this.

**Comment by chris-smith-zocdoc** [comment]
https://github.com/nunit/nunit/pull/588 has been merged. I've merged the latest master into this branch.

The only difference I see between the current master and this branch is how namespacing is affected in TC. Since I removed `testSuiteStarted`/`testSuiteFinished` the dll is no longer part of the test name. This causes tests with the same name in different dlls to look like a single test. 

Left is Before, Right is After.
image


Other than that, TC is parsing the output correctly when the runner is using multiple threads.

**Comment by CharliePoole** [comment]
@chris-smith-zocdoc I don't understand how TC can be confusing tests of the same name in multiple assemblies, since they would have different IDs. What am I missing?

**Comment by chris-smith-zocdoc** [comment]
@CharliePoole They have different flow ids but the have the same name. Previously this wasn't an issue because TC knew which dll they belonged to. To mitigate this we would need to include the dll in the test name

Example 

##teamcity[testStarted name='NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine' captureStandardOutput='true' flowId='4-1003']

##teamcity[testStarted name='NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine' captureStandardOutput='true' flowId='1-1023']

**Comment by CharliePoole** [comment]
OK. Seems like TC makes this more complicated than it needs to be.

If you think this is ready to merge, then we'll do it, since you're actually the only TC user who's in this conversation as far as I can tell. :-)

For future, let's keep in mind that this is completely separate from what NUnit calls tests, etc. We can pass anything we want to Team City, so long as the reports come out looking OK. For example, we could add our ID to the name if that helped.

You hadn't answered an earlier question of mine, so I'll repeat it... Would you like to work on our TC CI test of NUnit? We currently no longer rely on it for CI but use Travis and Appveyor. However, it would be worthwhile to be able to demonstrate that TC reports NUnit tests correctly. Contact me offline if you would like.

**Comment by AndriusJanusas** [comment]
> I don't understand how TC can be confusing tests of the same name in multiple assemblies, since they would have different IDs. What am I missing?

@CharliePoole Here's the answer from TC forum:
> Since TeamCity 9.0 multiple tests with the same name within the same build are considered a single test with an invocation count. This change results in drop of test number counters in builds which have multiple runs for the same test.
> - https://devnet.jetbrains.com/message/5538066#5538066

**Comment by CharliePoole** [comment]
@AndriusJanusas Hmm... the OP seemed to think that a unique flow-id would separate things. Apparently not. I doubt it's a problem that will come up often, however.

**Comment by CharliePoole** [comment]
I'm going ahead and merging this. It may need to be looked at again once we are running assemblies in parallel processes rather than sequentially.

**Comment by chris-smith-zocdoc** [comment]
@CharliePoole No, the flowId is specific to the parallel execution issue. The duplicate name issue is a unexpected side effect of the `testSuiteStarted/testSuiteFinished` removal. 

> It may need to be looked at again once we are running assemblies in parallel processes rather than sequentially.

What makes you think we would need to look at this again? As far as I can tell, each process should have a unique prefix now. I'll merge the latest master into https://github.com/nunit/nunit/pull/572 to verify everything looks as expected.

**Comment by chris-smith-zocdoc** [comment]
@CharliePoole 

> OK. Seems like TC makes this more complicated than it needs to be.
If you think this is ready to merge, then we'll do it, since you're actually the only TC user who's in this conversation as far as I can tell. :-)

Can't argue with that, I'd be curious what the JetBrains developers will be doing to support NUnit3. For NUnit2 they have a custom test runner that is shipped with TC. I wonder how customized that is compared to what NUnit3 has built in with the TC service message api. 

> For future, let's keep in mind that this is completely separate from what NUnit calls tests, etc. We can pass anything we want to Team City, so long as the reports come out looking OK. For example, we could add our ID to the name if that helped.

We should probably keep them as close to identical as possible. I don't think we should add the id to the name.

> You hadn't answered an earlier question of mine, so I'll repeat it... Would you like to work on our TC CI test of NUnit? We currently no longer rely on it for CI but use Travis and Appveyor. However, it would be worthwhile to be able to demonstrate that TC reports NUnit tests correctly. Contact me offline if you would like.

I wouldn't mind helping set this up, TC is fairly easy to get going. We can work it out over email.

**Comment by CharliePoole** [comment]
I forgot you were also working on #572. In which case, I assume you'll coordinate with yourself. :-)

Yes, send me a note at charliepoole AT gmail DOT com and we'll chat.

**Comment by AndriusJanusas** [comment]
Hi Chris,

Have you tested your changes in TeamCity? Did it work for you?

I tried that and for me only passed tests count is correct, but not ignored/failed tests count.
Please take a look into [this](https://groups.google.com/d/msg/nunit-discuss/X2-LDrsxXXc/FA8Vq8IwRYgJ) thread to see more details.

**Comment by chris-smith-zocdoc** [comment]
@AndriusJanusas I haven't had any issues with TC with these changes.  Do you have a sample project that reproduces the issue that I can look at? Which version of TC are you using? What command are you running NUnit with?

**Comment by AndriusJanusas** [comment]
@chris-smith-zocdoc 

Unfortunately I don't have a sample project, which I can share with you.

I'm using TC 9.0.4 and the following command line to run tests:

    ..\libs\NUnit-3.0.0-beta-2\bin\nunit-console.exe My.Tests.dll --include=Selenium --labels=Off --result=TestResult.xml;format=nunit2 --noheader --workers=10 --teamcity

**Comment by AndriusJanusas** [comment]
@chris-smith-zocdoc Have you tried to take a look at this issue? Have you been able to reproduce it?

**Comment by chris-smith-zocdoc** [comment]
@AndriusJanusas No I haven't had the time, if you could setup a reproducible test case it would be much easier for me to look into.

**Comment by AndriusJanusas** [comment]
@chris-smith-zocdoc I tried to create a dummy tests project and reproduce this bug, but results are shown fine and I don't know why.. However it reproduces in my project, but unfortunately I can't share this project with a public. Any ideas how to reproduce this bug are welcome.

**Comment by AndriusJanusas** [comment]
@chris-smith-zocdoc I figured out what was wrong. I had 3 tests similar like this:

        [Test]
        [TestCaseSource("GetRequiredFields", Category = "Unit")]
        public void Registration_Form_Foo_Bar(TestPair propertyValuePair)
        {
            ValidateTestCase(propertyValuePair);
        }

Each of them run multiple times (34 or something like that) with different tests cases.
If those tests are ignored, TeamCity doesn't count them at all. If they're not ignored - TeamCity gets the count, but it's incorrect for some reason (e.g. instead of 138 it counts 121).

So, I guess, it's not NUnit issue. It's probably my tests and/or TeamCity problem.

**Comment by CharliePoole** [comment]
My guess is that some of the tests have the same test name. This will happen if TestPair.ToString() does not provide a unique value for each data item.

**Comment by AndriusJanusas** [comment]
I haven't tested, but from test cases count I guess, that it considers `new TestPair(r => r.Username, null)` and `new TestPair(r => r.Username, string.Empty)` as the same one.

**Comment by CharliePoole** [comment]
It's a general problem. Many programs that use NUnit assume the test name is unique although it need not be.

**Pull request merged**
