### PR TITLE
Allow null string message to be passed to Assert.That

### LINKED ISSUE #4532: Assert.That no longer allows 'null' message
I encountered NUnit extension methods that have a signature with: `string? message = null` which eventually calls into some version of `Assert.That(actual, constaint, message)`. These no longer compile.

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #4532

### CODE REVIEW

**Review by stevenaw — APPROVED** [review]
LGTM. Good catch @manfred-brands

**Comment by manfred-brands** [comment]
> LGTM. Good catch @manfred-brands

I only noticed it because some my work's NUnit extensions didn't compile anymore with version 4.

**Comment by OsirisTerje** [comment]
@manfred-brands Awesome!  Very good that you found this before real release.  The more we manage to test the beta, the more likely it is we wont have any hotfixes.

**Comment by OsirisTerje** [comment]
@manfred-brands Could be interesting if you wrote up your experiences, could be useful for creating a migration guide.

**Pull request merged**
