### PR TITLE
Typeo in WorkItem.cs cause abort to fail

### PR DESCRIPTION
**Pull request by oznetmaster**

### CODE REVIEW

**Comment by rprouse** [comment]
Code change looks fine, but we did get one test run failure in Mono 3.2.8 on Linux. It may just be one of those random Mono bugs that we run into occasionally, so I have restarted that build, but take a look at this callstack and let me know if it might be related to any of your other recent changes? Maybe a race condition?

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Threading.Tasks.TaskContinuation.ContinuationStatusCheck (TaskContinuationOptions kind) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.TaskContinuation.Execute () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ContinueWith (IContinuation continuation, Boolean canExecuteInline) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ContinueWithCore (System.Threading.Tasks.Task continuation, TaskContinuationOptions options, System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ContinueWith (System.Threading.Tasks.TaskActionInvoker invoker, CancellationToken cancellationToken, TaskContinuationOptions continuationOptions, System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ContinueWith (System.Action`1 continuationAction, CancellationToken cancellationToken, TaskContinuationOptions continuationOptions, System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at Microsoft.Runtime.CompilerServices.TaskAwaiter.OnCompletedInternal (System.Threading.Tasks.Task task, System.Action continuation, Boolean continueOnCapturedContext) [0x00000] in <filename unknown>:0 
  at Microsoft.Runtime.CompilerServices.TaskAwaiter`1[System.Int32].UnsafeOnCompleted (System.Action continuation) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Int32].AwaitUnsafeOnCompleted[TaskAwaiter`1,<One>c__async0] (Microsoft.Runtime.CompilerServices.TaskAwaiter`1& awaiter, NUnit.Framework.Constraints.Tests.<One>c__async0& stateMachine) [0x00000] in <filename unknown>:0 
```

**Comment by rprouse** [comment]
Oops, mistake in copy paste. This is the full callstack,

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Threading.Tasks.TaskContinuation.ContinuationStatusCheck (TaskContinuationOptions kind) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.TaskContinuation.Execute () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ContinueWith (IContinuation continuation, Boolean canExecuteInline) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ContinueWithCore (System.Threading.Tasks.Task continuation, TaskContinuationOptions options, System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ContinueWith (System.Threading.Tasks.TaskActionInvoker invoker, CancellationToken cancellationToken, TaskContinuationOptions continuationOptions, System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.ContinueWith (System.Action`1 continuationAction, CancellationToken cancellationToken, TaskContinuationOptions continuationOptions, System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at Microsoft.Runtime.CompilerServices.TaskAwaiter.OnCompletedInternal (System.Threading.Tasks.Task task, System.Action continuation, Boolean continueOnCapturedContext) [0x00000] in <filename unknown>:0 
  at Microsoft.Runtime.CompilerServices.TaskAwaiter`1[System.Int32].UnsafeOnCompleted (System.Action continuation) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.Int32].AwaitUnsafeOnCompleted[TaskAwaiter`1,<One>c__async0] (Microsoft.Runtime.CompilerServices.TaskAwaiter`1& awaiter, NUnit.Framework.Constraints.Tests.<One>c__async0& stateMachine) [0x00000] in <filename unknown>:0 
An error occured when executing task 'TestAllFrameworks'.
Error: 255 tests failed
```

**Comment by oznetmaster** [comment]
They made no sense to me, and all tests pass now.

**Comment by rprouse** [comment]
Yah, it looks like an error with the mono thread task library. The callstack is documented here now in case we see it again. I am going to merge this.

**Pull request merged**
