### PR TITLE
Move environment and settings elements. Fixes #887.

### LINKED ISSUE #887: Move environment and settings elements to the assembly suite in the result file.
This is work that was postponed from #254.

We need to examine all attributes under the current environment element and determine where to move that information which actually varies from process to process. Some info will vary by machine as well but that can wait until we support remote execution.

### PR DESCRIPTION
**Pull request by CharliePoole**
Both elements are now at the assembly level. This entails some repetition for certain settings but it gets the information to the right place and takes care of situations where some environment variables or settings vary for different assemblies.

### CODE REVIEW

**Comment by rprouse** [comment]
Looks good to me.

**Comment by oznetmaster** [comment]
Does nunitlite need to be changed as well, since it does not use the FrameworkController?

**Comment by CharliePoole** [comment]
@oznetmaster Originally, the fix was elsewhere. After I moved it to the FrameworkController, I realized that NUnitLite would no longer generate these elements. I thought about #if ing it out, but decided to leave it. It's possible we may want to put it elsewhere at some point, but right now it's just another block of code (like the rest of Framework controller) that is never called when using NUnitLite.

As you suggeset, NUnitLite could make up for this deficit by generating the entries itself. I figured that might be an enhancement at some point but didn't do it right away because NUnitLite is somewhat fluid at this point. As an alternative, we could move the code to the assembly runner, which I think would require an interface change.

What are your thoughts on this? What about timing?

**Comment by oznetmaster** [comment]
My concern is having a different structure in the result file for nunit and nunitlite.

I use the same GUI (which I wrote) to display results from both.  I would prefer not to have to differentiate between the two.

I would assume that other programs that utilize the results file would feel the same?

**Comment by CharliePoole** [comment]
It's not a different structure, it's an element that may not be present. This is pretty common in our output and most programs seem to deal with it by checking for the presence of the element. Isn't that what you are already doing about the test-run and environment elements?

The settings element is new and you won't have it in NUnitLite unless we add it somewhere. I can see that it would be quite useful.

I do understand the concern. Can you say precisely what you think we should do and when we should do it? To the point, should we make this a part of 3.0, holding it up if necessary?

**Comment by rprouse** [comment]
Isn't it just missing elements in NUnitLite which a tool should ignore?

@oznetmaster, you should put your GUI tool up on GitHub, I bet others would find it useful :smile:

**Comment by oznetmaster** [comment]
I though you changed the position of the environment element as well, or am I confused?

**Comment by oznetmaster** [comment]
I think it should be in nunitlite 3.0 if possible.  Is it a big thing to do?

**Comment by oznetmaster** [comment]
And yes, my tool ignores missing elements.

**Comment by CharliePoole** [comment]
The position changed from the test-run element to the top-level test-suite.

I looked at the code and I now see what you mean. I had forgotten that
NUnitLite itself creates a test-run element and adds an environment element
under it. It's not a bad place for it in the case of nunitlite, since there
is only a single assembly to worry about. But it is an inconsistency. I'll
create an issue.

**Pull request merged**
