### PR TITLE
Removed redundant casts

### PR DESCRIPTION
**Pull request by sean-gilliam**
Redundant casts are redundant.

### CODE REVIEW

**Comment by CharliePoole** [comment]
This looks good, but needs to be tested on some platforms that the CI builds don't handle. I'm pulling it down to do that now.

@sean-gilliam We don't normally do this sort of thing - making a system-wide pass to fix something that works but just isn't good code. I assume you did it as a way to get into the swing of making contributions, which is all for the  good. Normally, we would just fix such things as we encounter them.

That said, I can see there's actually a common underlying cause to all of these fixes. They are all left over from NUnit 2.x, which supports .NET 1.1 and therefore uses ArrayLists to hold varying lists of things. Each instance seems to have become redundant when generics were introduced into the code, so we should have caught them at that point but didn't.

**Comment by sean-gilliam** [comment]
@CharliePoole I'll keep that in mind for future commits to this project. I was just going by the motto "A clean codebase is a healthy codebase."

**Comment by CharliePoole** [comment]
Checks out on Silverlight, Portable build and Compact Framework... merging.

**Comment by CharliePoole** [comment]
@sean-gilliam No problem here... it just took me a bit of head-scratching to figure out where all these casts had come from.

**Pull request merged**
