### PR TITLE
Use cecil in TestEngine instead of reflection or AssemblyReader

### PR DESCRIPTION
**Pull request by CharliePoole**
Please review and comment...

This PR removes use of ReflectionOnlyLoad from the engine, as called for in issue #654 and also eliminates our own AssemblyReader class used to select the runtime target for a test assembly.

As a spike, I simply used the Cecil nuget package rather than building it ourselves. If we need some capabilities that require building or we want to reduce the footprint, then we can later switch to our own custom build.

Cecil is used at two points in the engine...

1. RuntimeFrameworkService uses it to find the target runtime for which a test assembly was built as well as the bitness of the test assembly. This info is passed along in the TestPackage for later use.

2. DriverService uses it to inspect references to assemblies, which are then checked to see if they represent known test frameworks supported by the drivers. I modified IDriverFactory to take the name and version of the referenced assembly, so that folks writing new drivers would not have to reference Cecil.

Ideally, we would combine these two uses into a single point. However the first is called by the initiating process and the second in the process running the test. It might be possible to check for a reference to nunit 3 on the first call and thereby avoid the extra call later, but there is no evidence that this is actually a performance issue.

The TestEngineActivator class in the nunit.framework.api assembly is still using ReflectionOnlyLoad. While we could Cecil here as well, this seems unnecessary. We know what version we are installing when we install it and it seems better for us to simply save that information in the registry or elsewhere and completely avoid reflecting over the installed engines in order to select one.

Summarizing:

Using Cecil seems to work well. We still need to decide...

1. Whether to build Cecil ourselves
2. Whether we need to worry about loading each test assembly twice through Cecil.
3. How to handle TestEngineActivator.

A further (but side-) issue is that this adds yet another binary to our repo. Maybe we should do a push on making NuGet restore work correctly.

### CODE REVIEW

**Comment by CharliePoole** [comment]
@nunit/core-team This needs some review. I'll modify it further based on comments I get.

**Comment by rprouse** [comment]
Sorry it took me so long to get at this. I like the approach, it seems to simplify our code where it was used. 

For your questions, my thoughts are;

1. We shouldn't build Cecil ourselves unless there is a strong need
2. Everything I see states how performent Cecil is. Unless we see issues, I don't think we should worry about loading twice.
3. Based on what we decide here, changing TestEngineActivator could be another spike. If the code ends up being cleaner and easier to maintain, then we can go with it.

**Comment by CharliePoole** [comment]
@rprouse In that case, we may be ready to merge this. The performance issues can come later. I'll take a final pass through the code and then merge it.

 WRT item 3 I'd like to see if we can simply store registry or other info about the version of each assembly we install. It seems silly to be reading the engine assembly to select the version and it might be better if runners that use the api assembly don't have to also include cecil. But that can be a separate PR if necessary.

**Comment by oznetmaster** [comment]
I just want to nite that the version of Cecil that I use in the CF core engine is only 50k in size.   I do not think that is a significant overhead.  Actually, in the CF core engine, I not use separate assembly, but include Cecil as part of the core engine, although I also have a separate assembly.  I go back and forth about which is the better way to go.

Greetings from Livingstonr, Zambia!

**Comment by rprouse** [comment]
The smaller size is a nice feature, but I think that less code to maintain ourselves should take priority unless we have a compelling reason to do otherwise. Are there parts of Cecil that don't compile on CF or are you memory constrained?

**Comment by oznetmaster** [comment]
Cecil requires a special build.  It is already built into the Cecil source code, but there is no cf project provided to actually build it.  I enable both the cf and read only conditionals for the cf build.

**Comment by oznetmaster** [comment]
Additionally, cf is usually memory constrained, so I actually also have mini-Cecil that is even smaller, the 50k version.  Release cf and read only Cecil is about 150k.

**Comment by CharliePoole** [comment]
@oznetmaster There's no doubt that any use of Cecil in CF requires building it for CF. And once you are building it, it makes sense to build the read-only version.

 However, the only place we are currently experimenting with Cecil is in the full Engine on the desktop. It will be easy enough to build Cecil if and when it becomes necessary. Right now, the "simplest thing that can possibly work" is to use the published package. So far, it seems to work well. I've been waiting for quite some time for somebody to review it and now that Rob has done so, I'm inclined to merge unless you see any problems for what we are doing right now, as opposed to what we might need to do in the future.

**Comment by oznetmaster** [comment]
There was a published read only package at one point in time.  Is it not still there?

**Comment by CharliePoole** [comment]
@oznetmaster I'm not able to find one, but we could definitely switch to it if we find it. For desktop use, I don't think the size matters though.

**Pull request merged**
