### PR TITLE
fixing #2965

### PR DESCRIPTION
**Pull request by MaximRouiller**
fixing #2965

### CODE REVIEW

**Comment by CharliePoole** [comment]
Looks good to me. Thanks.

**Comment by jnm2** [comment]
@MaximRouiller This is greatly appreciated!

**Comment by mikkelbu** [comment]
@jnm2 Note that this did not auto close #2965, but perhaps we should leave that issue open until we have closed all the other issues?

**Comment by jnm2** [comment]
@mikkelbu Yes, that should stay open until there is an issue or merged PR for each repository.

**Pull request merged**
