### PR TITLE
Isolate packaging from building - #568

### PR DESCRIPTION
**Pull request by CharliePoole**
**Incomplete - Do Not merge**

The initial commit modifies the packaging so that all input is taken from the package working directory.

NuGet:
Copy files from the working directory rather than the bin directory

Msis:
Provide parameters for location of the source files and the target directory for output.
Do a rebuild from the script so that passed in properties are actually effective
Keep VS build working with default parameters

### CODE REVIEW

**Comment by CharliePoole** [comment]
The msi fix is messy. It required a lot of manual edits to the wixproj files. Because the bin\Config directories have a different structure from the install image, two properties are passed in, one for the root files and one for the binaries. This allows building from within vs without any passed in arguments.

@rprouse This is something I'd like you to look over since you authored the wixproj files.

**Comment by CharliePoole** [comment]
Next step is to decide 
* Where to keep the zipped install images
* How to recover them
* How to initiate a repackaging operation

One possibility is to move the PackageWorkingDirectory elsewhere in the tree, since the package directory may be cleaned from time to time. A deploy directory with subdirectories by version makes some sense. Alternatively, it could be entirely outside of the working directory structure, i.e. ..\something.

We could either automatically deploy to this directory when packaging or have a separate command.

The "repackage" command could just package right out of this directory, based on the package version.

@nunit/core-team I'm looking for suggestions, since we'll all be using these commandds.

**Comment by CharliePoole** [comment]
This fixes #560 now and will fix #568 when complete.

**Comment by rprouse** [comment]
This is one where we need the `?w=1` when reviewing changes :smile: 

@CharliePoole, you and I need to make sure we have all of the editors that we use to edit the XML files like NUnit.proj setup the same way for tabs and spaces. I know I jump between Notepad++, Sublime and Visual Studio and I always seem to be messing the formatting in our XML up.

Apart from that, this looks good to me. The hand edited changes to the project files make sense and everything seems cleaner taken as a whole. I think it is a step in the right direction.

**Comment by rprouse** [comment]
For tabs and spaces in XML, Visual Studio seems to use `2 space indent` and `replace tabs with spaces` in the various project files. Shall we adopt that so that we can edit NUnit.proj or the project files consistently?

**Comment by CharliePoole** [comment]
@rprouse I agree with that standard. In fact, about half-way through my changes, I updated my VS settings to exactly that. I tend to use notepad sometimes but that's easy: I just use the space bar.

**Comment by CharliePoole** [comment]
Continuing from here... after a night's sleep I think the way to do the packaging is as follows:

1. Continue to build as we do into bin\$(Configuration)

2. Continue to specify the package version and suffix in the NUnit.proj file.

3. Create a new top-level directory to hold multiple package working directories. This isn't essential but I think it's cleaner if we want to retain those directories. I thought of calling it 'deploy' but I'm not sure that really represents what it does. Ideas?

ALTERNATIVE 1
4. Create a new target that copies from the bin directory to the working directory. In fact we have one we can rename as a first-level command. If we stick with a 'deploy' directory, the command could be Deploy.

5. Whenever we package (any package) check that directory for the presence of a working directory with the correct name, matching the version we are packaging. If present, use what is there. If not, create it from the latest build.

ALTERNATIVE 2
4. Whenever we package, create that working directory first, even if it already exists.

5. Create new commands like Repackage... which will skip the creation of the directory. This requires a lot more new commands if we want to be able to repackage a given NuGet package, for example.

*****

I lean toward alternative 1, since it requires only one new command. I'm still puzzled over what to call it, however, and you will have to remember to use that command whenever you package. Either way, we will have to figure out someplace other than our own hard disks to save the info for the official packages we release.

**Comment by rprouse** [comment]
I prefer alternative 1 also. Deploy feels wrong to me too, but I'm not sure I could come up with something better. Archive, PackagingSource, ???

To store the archived official package sources, we could zip the sub-directory for the one release and attach it to the GitHub release with the comment that it is only intended for archival purposes, not public consumption.

**Comment by CharliePoole** [comment]
I rebased this on current master.

**Comment by CharliePoole** [comment]
The current second level command is _CreatePackageImage. We could rename that as either CreatePackageImage or just CreateImage. The directory could be simply images and could contain either subdirectories or zips.

**Comment by CharliePoole** [comment]
Please review the latest commit. There is an images directory - called ProjectImageDir in the script - that holds individual release images. The current one is called CurrentImageDir and replaces the old PackageWorkingDir, which was a subdirectory of package.

All the packaging targets work out of the CurrentImageDir, which is created automatically if it doesn't already exist. If it does exist, the packaging commands will use it, so the latest binaries may not be used. To force rewriting it, you have to explicitly use the CreateImage target.

This approach runs the risk that the latest binaries may not be included in a release but avoids the risk of overwriting an image directory that we may need.

Let's have some comments on this approach before I go any further. You may want to pull this down and try some command-line builds and packaging.

**Comment by rprouse** [comment]
The approach looks good to me, but, as you said, I should probably pull down and test to get a better feeling for it.

**Comment by CharliePoole** [comment]
Of course, we will be exercising it in doing the release. I think the main issue is how and where to archive those images we want to keep. The script won't overwrite them without an explicit target being used, but if you do that then of course the old image of the same name is gone.

This relates to another question: when a developer doing testing runs the packaging commands, what should be built. Maybe the default should be to NOT use the embedded version info but to generate some suffix for the build.

**Comment by rprouse** [comment]
I think I need to see it in action. What you describe sounds good, but I
think the experience of doing a release will be more telling. Shall we
merge and then update based on the experience from the release?

On 7 May 2015 at 15:13, CharliePoole <notifications@github.com> wrote:

> Of course, we will be exercising it in doing the release. I think the main
> issue is how and where to archive those images we want to keep. The script
> won't overwrite them without an explicit target being used, but if you do
> that then of course the old image of the same name is gone.
>
> This relates to another question: when a developer doing testing runs the
> packaging commands, what should be built. Maybe the default should be to
> NOT use the embedded version info but to generate some suffix for the build.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/pull/613#issuecomment-99985806>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by CharliePoole** [comment]
Makes sense to me.

**Pull request merged**
