### PR TITLE
WIP: Add Coverlet Coverage to builds

### LINKED ISSUE #423: Integrate Code Coverage into CI
I just wanted to put this out there as an idea and possibly a future task. I have been experimenting with [OpenCover](https://github.com/OpenCover/opencover) to run code coverage on the project and used [ReportGenerator](http://www.palmmedia.de/OpenSource/ReportGenerator) to generate HTML reports.

So far I've just run one of the framework tests, but we are getting 86.7% coverage which is pretty good. It does highlight some areas that are poorly tested, so I think it is a worthy exercise.

I am using the command line versions of both tools, but they are also available as NuGet packages that add MSBuild tasks.

An alternative might also be to use JetBrains' DotCover. They have a free license for open source teams that we could take advantage of.

### PR DESCRIPTION
**Pull request by SeanKilleen**
Resolves #423.

Putting this out here in super-draft form just to get it started. 

* Updates Cake to v3 and adjusts cake file to new conventions since v1
* Introduces `Cake.Coverlet` as an add-in
* Adds Coverlet collector as part of the tool manifest
* Updates the testing task to use Cake command & coverlet settings

### CODE REVIEW

**Comment by SeanKilleen** [comment]
(I only just now realized that GitHub runs the CI for draft pull requests too -- very helpful to get the benefits of CI without bugging anyone with notifications.)

**Comment by manfred-brands** [comment]
GitHub is still notifying, even for draft PRs.

**Comment by stevenaw** [comment]
@SeanKilleen I don't know if I'd have the time to help with this myself, but would you be open to if someone were to help get this back in sync with recent changes and eventually help get this merged?

**Comment by SeanKilleen** [comment]
@stevenaw I'll see if I can take a look at this tonight. Thanks for the ping! I've been all over the place with job stuff and kid being sick for a few weeks, Good to have the reminder.

**Comment by SeanKilleen** [comment]
Closing in favor of #4722.

**Pull request closed without merging**
