### PR TITLE
Upgrade cake bootstrappers

### PR DESCRIPTION
**Pull request by halex2005**
Here is PR with lastest bootstrappers for cake:

- http://cakebuild.net/download/bootstrapper/linux
- http://cakebuild.net/download/bootstrapper/windows

### CODE REVIEW

**Comment by jnm2** [comment]
I thinking keeping these up to date is good. Ironically I'm in the middle of a PR at https://github.com/cake-build/resources/pull/30 to make the bootstrappers more useful 😆 but don't let that affect this.

Out of curiosity, what does updating the bootstrappers enable you do to?

**Comment by halex2005** [comment]
@jnm2 Actually, I just tried to run build.sh on my ubuntu and I got error ))
After upgrading script works well

**Comment by CharliePoole** [comment]
The bootstrappers are the biggest problem with Cake. At various times, different bootstrappers were available at different URLs without any indication as to which to use. It's also not clear whether the bootstrappers require a particular Cake version or (the opposite) whether a Cake version requires particular bootstrapers. Some statement about this in a readme would be very helpful!

**Comment by CharliePoole** [comment]
Since it's passing our CI, I'm going to say LGTM!

**Comment by jnm2** [comment]
@CharliePoole Couldn't agree more. The times I've tried to get that across to the Cake team, they agreed to disagree. Hopefully https://github.com/cake-build/resources/pull/30 will end up minimizing the bootstrapper's role and make it less likely to need to be updated.

**Comment by CharliePoole** [comment]
That would be great. But at a minimum, there should be info that lets us decide whether we can safely use the latest bootstrapper. Do they guarantee the latest bootstrapper to work with all versions of Cake earlier than some version? Kind of like our guaranteeing the the NUnit V2 console to work with framework versions 2.0 through 2.6.4 and the NUnit 3 console with 3.0 through current - or 2.0 with an extension.

**Comment by halex2005** [comment]
@CharliePoole 

I found these bootstrappers in cake's documentation here: [Setting Up A New Project](http://cakebuild.net/docs/tutorials/setting-up-a-new-project). [This cake-build/resources repo](https://github.com/cake-build/resources) contains lastest version of bootstrappers where they can be found and be contributed.

> It's also not clear whether the bootstrappers require a particular Cake version or (the opposite) whether a Cake version requires particular bootstrapers. Some statement about this in a readme would be very helpful!

Is that so important? As I know, bootstrappers always installs lastest cake version from nuget, you should not specify cake version. If something went wrong, it's likely already fixed or could be fixed with `cake-build/resources` repo.

**Comment by CharliePoole** [comment]
Actually, the bootstrapper installs the version you specify in the tools/packages.config directory. We always specify the latest version that has worked for us because an unexpected upgrade can cause a problem. 

It's also important to keep in mind that the Cake install in your working directory does not get updated automatically when packages.config is updated. You have to delete it for that to happen.

**Comment by halex2005** [comment]
@CharliePoole, despite master branch of nunit contains 0.19.5 cake version in `tools/packages`, the bootstrapper installs 0.18.0 version. I think it is because this version was hardcoded into `build.ps1`: 

```
$CakeVersion = "0.18.0"
```

Is that was intentional? New bootstrapper will honor version from `tools/packages.config` and will install v0.19.5 of cake (and it works, btw).

**Comment by CharliePoole** [comment]
Are you saying someone in NUnit project did that? I can't check right now in repo.

Our practice is not to change these files from cake build.

**Comment by halex2005** [comment]
Here is line: https://github.com/nunit/nunit/blob/master/build.ps1#L34
And it's appeared in [Updated Cake to 0.19.5 commit](https://github.com/nunit/nunit/commit/033dbc0da7915b25ecc27eaff41836acf896fe1e).

**Comment by jnm2** [comment]
@rprouse We don't need this line, do we?

**Comment by CharliePoole** [comment]
@rprouse I'm assuming you didn't actually edit the file but just replaced it with a new one from Cake, right?

**Comment by rprouse** [comment]
Yes, I just dropped in the latest version from Cake. I'm not sure about this change, but the only thing I've ever changed is the version of NuGet. I was also confused the the cake version in the file was not equal to the released version of cake, but it seemed to be respecting what was in my `tools\packages.config` so I just left it.

**Comment by halex2005** [comment]
Let's merge this PR?

**Comment by jnm2** [comment]
Yay the simplified bootstrapper is now merged: https://github.com/cake-build/resources/pull/30

**Comment by jnm2** [comment]
Not sure when it ends up in master- they don't have releases per se.

**Pull request merged**
