### PR TITLE
Revert accidental doc removal

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Another @oznetmaster special -https://github.com/nunit/nunit/commit/acdc5477eae0aa489331199ec07053c9e43b69f2#diff-773ff02e2f8e671f005e32bcf2e9d03eL44

#2296 seems to have caught something it couldn't.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Thanks @mikkelbu 🙂

**Comment by mikkelbu** [comment]
@ChrisMaddock Should it not be an issue that is assigned to a milestone? (this is the only PR with a milestone AFAICT)

**Comment by ChrisMaddock** [comment]
If there's both Issue and PR, assign just the issue. If there's only a PR, assigning the PR is fine. 

The tool that generates the release notes doesn't mind which one is there, but of course we don't want any duplicates. 🙂

**Comment by mikkelbu** [comment]
Understood 👍

**Comment by CharliePoole** [comment]
Having an issue is only important for the humans, especially if there is a need to decide what to do. Also OOF you see a bug and don't plan to fix it in the next few minutes.

**Comment by jnm2** [comment]
Heh, it wasn't accidental. But :+1:

**Comment by ChrisMaddock** [comment]
Ah, ok! I thought it was an odd regex malfunction. ;-) Either way - it's documented !

**Comment by jnm2** [comment]
> I thought it was an odd regex malfunction.

People say that about me a lot. 😁 ;-)

**Pull request merged**
