### PR TITLE
Remove teamcity listener from nunit build

### LINKED ISSUE #1700: Create separate repository for TeamCity extension

### LINKED ISSUE #1702: Create separate repo for teamcity event listener extension
Move the extension code to a new repo and remove it from the nunit repo.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #1702

The new branch at nunit/teamcity-event-listener should be reviewed in conjunction with this.

### CODE REVIEW

**Comment by CharliePoole** [comment]
The iOS builds are all timing out on Travis. Doesn't seem to be an issue with the PR though.

**Comment by CharliePoole** [comment]
This PR applies to the engine only. Needs to be merged before we split per #1598.

**Comment by CharliePoole** [comment]
@nunit/core-team This is waiting for review.

**Comment by rprouse** [comment]
Looks good

**Pull request merged**
