### PR TITLE
Port caching of method discovery to main

### LINKED ISSUE #4053: Cache method discovery by migrating PR 4034 to main
PR #4034 added caching of method lookups. It was merged to 3.13, we should consider also syncing it to main/v4

### LINKED ISSUE #4096: NUnit.Framework 3.13.2 introduced a breaking change that conceals problems with tests
Before NUnit.Framework 3.13.2 running an assembly compiled from the following code 

```
[TestFixture]
public class BrokenTestClass
{
  [Test, Invalid] public void Test() { }
}

public class InvalidAttribute : Attribute
{
  public InvalidAttribute() => throw new InvalidProgramException();
}
```
would issue the `An exception was thrown while loading the test` twice:
 - once inside the xml returned from `ITestEventListener.Explore`,
 - and the second time inside a `<test-suite type="TestFixture" ... />` event for `NUnit.Engine.ITestEventListener`.

The new behavior broke R#/Rider test runner in that a broken test class no longer gets a clear indication of a problem, marking such test as inconclusive instead.

More importantly, the new behavior broke NUnit's own runner in that it no longer reports such errors, making problems of this nature very difficult to notice. For this reason over a 1000 tests weren't running in our CI over a past week without us knowing.

Below is the output of `nunit3-console` running an assembly with broken tests:
```
Copyright (c) 2022 Charlie Poole, Rob Prouse
Wednesday, April 13, 2022 3:49:53 PM

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    c:\Users\jetbrains\source\repos\Tests.Sandbox\Sandbox.NUnit3\bin\Debug\net35\Sandbox.NUnit3.dll


Run Settings
    DisposeRunners: True
    WorkDirectory: C:\Users\jetbrains\Documents\59\bin\net35
    ImageRuntimeVersion: 2.0.50727
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    TargetRuntimeFramework: net-2.0
    NumberOfTestWorkers: 16

Test Run Summary
  Overall result: Passed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2022-04-13 13:49:53Z
    End time: 2022-04-13 13:49:53Z
    Duration: 0.510 seconds

Results (nunit3) saved as TestResult.xml
```

### LINKED ISSUE #4107: Incorrect type specified for Values attribute fails unrelated tests
With the following tests in test container, I expect one test to pass, and another to fail because of the incorrect type of the variable with ValuesAttribute.
```
    [Test]
    public void ThisOnePasses()
    {
    }

    [Test]
    public void ThisOneFails([Values("apple")] int value)
    {
    }
```

For the different NUnit package versions, behaviour is different.

3.10.0 - console message is ok, test report is correct.

```
  Determining projects to restore...
  All projects are up-to-date for restore.
  nunit-sample -> /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll
Test run for /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed ThisOneFails("apple") [15 ms]
  Error Message:
   System.ArgumentException : Object of type 'System.String' cannot be converted to type 'System.Int32'.
  Stack Trace:
     at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)

Failed!  - Failed:     1, Passed:     1, Skipped:     0, Total:     2, Duration:  - /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll (net6.0)
```

3.13.1 - console message is ok, test report is incorrect (no test actually run).
```
  Determining projects to restore...
  All projects are up-to-date for restore.
  nunit-sample -> /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll
Test run for /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Setup failed for test fixture nunit_sample.Tests
An exception was thrown while loading the test.
System.ArgumentException: apple is not a valid value for Int32. (Parameter 'value')
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at NUnit.Framework.Internal.ParamAttributeTypeConversions.TryConvert(Object value, Type targetType, Object& convertedValue)
   at NUnit.Framework.Internal.ParamAttributeTypeConversions.GetData(Object[] data, Type targetType)
   at NUnit.Framework.Internal.ParamAttributeTypeConversions.ConvertData(Object[] data, Type targetType)
   at NUnit.Framework.ValuesAttribute.GetData(IParameterInfo parameter)
   at NUnit.Framework.Internal.Builders.ParameterDataSourceProvider.GetDataFor(IParameterInfo parameter)
   at NUnit.Framework.CombiningStrategyAttribute.BuildFrom(IMethodInfo method, Test suite)
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildTestCase(IMethodInfo method, TestSuite suite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
No test is available in /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

3.13.2, 3.13.3 - console message is misleading, test report is incorrect (no test actually run).

```
  Determining projects to restore...
  All projects are up-to-date for restore.
  nunit-sample -> /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll
Test run for /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in /Users/gp/src/test-allure/src/nunit-sample/bin/Debug/net6.0/nunit-sample.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

### LINKED ISSUE #4426: Testfixture is silently ignored if exception in constructor and DatapointSource
Hi,

It seems test can be silently ignored without any warning or errors if the test fixture constructor throws and there are some usage of non-static DatapointSource.

Here is the repro:
```
namespace TestProject1
{
    [TestFixture]
    public class Tests
    {
        public Tests()
        {
            throw new Exception("Thrown in constructor");
        }

        [DatapointSource]
        private int[] intSource = new int[] { 0, 1, 6, 8, 50 };

        [Test, Theory]
        public async Task Test1(int intVal)
        {
            await Task.Delay(intVal);
            Assert.Pass();
        }
    }
}
```
image

No test is discovered and there is no error.

Now if we do the same code but with a static datapoint source for example then it does throw and fail:
```
namespace TestProject1
{
    [TestFixture]
    public class Tests
    {
        public Tests()
        {
            throw new Exception("Thrown in constructor");
        }

        [DatapointSource]
        private static int[] intSource = new int[] { 0, 1, 6, 8, 50 };

        [Test, Theory]
        public async Task Test1(int intVal)
        {
            await Task.Delay(intVal);
            Assert.Pass();
        }
    }
}
```
image

This can lead to test suites being silently ignored in CIs for example and it is not obvious to detect..

### PR DESCRIPTION
**Pull request by stevenaw**
Fixes #4053
Fixes #4096 in main
Fixes #4107 in main
Fixes #4426

Migrates:
- #4034
- #4104

### CODE REVIEW

**Comment by stevenaw** [comment]
@manfred-brands I was going to ask you for a review on this, but I would instead like to ask for some help :)
I've tried to port both the method caching + your exception handling bugfix but it seems one of the tests in `main` reliably fails. You're more familiar with this change, would you be able to help me out?

> NUnit.Framework.Internal.AttributeThrowingExceptionTests.TestSuiteContainsAllTests(NUnit.TestData.AttributeThrowingExceptionFixture.AttributeOnFixtureThrowingExceptionFixture)

**Comment by manfred-brands** [comment]
@stevenaw I didn't have time today, will look at it tomorrow.

**Comment by stevenaw** [comment]
Thanks @manfred-brands No rush at all. My setup is acting up and I was having a hard time debugging it myself

**Comment by manfred-brands** [comment]
@stevenaw I have traced this to nunit 4.0 specific code introduced with #3926 where it calls unconstrained `GetCustomAttributes`. I have rewritten the `OSPlatformTranslator` so it doesn't do that anymore.

I then looked where else we called `GetCustomAttributes` and removed the last call in `AsyncToSyncAdapter`.
Surprisingly this broke tests.

As Nunit now only interrogates know attributes, it will never trigger any exception from bad behaving 3rd party attributes.
To me this is correct. 3rd party attributes, unless implementing IApplyToTest should not affect NUnit.

**Comment by manfred-brands** [comment]
See my changes on top of your changes https://github.com/nunit/nunit/pull/4137

**Comment by stevenaw** [comment]
Thanks once again for all your help with this @manfred-brands 
I think this is now ready for review

**Comment by stevenaw** [comment]
@nunit/framework-team Is anyone up to reviewing this? It's a large PR but is mostly cherry picks and should sync a few large pieces of work between the two branches

**Comment by OsirisTerje** [comment]
@stevenaw @manfred-brands  This PR is rather big, but it is migration to 4.0 branch.  I tried to look at the changes here, but there is simply too much.  I believe you two have to agree if this looks ok or not, and then we just merge it in.  What could possibly go wrong?

**Comment by stevenaw** [comment]
>  What could possibly go wrong?

🙂
I will volunteer that this PR was largely made by cherry-picking commits. To the best of my knowledge, most merge conflicts are likely related to pattern matching changes in default. I recall having looked at @manfred-brands small post-fix and being ok with it

**Comment by OsirisTerje** [comment]
Ok, then I suggest we just need to fix the merge conflicts and then we merge it, right ?

**Comment by stevenaw** [comment]
That makes sense to me.

**Comment by manfred-brands** [comment]
I will see if I can sort out the conflicts.

**Comment by manfred-brands** [comment]
I have rebased the branch and solved the merge conflicts.

Then added two more commits:
1. Protect the newly added TestSuite.ApplyAttributesToTestSuite from rogue attributes by only asking for relevant attribute.
2. Fix a previously non-detected bug in the recently added 'Add support for ref/in keywords in ValueAtttribute'. Due to the bug the code was throwing in the test discovery resulting in finding zero test and hence not showing a failure. The changes in this branch (commit Exception in ApplyToTest are recognized) now detect this.

Can someone @stevenaw or @OsirisTerje give this a final review?

**Comment by stevenaw** [comment]
Thanks for this @manfred-brands !

> Due to us no longer including System.Runtime, on some platforms the AsyncStateMachineAttribute type is not found. This resulted in a ArgumentNullException.

Ah, I had been a little afraid of something like this. I noticed we simply added a null check. Based on your checking in this PR, should we instead add the reference back (in separate PR) or is it alright as-is?

**Comment by stevenaw** [comment]
This PR looks ok to me. There's been a lot of catch-up it's had to do over the last while, and now that it's caught up I think it'd be great to merge it in.

@OsirisTerje Are you able to approve? I'm unable to as I've created this PR.

**Review by OsirisTerje — APPROVED** [review]
Approved

**Comment by OsirisTerje** [comment]
@stevenaw @manfred-brands 
> Due to us no longer including System.Runtime, on some platforms the AsyncStateMachineAttribute type is not found. This resulted in a ArgumentNullException.

> Ah, I had been a little afraid of something like this. I noticed we simply added a null check. Based on your checking in this PR, should we instead add the reference back (in separate PR) or is it alright as-is?

I could not see this in this PR, so I assume it was done somewhere else.  If it fails on some platforms, we better add it back.  I noticed we do refer to that assembly in this PR (by reflection).  Its better to be safe than sorry wrt to this.

**Comment by stevenaw** [comment]
@OsirisTerje I suspect the runtime/reflection issue could be from #4335 . I can spin up a PR to add it back, with a test for the used functionality

**Pull request merged**
