### PR TITLE
#4602 WpfMessagePumpStrategy

### LINKED ISSUE #4602: WpfMessagePumpStrategy - change from Dispatcher.Run to Dispatcher.PushFrame
Currently when awaiting an awaitable test nunit post to the context and calls Dispatcher.Run. In the Post a continuation is scheduled which calls ExitAllFrames on the dispatcher. This leads to some problems if there is already a frame running. 

My idea (and I have a working version) is to create a DispatcherFrame and call PushFrame on the Dispatcher. If the posted action is completed just set frame.Continue to false. This will cause the PushFrame to return and will not disturb a previously pushed frame. Would you guys be interested in a PR for this?

### PR DESCRIPTION
**Pull request by soerendd**
Replace Dispatcher.Run with PushFrame as Dispatcher.Run needs to exit all frames to return properly which causes issues if there is already an outer frame.

Should fix #4602

### CODE REVIEW

**Review by jnm2 — APPROVED** [review]
Thanks so much! LGTM

**Comment by jnm2** [comment]
If it's possible to write a test that fails for the previous strategy and succeeds here, that would be great.

**Comment by soerendd** [comment]
> If it's possible to write a test that fails for the previous strategy and succeeds here, that would be great.

Sure thing. I checked if there is a test for the message pump strategies. There are none.

I will check where to add this test

**Comment by soerendd** [comment]
> > If it's possible to write a test that fails for the previous strategy and succeeds here, that would be great.
> 
> Sure thing. I checked if there is a test for the message pump strategies. There are none.
> 
> I will check where to add this test

@jnm2  I'm sorry but I haven't found a place where to put tests for that. The reason is that it would require a reference to System.Windows.Threading (wpf) and I do not see an easy way to mock this properly.

**Comment by OsirisTerje** [comment]
@soerendd The builds fails due to a mismatch on sdks.  This is fixed in the master branch, so if you just merge in the master branch and push that up, the builds should work just fine.

**Comment by soerendd** [comment]
@OsirisTerje Merged and pushed.

**Pull request merged**
