### PR TITLE
Solution to "DelegatingConstraintResult does not use its _innerResult for WriteMessageTo "

### PR DESCRIPTION
**Pull request by 0ZeKa0**

### CODE REVIEW

**Comment by 0ZeKa0** [comment]
@dotnet-policy-service agree [company="{ }"]

@dotnet-policy-service agree

@dotnet-policy-service agree company="Microsoft"

**Comment by 0ZeKa0** [comment]
@dotnet-policy-service agree

@dotnet-policy-service agree company=" "

**Comment by 0ZeKa0** [comment]
[> @0ZeKa0 the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @dotnet-policy-service agree
> ```
> 
> and
> 
> ```
> @dotnet-policy-service agree company="your company"
> ```



> @0ZeKa0 the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @dotnet-policy-service agree
> ```
> 
> and
> 
> ```
> @dotnet-policy-service agree company="your company"
> ```
](https://github.com/nunit/nunit/pull/4714#issuecomment-2116267417)

**Comment by 0ZeKa0** [comment]
> @0ZeKa0 the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @dotnet-policy-service agree [company="{ }"]
> ```
> ```
> @dotnet-policy-service agree
> ```
> 
> and
> 
> ```
> @dotnet-policy-service agree company=" "
> ```

**Comment by 0ZeKa0** [comment]
> ```
> @dotnet-policy-service agree
> ```
> 
> and
> 
> ```
> @dotnet-policy-service agree company=" my company"
> ```

**Comment by manfred-brands** [comment]
Can you add an unit test to show the original problem you fixed?

**Pull request closed without merging**
