### PR TITLE
remove redundant null check in TestFilter

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by manfred-brands — APPROVED** [review]
It would be nice if the compiler told us about these.

**Comment by SimonCropp** [comment]
> It would be nice if the compiler told us about these.

agreed

**Comment by SimonCropp** [comment]
can we get a merge?

**Comment by mikkelbu** [comment]
@SimonCropp Thanks for all the PRs. Regarding the merge, then I can take a look at this PR and the other PRs tonight when I'm at a computer.

**Review by stevenaw — APPROVED** [review]
Likewise, thanks @SimonCropp for all the contributions. 🙂 Like @mikkelbu I'll also work through these as my own timing permits this weekend. This one looks good to me too 👍

**Pull request merged**
