### PR TITLE
914 clear error message from console runner when no tests or driver f…

### PR DESCRIPTION
**Pull request by michal-franc**
…ound
#914

### CODE REVIEW

**Comment by CharliePoole** [comment]
This may be too pedantic, but "No suitable tests found..." seems to imply we looked for tests and couldn't find them. How about...

"The assembly <assemblyname> does not reference any known framework. No tests were loaded."

If you wanted to go long, you could add "If the tests require a non-standard driver, make sure it is installed."

@rprouse What do you think?

**Comment by rprouse** [comment]
I don't mind the wording in this PR, but I don't mind "The assembly does not reference any known framework. No tests were loaded." either. Maybe "The assembly does not reference any known **test** framework. No tests were loaded."?

**Comment by rprouse** [comment]
That said, I think this pr is an improvement on the current message, so I would be happy to merge as is too.

**Comment by CharliePoole** [comment]
The Travis failure is unrelated. I'll go ahead and merge it.

**Pull request merged**
