### PR TITLE
#1623 Change EngineVersion to "3.4.0.0" for attribute Extension for TeamCityEventListener

### PR DESCRIPTION
**Pull request by NikolayPianikov**

### CODE REVIEW

**Comment by rprouse** [comment]
I thought @charliepoole said this wouldn't kick in until 3.6,thus the higher number. It could be it isn't loaded for another reason. Can you comment @charliepoole. 

@NikolayPianikov, would it make sense for you to set up a TeamCity CI server against NUnit to ensure we don't break your integrations. If you want to do that, probably best to wait a few weeks until we split up the repository.

**Comment by NikolayPianikov** [comment]
@rprouse  I've tested the integration - extension works fine

**Comment by CharliePoole** [comment]
@rprouse What I meant was that the check would not be useful till 3.6, since 3.4 is the first one implementing it. I put 3.6 into the attribute to do tests. It should not have got into a PR but apparently did.

@NikolayPianikov I think Rob is saying we need to run integration tests before releasing!

**Comment by CharliePoole** [comment]
I merged this, but we need to do some more work to fix the problem.

**Comment by NikolayPianikov** [comment]
Yes we have integration tests, but for the last relesed version only. I will add them for the master branch.

**Comment by rprouse** [comment]
Thanks @NikolayPianikov. Are those tests internal only, or can we get some visibility into them?

**Comment by NikolayPianikov** [comment]
Another one question is what happens when user restores packages via a nuget command? Will all plugins have to work without any triks?

**Comment by NikolayPianikov** [comment]
I will try to move them to the external build server.

**Comment by CharliePoole** [comment]
The big question for me is was why our CI passes. The answer is simple...

1. We have no unit tests of the teamcity extension.
2. We have one functional test that ensures all known extensions are recognized, but the teamcity extension was never added to it.
3. And, of course, we have no automated integration tests.

Embarrassing as it is, maybe one theme for the 3.6 release is to improve our own testing!

@NikolayPianikov I'm going into a meeting now. I'll come back to you in a few hours and maybe we can work together to get this done better, first for 3.4.1 and then for later on.

**Comment by CharliePoole** [comment]
@NikolayPianikov Keep watch on the 3.4.1 milestone, which we will finish very quickly. It has only two issues in it. let me know if there are other things that seem critical and have a quick solution!

**Comment by NikolayPianikov** [comment]
@rprouse @CharliePoole see integration tests [here](http://win10nik.cloudapp.net/viewType.html?buildTypeId=NUnit_NUnit3IntegrationTests).

**Pull request merged**
