### PR TITLE
New assertion constraint superset of (#753)

### LINKED ISSUE #753: Feature request: Is.SupersetOf() assertion constraint
See https://bugs.launchpad.net/nunit-3.0/+bug/1184903.

### PR DESCRIPTION
**Pull request by Seddryck**
Resolve #753 by implementing the constraint supersetOf (based on subsetOf)

### CODE REVIEW

**Comment by CharliePoole** [comment]
This generally looks ready to merge to me, with one exception.

CollectionAssert is a legacy class that emulates the features of MSTest CollectionAssert. In general, we have not added new features to it in the past, when we created new constraint syntax. I don't think I would add the feature in this case either. If we add it, we will have to explain in the future why we add some things and not others. :-)

@nunit/core-team What do you think? We need a second review to merge this in any case.

**Comment by CharliePoole** [comment]
@nunit/core-team Some of the most active folks are tied up. We need some others of you to step up and do PR reviews! Please.

**Comment by rprouse** [comment]
The code looks good. The new constraint also needs to be added to the Compact Framework project. @Seddryck, you can do that by manually editing the file if you want, or one of us can do it.

As for adding to the `CollectionAssert` class, I am of two minds in this case because it provides the compliment to IsSubsetOf. I agree that we shouldn't be adding indiscriminately, but I think this is one case that we should allow. Then again, maybe I just like symmetry too much :smile:

**Comment by Seddryck** [comment]
@rprouse new constraint added to the CF, I missed this project.

**Comment by CharliePoole** [comment]
I'll run the tests and then merge.

**Comment by CharliePoole** [comment]
I'm going with Rob's view that symmetry calls for modifying CollectionAssert.

**Pull request merged**
