### PR TITLE
Move towards coding standards in small steps

### PR DESCRIPTION
**Pull request by agray**

### CODE REVIEW

**Comment by CharliePoole** [comment]
Do you want this merged? Or do you want to wait till some group of things is done?

Doing it in small steps helps you to keep it working, but it doesn't necessarily help us in reviewing. If we wait, the sum total will be the same amount of stuff to review. We're already up to 73 files. That might be enough for a review. It's mostly the engine I see, which is good too.

FYI, a convention we have generally established is that any PR is ready to review and merge unless the description says otherwise. For example, see #588.

**Comment by CharliePoole** [comment]
I'm seeing Javascript-like braces. What's that about?

**Comment by OsirisTerje** [comment]
I would not like to see this merged.  This seems to be the same as the previous one, and again only contain syntax changes, and many not even agreed upon, ref discussion on Dev list.

**Comment by CharliePoole** [comment]
I can see that even as far as you have gone, this is going to create all sorts of merge conflicts with other work that's going on. I think we had a slight misunderstanding. I thought that your small steps would involve multiple PRs, which we could merge separately. I suggest we stop here for a moment so it doesn't get too big. I'll start the individual review.

**Comment by agray** [comment]
This PR is about coding standards so yes, it is syntax changes.  It is not the same as the previous one:  It is much smaller and it passes the checks.  It's pretty small at  "+439 −623".

**Comment by oysteinkrog** [comment]
IMO many of these changes are bad:
1. The curly brace changes is very nonstandard for C#.
2. Use of var can be helpful but I find that for large open source projects it is much better to use explicit types as it helps when reading unknown code.

**Comment by agray** [comment]
This is a test comment only

**Comment by sean-gilliam** [comment]
I like the changing of the fields to readonly and the xmldoc bits, but this PR is all over the place with changes (with some of them potentially worrisome like @oysteinkrog listed). I'd suggest more logically grouping of issues into separate PRs like @CharliePoole mentioned. Just my 2c.

**Comment by CharliePoole** [comment]
Most comments tend toward not doing large changes like this so I think we should just close it . Thanks @agray  for your efforts. Hopefully you'll keep contributing on other issues.

**Pull request closed without merging**
