### PR TITLE
Rename Common.props to Directory.Build.props

### PR DESCRIPTION
**Pull request by sharwell**
:bulb: Please do not rebase or squash this pull request on merge.

### CODE REVIEW

**Comment by mikkelbu** [comment]
@sharwell Before looking at the change (and skimming https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build) I was wondering what value this rename would provide, but I can understand that `Directory.Build.props` is a "reserved" filename that is handled specially by msbuild.

Ps. Not being an git expert I was wondering why you have added "Please do not rebase or squash this pull request on merge". What is the problem with this (just being curious about git).

**Comment by sharwell** [comment]
> Before looking at the change I was wondering what value this rename would provide...

Three improvements are:

1. When seeing this file, developers understand how/where it will be used during a build (at least to a point of understanding consistency)
2. Eliminates the need to manually import the file
3. It works better with up-to-date checks during the build by avoiding the limitations described in Microsoft/msbuild#1299 and various linked issues

**Comment by sharwell** [comment]
@mikkelbu Fixed

**Comment by ChrisMaddock** [comment]
Rebuilding Appveryor - another unrelated .NET 3.5 failure. :-(

All in favour of more convention - I'll stand back to @jnm2's expertise here though! 😄 

```
1) Failed : NUnit.Framework.Internal.Execution.EventQueueTests+DequeueBlocking_StopTest.DequeueBlocking_Stop
  Expected: True
  But was:  False
   at NUnit.Framework.Internal.Execution.EventQueueTests.ProducerConsumerTest.RunProducerConsumer() in C:\projects\nunit\src\NUnitFramework\tests\Internal\EventQueueTests.cs:line 296
   at NUnit.Framework.Internal.Execution.EventQueueTests.DequeueBlocking_StopTest.DequeueBlocking_Stop() in C:\projects\nunit\src\NUnitFramework\tests\Internal\EventQueueTests.cs:line 137
```

**Comment by jnm2** [comment]
> I'll stand back to @jnm2's expertise here though!

Haha, what gave you that impression? Stubbornness, more likely 😜

I've been on the fence about Directory.Build.props, being wary of spooky action at a distance where new csprojs pull in settings you didn't think about. But it's becoming more common and I'm equally happy with it, I think, for what that's worth.

**Comment by jnm2** [comment]
@sharwell The branch has a merge conflict with the other change.

**Comment by sharwell** [comment]
Fixed the merge conflict. I'm slightly surprised GitHub didn't detect the unaltered file contents during the rename and allow it.

**Pull request merged**
