### PR TITLE
Allow Extensions to provide data through an attribute

### PR DESCRIPTION
**Pull request by CharliePoole**
**Ready to Merge**

~~Even though it's not complete, I'd like some review of the initial commit, which should give a much clearer picture of where I am going with this than my non-code explanations!~~

I have added an ExtensionPropertyAttribute, which is applied ot any extension classes that want to include additional information in the ExtensionNode.

I used the new attribute to specify the Format supported by the NUnit2XmlResultWriter class as "nunit2".  As a result, I eliminated a number of factories and simplified the logic of the ResultService. More importantly, the extension assembly containing NUnit2XmlResultWriter class is no longer loaded unless it is actually needed - that is, if someone asks for the "nunit2" format.

### CODE REVIEW

**Comment by CharliePoole** [comment]
This second commit on issue #790 extens the use of attribute-provided data to our two project loader extensions, for nunit and visual studio projects. The ExtensionPropertyAttribute is used to create a FileExtensions property holding a comma-separated list of valid file extensions for the projects supported. This assemblies are only loaded in the case that a path with one of those extensions is presented.

**Comment by rprouse** [comment]
Looks good to me so far.

**Comment by CharliePoole** [comment]
In the third commit, I have done some refactoring and tried to simplify the use of attributes to create extensions and extension points:

* I created a new TypeExtensionPointAttribute, which is now used for most of our extension points. It is applied to the interface that the extensions should use. The Path property is optional and we create a Path for the attribute based on the interface name.

* ExtensionNode now supports multiple values for the same property. This allowed me to use the ExtensionPropertyAttribute multiple times to specify the file extensions that a property loader can handle and to eliminate the use of comma-separated values with a special meaning.

* Various points where a property might not be found are now handled so that an exception is not thrown. In general, I have not issued error messages and stopped the run in the case of properties. The extension will simply not work if the property is needed. This kind of problem would normally be detected in the development of the extension.

I still want to take this another step and avoid loading the V2 driver if it isn't needed. That's what I plan to work on next.

**Comment by CharliePoole** [comment]
The fourth and final commit takes care of the V2 driver.

The logic for the driver, which works with two different frameworks with differing version numbers, was too complex to handle using extension properties. I moved the factory into the main engine assembly and kept the driver itself separate. There is a special-purpose, single-use, extension point that allows the driver to be loaded when needed. Essentially, this uses the extension mechanism to provide delayed loading of an assembly in a standard way.

I think this is ready to merge once CI builds pass.

**Comment by rprouse** [comment]
I mistakenly made comments on a checkin, not on the entire pull request so they don't show up here. Disregard the XMLDoc comment, I thought we generated XMLDocs for engine, but I see we don't. The other comment was fairly minor, so we could merge if you don't want to change it.

**Comment by rprouse** [comment]
Yah, it is a matter of taste and not enough to worry about. Merging...

**Comment by CharliePoole** [comment]
Yes, we only do xmldocs for the api assembly, although I sometimes use the comments anyway and they probably wouldn't hurt here.

**Comment by rprouse** [comment]
I've merged, but comments can always help.

On 21 September 2015 at 14:53, CharliePoole <notifications@github.com>
wrote:

> Yes, we only do xmldocs for the api assembly, although I sometimes use the
> comments anyway and they probably wouldn't hurt here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/pull/816#issuecomment-142074849>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Pull request merged**
