### PR TITLE
Remove NUnit.Compatibility.Path

### LINKED ISSUE #1663: Find way to hide NUnit.Compatability.Path from intellisense
@jcansdale commented on [Wed Jul 13 2016](https://github.com/nunit/dotnet-test-nunit/issues/52)

The .NET Core version of `nunit.framework` contains a public class called `Path`. This shows up in intellisense at the top when you try to auto-complete a reference to `Path`. This can be annoying because `Path` is a commonly used class.

compat

---

@rprouse commented on [Wed Jul 13 2016](https://github.com/nunit/dotnet-test-nunit/issues/52#issuecomment-232357771)

@jcansdale I am pretty sure it is gone in the latest versions on master. It was annoying me to, so I removed it from the compatibility classes in the portable driver because it wasn't really needed. It was left over from when the driver was a PCL.

I just searched the code and can't find it, but I'll leave this open until the next release just in case I'm blind :smile: 

---

@jcansdale commented on [Wed Jul 13 2016](https://github.com/nunit/dotnet-test-nunit/issues/52#issuecomment-232359236)

@rprouse,

This was with 'nunit.framework' v3.4.1 (lousy bug report missing that).

Good to hear you're on top of it. :smile: 

---

@rprouse commented on [Wed Jul 13 2016](https://github.com/nunit/dotnet-test-nunit/issues/52#issuecomment-232359917)

Ah, that is where it was coming from. Most people won't be including the NUnit.Compatibility namespace when using the PCL, but it should probably be internal anyway. We might also be able to drop it when we switch the PCL to .NET Standard. 

I am going to move this to the main NUnit repo. I am pretty sure it belongs there.

### PR DESCRIPTION
**Pull request by FantasticFiasco**
Remove class ``NUnit.Compatibility.Path`` since it was redundant.

At least it looked like that to me. Please correct me if I'm wrong. Maybe the class is used on a branch that hasn't been merged back to master, or it was used once but no longer?

Fixes #1663

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Oh, I see the CI is failing :-) Guess it was used. Don't worry about this PR yet, I'll fix it.

**Comment by FantasticFiasco** [comment]
Ok, seems CI servers are happy.

**Comment by CharliePoole** [comment]
@FantasticFiasco Please use a descriptive title for your PR and put the Fixes #nnnn comment in the description where GitHub will actually notice the connection. I edited both title and description.

**Comment by CharliePoole** [comment]
Looks good. Appararently, we removed all actual usage of this class previously!

**Comment by rprouse** [comment]
Looks good to me too.

**Pull request merged**
