### PR TITLE
use some pattern matching

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by mikkelbu — APPROVED** [review]
LGTM. Thanks for the contribution @SimonCropp :+1

**Comment by mikkelbu** [comment]
I'll rerun the tests when I get back to my personal computer

**Review by jnm2 — APPROVED** [review]

**Comment by jnm2** [comment]
One failure was a timeout that is way too low for CI:

> NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.LargeStringCollection
>Test exceeded Timeout value of 500ms

**Review by stevenaw — APPROVED** [review]
👍 big fan of this sort of thing as it often results in simpler, slightly more performant code. Thanks once again!

**Pull request merged**
