### PR TITLE
Exposed NUnitEqualityComparer ctor and obsoleted Default

### LINKED ISSUE #2591: NUnitEqualityComparer.Default should be replaced with new NUnitEqualityComparer()
In https://github.com/nunit/nunit/pull/2290, we made the constructor internal ~~and introduced a Default static property which returns a new instance every time~~. I failed to notice this when reviewing that PR. 

Edit: Thanks for the correction @mikkelbu. The Default property has been in NUnitEqualityComparer since v2.5.1!

I believe that static properties should return the same instance every time or at least *semantically be able* to return the same instance every time. If the returned instance is immutable, it should be a static property. If it's mutable, it must create a new instance every time and therefore should be a method. Rather than having a static method delegate to the default constructor, I'd prefer re-exposing the default constructor.

I would like to propose the following:

```diff
namespace NUnit.Framework.Constraints
{
    public class NUnitEqualityComparer
    {
+       public NUnitEqualityComparer();

+       [Obsolete("Deprecated. Use the default constructor instead.", error: true)]
        public static NUnitEqualityComparer Default { get; }
    }
}
```

Should we make the obsoletion a warning or error? I prefer error because it helpfully points people to the necessary refactor while flushing out all uses but I could go either way.

### PR DESCRIPTION
**Pull request by jnm2**
Closes #2591

### CODE REVIEW

**Comment by jnm2** [comment]
Good thought. I can take care of that.

**Comment by rprouse** [comment]
Looks good to me too. Just waiting on CI.

**Comment by rprouse** [comment]
Travis failure was just an `apt-get` failure. Restarted.

**Comment by jnm2** [comment]
Docs updated. https://github.com/nunit/docs/wiki/Breaking-Changes/376972f6797a4c76424e16986fed247eb817a296

**Comment by jnm2** [comment]
@rprouse You know, I think there were more breaking changes in 3.7–3.9. Do you mind if I do an API diff and fill out https://github.com/nunit/docs/wiki/Breaking-Changes? I can do a PR against my fork of the wiki before copying it over to the docs wiki.

**Comment by rprouse** [comment]
Sure, go ahead. I would be interested in seeing what you find.

**Pull request merged**
