### PR TITLE
Do not construct object for OneTimeSetUp in InstancePerTestCase lifecycle

### PR DESCRIPTION
**Pull request by mvdfugro**
Test + (hopefully to-the-point) solution for #3843 . May need some extra unit tests?

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3844) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3844) before we can accept your contribution.<br/><br/>:x: mvdfugro [sign now](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3844)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/nunit?pullRequest=3844) it.</sub>

**Comment by mvdfugro** [comment]
Thanks for the quick review! I'm currently a bit swamped but hope to be able to write some additional tests in the next week or so.

**Comment by mvdfugro** [comment]
In the above, the first three commits rearrange the tests to fully test the lifecycle in a single test (rather than testing bits and pieces in various tests).
The fourth adds a test to verify that inheritance works as expected.

The rest of the commits use inheritance to make sure the basic invariants are verified in every test. I'm not sure whether that's acceptable for test within NUnit or whether it is preferred to have duplication to have simpler tests -- I'm happy to just push the first four commits otherwise.

Adding the BaseLifeCycle did surface a bug (this is why the tests are failing -- I've kept a failing test to show the issues):

* The InstancePerTestCase annotation does not seem to be 'inherited' by nested classes. (The original test cases actually didn't test anything as they (confusingly) did not run -- `TestBuilder.MakeFixture(typeof(LifeCycleWithNestedOverridingFixture))` doesn't actually instantiate any nested test classes.)

I also found something I'm confused by but which might be intended behavior:

* The test with the TestFixtureSource annotation calls OneTimeSetUp _twice_. This happens for both InstancePerTestCase & SingleInstance so it is consistent -- I did find it somewhat surprising. Is this intended behavior?



The assembly level tests are a bit out of sync with the main tests (i.e. not every test in `NUnit.TestData.LifeCycleTests` has an friend in `NUnit.TestData.LifeCycleTests.AssemblyLevelFixtureLifeCycleTest`). I'm not entirely sure how useful it is to test all combinations of attributes there?
My suggestion would be to remove those tests (as they are nominally covered in the regular tests), and instead focus on tests that verify the behavior of overrides of `FixtureLifeCycle(LifeCycle.InstancePerTestCase)`. I just realized those are missing entirely so I'll add those in any case.

**Comment by mvdfugro** [comment]
Pushed additional assembly-attribute-tests to verify the overriding behavior. Seems to work as expected! 👍

**Comment by mvdfugro** [comment]
Dug into the wrapping class issue as well, but I'm not entirely sure how it's supposed to work:

- In `NUnitTestFixtureBuilder.BuildFrom`, `fixture.ApplyAttributesToTest(new AttributeProviderWrapper<FixtureLifeCycleAttribute>(typeInfo.Type.GetTypeInfo().Assembly));` is called. This correctly applies attributes on inherited classes but doesn't so do for wrapped classes. The AttributeProviderWrapper could recurse into parent wrappers as well.
  - In the end, this is what sets the `LifeCycle` flag on the fixture, so this seems like a natural choice.
-  `TestExtensions.HasLifeCycle` recurses through `Test.Parent`, but that is only set for _tests_, not for _fixtures_. I can't quite figure out how `TestExtensions.HasLifeCycle` is supposed to work -- it seems to search for the first use of 'InstancePerTestCase' rather than looking for the first defined lifecycle... but that would imply that you could never override from `InstancePerTestCase` back to `SingleInstance`.

**Comment by mvdfugro** [comment]
Rebased onto latest master, and added `Ignore` attributes to the two tests that fail because of #3888. I'll move the comment above to that bug for separate discussion; this now just resolves the original original issue + reorganizes / simplifies the test case setup.

**Review by rprouse — APPROVED** [review]
That is an impressive set of tests, nicely done.

**Comment by mvdfugro** [comment]
Hi @rprouse, is there anything I still need to do for this to get merged?

**Comment by rprouse** [comment]
@mvdfugro I was hoping to get a second review, but I'm happy with the work and the tests you've added so I'll merge. Thanks for your contribution.

**Comment by mvdfugro** [comment]
Thanks!

**Pull request merged**
