### PR TITLE
thoughts on expression based members?

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
any thoughts on this one? before i put any effort into resolving the conflicts

**Comment by manfred-brands** [comment]
I'm happy with expression body syntax for properties.
However to ensure consistency for further developments we need to add this to an .editorconfig file.
And others have to agree to these. Should it be 'suggestions' or enforced as 'error'?

```
# Expression-bodied members
csharp_style_expression_bodied_accessors = when_on_single_line:suggestion
csharp_style_expression_bodied_constructors = false:none
csharp_style_expression_bodied_indexers = when_on_single_line:suggestion
csharp_style_expression_bodied_lambdas = when_on_single_line:suggestion
csharp_style_expression_bodied_local_functions = when_on_single_line:suggestion
csharp_style_expression_bodied_methods = false:none
csharp_style_expression_bodied_operators = when_on_single_line:suggestion
csharp_style_expression_bodied_properties = when_on_single_line:suggestion
```

**Comment by SimonCropp** [comment]
> Should it be 'suggestions' or enforced as 'error'?

my preference is `error` but i am only a tourist

**Comment by jnm2** [comment]
`warning` is by far the best experience all around when combined with:
```xml
    <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
```

- It doesn't prevent you from running and debugging tests while you're knee-deep in code, which is highly annoying when you're focused on the fundamentals and constantly having to reformat your temporary code
- It still prevents the main branch from piling warnings up until the noise to signal ratio trains people to stop seeing them

**Comment by SimonCropp** [comment]
editor config updated

**Comment by SimonCropp** [comment]
bump

**Comment by stevenaw** [comment]
I'm also on board with this, thanks @SimonCropp 
@mikkelbu mind if I ask your quick thoughts on the proposed style enforcement changes above?

> I'm happy with expression body syntax for properties. However to ensure consistency for further developments we need to add this to an .editorconfig file. And others have to agree to these. Should it be 'suggestions' or enforced as 'error'?
> 
> ```
> # Expression-bodied members
> csharp_style_expression_bodied_accessors = when_on_single_line:suggestion
> csharp_style_expression_bodied_constructors = false:none
> csharp_style_expression_bodied_indexers = when_on_single_line:suggestion
> csharp_style_expression_bodied_lambdas = when_on_single_line:suggestion
> csharp_style_expression_bodied_local_functions = when_on_single_line:suggestion
> csharp_style_expression_bodied_methods = false:none
> csharp_style_expression_bodied_operators = when_on_single_line:suggestion
> csharp_style_expression_bodied_properties = when_on_single_line:suggestion
> ```

> `warning` is by far the best experience all around when combined with:
> 
> ```
>     <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
> ```
> 
>     * It doesn't prevent you from running and debugging tests while you're knee-deep in code, which is highly annoying when you're focused on the fundamentals and constantly having to reformat your temporary code
> 
>     * It still prevents the main branch from piling warnings up until the noise to signal ratio trains people to stop seeing them

**Comment by stevenaw** [comment]
@SimonCropp I tried resolving the conflicts in `TypeWrapper` here, they all stem from the removal of `GetTypeInfo()`. Assuming that you + CI are both in agreement with my changes, I think this can be merged. Will be great to get a changeset as large as this finally landed into the codebase.
Thanks once again!

**Review by stevenaw — APPROVED** [review]

**Comment by SimonCropp** [comment]
@stevenaw  yep. i will rebase tonight and let u know

**Comment by SimonCropp** [comment]
done. but probs should be squashed

**Comment by stevenaw** [comment]
Thanks once again @SimonCropp .
LGTM

**Pull request merged**
