### PR TITLE
Add assertion overloads that delay evaluation of the message until needed

### LINKED ISSUE #144: Pass a Func<string> to lazily evaluate an exception message
I find several cases in my tests where I only want to build a message when the Assertion fails.  Consider the following snippet:

// Assert
var comparer = new MyEqualityComparer();
Assert.That(actual, Is.EqualTo(expected).Using(comparer));

I have several cases where I use an IEqualityComparer<T> to simplify multiple Assertion statements into a reusable EqualityComparer.  It's great, until the the verification fails, and I have to manually step through the test comparing properties manually.

To help automate this task, I built a reusable helper class to not only compare two classes but enumerate the differences between their properties.  Then, the differences are rendered to a string, and I can use this string as the failure message in the Assertion.

Ideally, this message would not need to be created unless the verification fails.  However, none of the Assert methods allow for passing a function as a parameter which would lazily evaluate the failure message.  Here's the syntax I'd like to use:

// Assert
var comparer = new MyEqualityComparer();
Func<string> getFailureMessage = () => comparer.WriteDifferencesToString(expected, actual);
Assert.That(actual, Is.EqualTo(expected).Using(comparer), getFailureMessage);

Using this syntax, client test methods could lazily evaluate the failure messages using any valid Function.  I think this would really help users clean up their tests and extend the capabilities of the NUnit framework.

I'm open to discussion on this idea as well as direction on how to help make it a possibility.  Thank you for your consideration.

### PR DESCRIPTION
**Pull request by CharliePoole**
This PR builds on PR #1783 contributed by @pflugs30, which got caught in the big split of framework, engine and console. See some discussion on the original PR as well as here.

Fixes #144

### CODE REVIEW

**Comment by CharliePoole** [comment]
@pflugs30 @rprouse Please review

**Comment by pflugs30** [comment]
Looks good to me. Reviewed on phone and not compiled locally, but assuming that's already been done. Thanks!

**Comment by rprouse** [comment]
Looks good to me too.

**Comment by pflugs30** [comment]
Thanks, @rprouse!

**Pull request merged**
