### PR TITLE
Expand SupportOSPlatform to mean minimum supported version

### LINKED ISSUE #4564: Tests not discovered for .NET Windows-specific TFM without Windows build number
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
  * NUnit 4.0
  * NUnit3TestAdapter 4.5
* Visual Studio edition and full version number (see Help About)
  * 17.9.0 Preview 1.0

After updating to NUnit 4.0, and version 4.5 of the test adapter, tests are no longer recognised for a test project targeting **net6.0-windows**. Changing the target to **net6.0-windows10.0.19041.0** works around the problem.

See the attached repro project: [NUnitRunnerWindows.zip](https://github.com/nunit/nunit3-vs-adapter/files/13477774/NUnitRunnerWindows.zip)

Thanks!

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #4564 

Windows7 => WIndows7, Windows8, Windows10, Windows11
Windows10 => Windows10, Windows11

Added windows only test assembly with MS generated SupportOSPlatform attribute

### CODE REVIEW

**Review by stevenaw — APPROVED** [review]
Thanks for the prompt PR @manfred-brands !
No concerns from me, LGTM.

**Comment by christophwille** [comment]
Could you please publish this somewhere (MyGet, ...) to easily try it?

**Comment by manfred-brands** [comment]
> Could you please publish this somewhere (MyGet, ...) to easily try it?

The nuget package is available from the [build action](https://github.com/nunit/nunit/suites/18583950431/artifacts/1079714040)
Extract it to a local nuget feed (on your own drive). [See](https://learn.microsoft.com/en-us/nuget/hosting-packages/local-feeds)

**Comment by christophwille** [comment]
That doesn't quite cut it - https://github.com/icsharpcode/ILSpy/pull/3132 in addition to local failures, we are also failing on GH actions. I don't want to check in a binary just for testing.

**Comment by OsirisTerje** [comment]
I have pushed the latest up to MyGet at https://www.myget.org/feed/nunit/package/nuget/NUnit/4.1.0-adev.1

**Comment by christophwille** [comment]
Let's find out then how dotnet test fares on GH with the new package https://github.com/icsharpcode/ILSpy/pull/3132/commits/d3de4745048da6a4ae59694625930d02ab51cdb5

**Comment by christophwille** [comment]
No, it doesn't: https://github.com/icsharpcode/ILSpy/actions/runs/7030026378/job/19128743036 (note locally in VS it works a-ok). Is dotnet test behaving differently than VS in this case then? 

```
Run dotnet test --logger "junit;LogFileName=Debug.xml" --results-directory test-results $env:Tests1 $env:Tests2 $env:Tests3
Microsoft (R) Test Execution Command Line Tool Version [17](https://github.com/icsharpcode/ILSpy/actions/runs/7030026378/job/19128743036#step:10:18).8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 3 test files matched the specified pattern.
No test is available in D:\a\ILSpy\ILSpy\ICSharpCode.Decompiler.Tests\bin\Debug\net8.0-windows\win-x64\ICSharpCode.Decompiler.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
No test is available in D:\a\ILSpy\ILSpy\ILSpy.Tests\bin\Debug\net8.0-windows\ILSpy.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
No test is available in D:\a\ILSpy\ILSpy\ILSpy.BamlDecompiler.Tests\bin\Debug\net8.0-windows\win-x64\ILSpy.BamlDecompiler.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Results File: D:\a\ILSpy\ILSpy\test-results\Debug.xml
```

**Comment by OsirisTerje** [comment]
The tests are running, but it fails on creating the report:
image

**Comment by OsirisTerje** [comment]
It should not.  Does it run on command line locally ?

**Comment by christophwille** [comment]
Very, very strange. Locally it works in all those variations:

```
PS D:\GitWorkspace\ILSpy\ILSpy.Tests> dotnet test
PS D:\GitWorkspace\ILSpy\ILSpy.Tests\bin\Debug\net8.0-windows> dotnet test ilspy.tests.dll
PS D:\GitWorkspace\ILSpy\ILSpy.Tests\bin\Debug\net8.0-windows> dotnet test --logger "junit;LogFileName=Debug.xml" --results-directory test-results ilspy.tests.dll
```

all report Passed!  - Failed:     0, Passed:   118, Skipped:     0, Total:   118, Duration: 264 ms - ilspy.tests.dll (net8.0)

**Comment by OsirisTerje** [comment]
Yes, I got the same.  118 tests passing with no issues.  

Interesting enough, if I try to run the tests on the ICSharpCode.Decompiler.Tests, I am rewareded with the Virus Threat kicking off, about some 
image

**Comment by christophwille** [comment]
Test cases come from a submodule (git submodule update --init --recursive), and yes, we know that Antivirus doesn't like some of the code.

**Comment by OsirisTerje** [comment]
You can add "-- NUnit.Verbosity=5"    That give you a little bit more information.  Are you using any .runsettings file?  Also, you can add  "NUnit.DumpXmlTestDiscovery=true" and "NUnit.DumpXmlTestResults=true".  Add them either on the command line after the Verbosity option, or add all of them to a .runsettings file,

**Comment by christophwille** [comment]
No, no .runsettings. Locally adding -- NUnit.Verbosity=5 doesn't really change much in the output at all.

`dotnet test --logger "junit;LogFileName=Debug.xml" --results-directory test-results ilspy.tests.dll -- NUnit.Verbosity=5`

**Comment by christophwille** [comment]
I have added --diag to https://github.com/icsharpcode/ILSpy/pull/3132/commits/9982e1cb55c770e580c87bb5f23fe88a290e9d2f
[dotnettestdiag-Debug.txt](https://github.com/nunit/nunit/files/13499242/dotnettestdiag-Debug.txt)

btw, should we move the discussion to a new issue maybe?

**Pull request merged**
