### PR TITLE
[WIP] Save test results in a format AppVeyor understands

### PR DESCRIPTION
**Pull request by sharwell**
I'm not familiar with cake so this is still an experiment.

💡 Please do not rebase or squash this pull request on merge.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Neither of the CI failures look related to this change. I'm rerunning both...

**Comment by rprouse** [comment]
This looks promising, but only one set of test results is being displayed, https://ci.appveyor.com/project/CharliePoole/nunit/build/3.10.0-ci-05305-pr-2724/tests

You might need to make the test result filename unique for each test run.

**Comment by jnm2** [comment]
I've tried separate names but AppVeyor replaces all tests with the last uploaded file.
https://github.com/Microsoft/vstest/issues/880#issuecomment-341912021

**Comment by jnm2** [comment]
@sharwell What do you think, still interested in figuring this out?

**Pull request closed without merging**
