### PR TITLE
Issue 360

### PR DESCRIPTION
**Pull request by constructor-igor**
Fixed spelling issue (Tes4 --> Test4) and "tab"

### CODE REVIEW

**Comment by rprouse** [comment]
Looks good, thanks for updating.

**Comment by CharliePoole** [comment]
@constructor-igor In future, please stick with a single branch and PR unless there's a serious reason not to do so. For that to work, all you need to do is keep pushing to the same branch. The PR will then be updated with the new commits and all comments will still be in place.

Thanks for getting this fixed. :-)

**Comment by rprouse** [comment]
@constructor-igor, we would like to recognize your contributions in the upcoming release, but do not know your last name. If you would like us to include it, just post it here :smile:

**Comment by CharliePoole** [comment]
He uses Igor Z on google+

**Comment by constructor-igor** [comment]
my full name: Igor Ziselman

**Pull request merged**
