### PR TITLE
Issue 1553

### LINKED ISSUE #1553: Allow ordering tests to be done in multiple properties
On SQL queries, I tend to order by multiple columns and not only one.
I would like NUnit handles this case and allows unit testing not only on one property but on multiple properties.

The general idea is to be able to do the following:

`var list = new List<Tuple<string, string>>`
`{`
`    new Tuple<string, string>("aaaa", "bbbb"),`
`    new Tuple<string, string>("bbbb", "aaaa"),`
`    new Tuple<string, string>("aaaa", "cccc"),`
`    new Tuple<string, string>("cccc", "bbbb")`
`};`
`var ordered = list.OrderBy(p => p.Item1).ThenBy(p => p.Item2);`

`Assert.That(ordered, Is.Ordered.By("Item1").By("Item2"));`
or
`Assert.That(ordered, Is.Ordered.By("Item1").And.By("Item2"));`
or
`Assert.That(ordered, Is.Ordered.By("Item1").ThenBy("Item2"));`

I was looking for this feature on [SO](http://stackoverflow.com/questions/37676739/how-to-check-list-orders-further-properties-with-nunit/) and Charlie Poole sent me here.

Thank you.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #1553 

This is my shot at #1553, based on #1564 by @jnsn.

This version...

 * Uses an enum for direction

 * Generalizes the algorithm into a series of steps, which will always be one step if there is no "By"

 * Adds test cases and reorganizes the tests

Still needed...

 * The Comparer should logically be part of each step, allowing such things as

   ```C#
   Is.Ordered.By("A").Using(myComparer).Then.By("B").Using(myOtherComparer)
   ```

 * This implementation still gives errors at runtime rather than compile time. I realized while working on it that this particular constraint is much more difficult than many others in this regard. I think it's possible, but would probably be better as a separate follow-on issue.

@jnsn Feel free to continue from this or combine it with your version. I don't plan to work further on it for a while.

### CODE REVIEW

**Comment by rprouse** [comment]
@CharliePoole are you planning on getting this in for the release on the weekend?

**Comment by CharliePoole** [comment]
No... it's primarily being worked on by

**Comment by jnsn** [comment]
I'll attempt to pick this up this weekend if I can carve out some time.

**Comment by CharliePoole** [comment]
That's great... when you have time, please add any thoughts you may have. BTW, if you plug in my tests to your implementation, you'll see why I added the `break` statement in that inner loop.

**Comment by CharliePoole** [comment]
It would be desirable to merge this before splitting the repositories per #1598, but not absolutely necessary since it only deals with the framework.

**Comment by CharliePoole** [comment]
Rebased on top of current master.

**Comment by CharliePoole** [comment]
I'm having to repeatedly restart the Apple builds when they time out. It's getting annoying! We may be hanging and causing it, but I don't see how.

**Comment by CharliePoole** [comment]
@rprouse @jnsn I think this is ready to merge now. Error handling is at run time rather than compile time because that's a major bit of work I don't have time for right now.

Basically, the syntax is that you can have one or more groups with `By` or just one group without `By`. The groups are separated explicitly by `Then` or implicitly by a new `By` coming along. Each group can have one `By`, one directional and one `Using`. See the tests for examples. I'll need to do a revision of the documentation page to cover all this.

**Comment by rprouse** [comment]
I will look at this again in the morning when I am not as tired. Meanwhile, @jnsn can you give this a second look?

**Comment by CharliePoole** [comment]
@rprouse I've also been mentioning @jnsn but he seems to have disappeared from our world. :disappointed:

**Pull request merged**
