### PR TITLE
Revert "Proposed solution for Issue #600"

### PR DESCRIPTION
**Pull request by CharliePoole**
Reverts nunit/nunit#606

### CODE REVIEW

**Comment by CharliePoole** [comment]
@rprose I didn't realize you still had #606 marked as do not merge!

**Comment by rprouse** [comment]
Actually, nothing wrong with merging, I just thought we would want to make
more classes internal. We could always do that as an additional pr to keep
it small.

**Comment by CharliePoole** [comment]
What led me to revert was that the CI builds were failing with errors related to the key. Take a look in Appveryor and Travis and we can see what's needed to reapply the change.

**Comment by oznetmaster** [comment]
Is this revert to be merged or not?  I am confused by its status :(

**Comment by CharliePoole** [comment]
I was waiting for the CI builds to pass.

**Pull request merged**
