### PR TITLE
Release 3.10.1

### PR DESCRIPTION
**Pull request by rprouse**
**Do Not Merge** I am just using this as a sanity check. @jnm2 can you review and see if this is what you expect for the hotfix? Diff is to master. Looks correct to me, but I would love a second review. 😄

### CODE REVIEW

**Comment by rprouse** [comment]
I am making the suggested changes to `CHANGES.md` and will start building the release. I will push those to this PR any minute.

**Comment by rprouse** [comment]
Changes are up, starting release. If you see anything, let me know ASAP 😄

**Comment by jnm2** [comment]
Everything I can see looks good.

**Comment by rprouse** [comment]
@jnm2 I think you have access to the draft release at https://github.com/nunit/nunit/releases/tag/untagged-168322091a2f18b29a5a? Can you test the nuget package on an earlier release of VS?

**Comment by jnm2** [comment]
Yes, I can access that.
The only thing I have ready is VS2010 on a VM. 😄 I'll try it.

**Comment by rprouse** [comment]
I didn't think anything prior to VS 2012 update 1 worked with our NuGet packages. I am going to boot another computer that might have an older version...

**Comment by jnm2** [comment]
Oh, you're right.

**Comment by jnm2** [comment]
I'm quite confident given the wording in https://msdn.microsoft.com/library/dd576348.aspx, the simple contents of the props, and testing C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe, that this will just work.

**Comment by rprouse** [comment]
I hope so, I just checked my work machine and it only has 2017 on it too.

**Pull request closed without merging**
