### PR TITLE
Make ConstraintExpression.AnyOf() accept ICollection

### PR DESCRIPTION
**Pull request by ivan-gurin**
Add ConstraintExpression.AnyOf(ICollection) overload as discussed in https://github.com/nunit/nunit/issues/4551

### CODE REVIEW

**Comment by ivan-gurin** [comment]
@dotnet-policy-service agree

**Comment by manfred-brands** [comment]
@ivan-gurin Can you please add a test for the new functionality?

**Comment by ivan-gurin** [comment]
@manfred-brands done

**Review by manfred-brands — APPROVED** [review]
Thanks @ivan-gurin for your contribution.

**Pull request merged**
