### PR TITLE
Add testing for compounded Test Filters

### PR DESCRIPTION
**Pull request by OmicronPersei**
Closes issue #2372 .  Just looking for some feedback on whether or not I've covered enough that should probably be tested?  Any other worth while combinations, or other filters worth considering?

### CODE REVIEW

**Comment by jnm2** [comment]
> Added MultipleFilterTests, may have found a bug.

Looking at this without context, I don't see anything out of the ordinary. What specifically surprised you?

**Comment by OmicronPersei** [comment]
Nothing, that was my first commit, but I since squashed them.  Commit message is misleading, sorry.  I was just looking to see if there are other things I should try to cover in these tests?

**Comment by jnm2** [comment]
Nothing jumps out at me, but I'm deep in other stuff too.

**Comment by OmicronPersei** [comment]
@CharliePoole Any thoughts?  I know you mentioned more testing for this, thought you might have ideas.

**Comment by OmicronPersei** [comment]
I'm ready to merge if someone else would like to review! 👍

**Comment by jnm2** [comment]
If you rebase this on master it'll probably get rid of the test failure that is currently blocking this merge.

**Comment by OmicronPersei** [comment]
My last push was actually a rebase off of master, at least I thought.

**Comment by jnm2** [comment]
You did, but https://github.com/nunit/nunit/pull/2401 ("Fix spurious kill failure") has been merged in since then. 😃

**Pull request merged**
