### PR TITLE
Increase tolerance of StopwatchTests from 20% to 50%

### LINKED ISSUE #865: Intermittent failures of StopWatchTests
These are tests of our substitute StopWatch used in the Portable and Silverlight builds. Occasionally, the expected elapsed times are passed, which is to be expected since it isn't deterministic. We should find a way to test so that this doesn't break the build.

### PR DESCRIPTION
**Pull request by CharliePoole**
It's not a very elegant solution, but it seems to be working for our CI builds. Fixes #865.

### CODE REVIEW

**Comment by rprouse** [comment]
Looks good enough :)

**Comment by CharliePoole** [comment]
Didn't expect to hear from you! :-)

**Comment by rprouse** [comment]
We have wifi, so I might find some time here and there. Spending time with my wife's family is the priority though. All credit in the bank for later :)

**Comment by CharliePoole** [comment]
Whatever you can do is  great. I'm looking for a release either tomorrow
morning, before my company arrives from Germany, or later in the release
after they leave.

**Pull request merged**
