### PR TITLE
Don't use .NET 5, the RC requires a preview version of Visual Studio

### PR DESCRIPTION
**Pull request by rprouse**
If you have the RC of .NET 5 installed but haven't updated Visual Studio to the latest preview the projects won't load because .NET 5 RC1 requires MSBuild 16.8.

### CODE REVIEW

**Comment by rprouse** [comment]
Looks like Appveyor only has .NET 5 preview 6 installed.

**Comment by rprouse** [comment]
@jnm2 you switched the build machines to use .NET 5 preview 6. Do you have an issue with backing this down to 3.1 until the final version of .NET 5 is out?

**Review by jnm2 — DISMISSED** [review]
That sounds best.

**Review by jnm2 — APPROVED** [review]

**Comment by jnm2** [comment]
`net5.0` will need to be removed from the TargetFrameworks element in each project.

**Comment by rprouse** [comment]
@jnm2 I removed the 5.0 targets and I also had to pin the FSharp.Core version because they released a 5.0 beta a couple of weeks ago that doesn't support .NET FX and it was getting pulled in.

**Review by jnm2 — APPROVED** [review]

**Pull request closed without merging**
