### PR TITLE
Nuget Restore

### PR DESCRIPTION
**Pull request by chris-smith-zocdoc**
:warning: This PR is comparing a merge into msbuild-fixes as it contains some of those commits. I'll create a new PR once #767 is merged into master.

Addresses https://github.com/nunit/nunit/issues/125

This removes a single package `Microsoft.Bcl.1.1.10` from the `packages` folder and relies on nuget restore to download it before building the project. 

The four use cases that @CharliePoole mentioned in the issue are all working with this solution.

Should I remove the rest of the packages from git in this branch or another one?

### CODE REVIEW

**Comment by CharliePoole** [comment]
@chris-smith-zocdoc It's certainly possible to merge into a branch other than master, but I think it makes things more complex. Usually, for ease of review, we do one thing at a time...

In this case, you are asking to merge into the msbuild-fixes branch but you have already incorporated your changes in the branch. I think an easier approach is to first review my PR and merge it if it seems ready, then merge your own changes into master. My PR is only waiting for a second committer (after me) to review and merge it. Since you are now a committer, you could do that yourself after reviewing it. You should only do that if it doesn't need changes and you feel comfortable that you understand it but it's relatively simple and so should work.

Once that happens, you should either change this PR to merge into master, or delete it and create a new PR from the same branch. Your PR is a much bigger deal than mine, so I'd like to have both @rprouse  and me review it. We can decide whether to delete more binaries at the same time in the review.

**Comment by chris-smith-zocdoc** [comment]
I never meant to actually merge into your branch, this was just to make the code review easier. I will review your first, I was just unsure how close you were to merging that branch

**Comment by CharliePoole** [comment]
Normally, every PR is reviewed and merged. If we just want a review, but
have more to do with it, we put a **Do not merge** comment at the top and
remove it when we are ready.

**Comment by chris-smith-zocdoc** [comment]
I'll keep that in mind, thanks

**Comment by CharliePoole** [comment]
I'll wait for the new PR to make any detailled comments, so they won't get lost.

**Pull request closed without merging**
