### PR TITLE
"&" IS NOT "&&"

### PR DESCRIPTION
**Pull request by kloun**
Fix eric
(from http://www.viva64.com/ru/b/0420/ )

### CODE REVIEW

**Comment by CharliePoole** [comment]
This looks good to me - it's an obvious error. Since there is no issue, I labeled this as if it were a bug report.

**Comment by kloun** [comment]
please merge this patch as soon as possible

**Comment by CharliePoole** [comment]
It will get merged as soon as a second committer looks at it and finds it OK.

**Comment by ChrisMaddock** [comment]
Looks good to me - thanks @kloun!

I believe this is functionally equivalent, although more efficient, as the second condition won't necessarily be evaluated using a logical AND instead of bitwise. Good spot!

**Comment by ChrisMaddock** [comment]
Added this to the milestone, and re-titled to something that will make more sense in a changelog.

**Comment by CharliePoole** [comment]
@ChrisMaddock It's not an efficiency improvement it's to stop a NullReferenceException from being thrown in the case that actual is null.

**Comment by ChrisMaddock** [comment]
Didn't think that through - did I! 😆 Thanks Charlie - retitled again.

**Pull request merged**
