### PR TITLE
Release 3.6.1

### PR DESCRIPTION
**Pull request by rprouse**
**Do not merge**

I am creating this pull request so I can double check what is going into the 3.6.1 release. I will create a second pull request to pull changes from the hotfix back into master.

### CODE REVIEW

**Comment by rprouse** [comment]
@nunit/framework-team could you give this a quick review to make sure it matches what we plan to release as a hotfix. I have reviewed and it looks good to me.

**Comment by rprouse** [comment]
- [x] The release is built and tested.
- [x] The GitHub release is ready in draft.
- [x] A PR for changes to the website has been opened.
- [x] Release notes in the wiki have been updated.

If nobody sees any issues with this PR for the release, I will finish publishing the release tomorrow morning. My checklist is,

- [ ] Switch GitHub release from draft to publish
- [ ] Upload the NuGet packages
- [ ] Upload the nunit.org website changes
- [ ] Announce the release
- [ ] Create a PR to merge these changes back into master

**Comment by CharliePoole** [comment]
Looks good to me.

**Comment by rprouse** [comment]
Thanks for reviewing. I will go ahead with the release in the morning, assuming it isn't a powder day :)

**Comment by rprouse** [comment]
This release is done so I am closing this PR. I will create a PR to merge the changes back into master when I have time.

**Comment by oznetmaster** [comment]
Are you going to be able to merge the changes back into the master sometime soon?

**Comment by rprouse** [comment]
Yes, I will be merging back asap. I am just back from vacation and catching up.

**Comment by oznetmaster** [comment]
Will this be able to happen this week?

**Comment by rprouse** [comment]
I'm not sure, I have more to catch up on after my vacation than I expected. 

@oznetmaster why the rush? Are you looking to port to your version?

**Comment by oznetmaster** [comment]
Yes.  And my version generated from the master branch only.

**Pull request closed without merging**
