### PR TITLE
Fix: Escaping control chars in custom message #1575

### PR DESCRIPTION
**Pull request by lpszBuffer**
Adds EscapeNullCharacters to MsgUtils to specifically escape only null characters from a string.
Alters TextMessageWriter's WriteMessageLine to utilize new EscapeNullCharacters method instead of EscapeControlCharacters.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Looks good to me.

**Comment by rprouse** [comment]
This looks good and very straight forward. Still, we are a test framework, so I would like to see unit tests in `MsgUtilTests` and at least one in `TextMessageWriterTests` to show that this does fix the issue. :smile:

**Comment by lpszBuffer** [comment]
I added the unit tests, but it seems my attempt to squash my commits did not end well. :(

**Comment by rprouse** [comment]
No need to squash. I'll take a look.

**Comment by rprouse** [comment]
Thanks for the contribution.

**Pull request merged**
