### PR TITLE
Revise approach to locating extensions

### PR DESCRIPTION
**Pull request by CharliePoole**
PR #1613 will take care of issue #1607 as written. This PR aims to make improvements to that fix but it does so by making a number of changes to how NUnit finds extensions. If we can verify it today, it would be a good addition to the 3.4 release but we shouldn't put it in without testing the packages thoroughly.

Changes included:

* Use of `/**/` in a `.addins` file now means 0 or more subdirectories rather than 1 or more. This allows the use of `**/tools` for both nuget v2 and v3.

* The initial directory used for starting the search for addins does not have all its assemblies examined. This eliminates the need for an empty `.addins` file in the directory.

* The search for extensions in the packages directory is now done programmatically, without the need for wildcard entries in the addins file to locate them. Consequently, nunit.nuget.addins has been removed.

I'll go ahead and install this in a project using the NUnit.Console nuget package. I should be able to copy over all the addin tests and run them in that project.

### CODE REVIEW

**Comment by CharliePoole** [comment]
I should add one more feature of this PR that may not be obvious... The older approach using a `.addins` file only works when the engine and the extensions are both installed as nuget packages. In the current approach, the engine can be xcopied or whatever and the nuget extensions will still be found.

**Comment by CharliePoole** [comment]
I created a test app and installed the nunit.console package, which includes all the extensions. I ran tests that exercised all the extensions and everything passed except for my V2 test. I suspect that this has never worked when installed as an extension because the v2 driver is not able to locate the v2 nunit assemblies in it's own directory, when that directory is outside of the appbase.

We could decide to merge this as doing some things better or wait till after the release to spend more time on it. If it's the latter, we should merge the issue-1607 branch and leave this one unmerged.

**Comment by CharliePoole** [comment]
My mistake... all extensions including the V2 driver work quite well now when NUnit.ConsoleRunner and the extensions are installed as nuget packages. I just hadn't gotten the setup of my test project right earlier.

That being the case, I'd like to get this revised fix merged into the 3.4 release. I'll check for any review items first thing in the morning.

**Comment by rprouse** [comment]
This looks good to me, let's go with this one.

**Pull request merged**
