### PR TITLE
WIP: #4761 Experiment1: MultipleAssertException deriving from AssertionException

### PR DESCRIPTION
**Pull request by maettu-this**
This is a first experiment on #4761 to see the impact on `MultipleAssertException` deriving from `AssertionException`.

### CODE REVIEW

**Comment by OsirisTerje** [comment]
You can run these in your own fork. I believe that would be much easier for you.

**Comment by maettu-this** [comment]
Hmm..., don't seem to be able to manually trigger [the workflow in my fork](
https://github.com/maettu-this/nunit/actions/workflows/NUnit.CI.yml). [Manually running a workflow](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow#configuring-a-workflow-to-run-manually) instructions don't help much either. Any clues?

**Comment by OsirisTerje** [comment]
If you go to your Actions tab you should see this:
image

That alone should cause the CI action to run.

If you want to trigger it manually, add the workflow_dispatch trigger to the yaml file.  See https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow

**Comment by maettu-this** [comment]
I already previously did enable the workflows. Tried a bunch of other things with no success. Then, based on [a post](https://stackoverflow.com/a/65389878/8543604), I suceeded by adding `workflow_dispatch:` to `NUnit.CI.yml` which I then had to push onto the forked `main`. Not exactly an ideal solution, especially it also triggered the `NUnit.Myget.Publish.yml` of which I don't know the impacts of. I could manually cancel that.

Summarizing:

- Yes, I could trigger the workflows on the fork.
- No, it is neither obvious nor seems the right way to do it.

Adding `workflow_dispatch:` to the original `NUnit.CI.yml` could be the better solution, but that is even less my turf to decide upon.

**Comment by OsirisTerje** [comment]
When experimenting, which is just awesome that people do, you should NOT push this up to the NUnit repo.  It just creates unnecessary noise, and give us more work to maintain these things.

You should do that in your own sandbox.

If you don't like the way it works with the fork, then it is better to just clone the nunit repo, remove the remote, and add a new remote to your own repo.  
Then you can run as many experiments and build as you like.

**Comment by maettu-this** [comment]
Sure, sorry for that, just wanted to share what issues I have been running into when trying to use the workflows on the fork.

**Comment by OsirisTerje** [comment]
No problem, note that you can also use the [slack channels for discussions](https://nunit.slack.com), or also raise a discussion item here.

**Pull request closed without merging**
