### PR TITLE
[test 🚧] Test triggering the build from a fork

### PR DESCRIPTION
**Pull request by jnm2**

### CODE REVIEW

**Comment by rprouse** [comment]
The only change I see is the Noop comment. Is there more or are you testing if it works?

**Comment by jnm2** [comment]
I'm just experimenting so far.
https://docs.microsoft.com/azure/devops/pipelines/build/triggers#pull-request-validation

image

**Comment by jnm2** [comment]
I wonder if this is somehow filtering out forks:

```yml
trigger:
  branches:
    include: [ '*' ]
    exclude: [ 'refs/tags/*' ]
```

**Comment by jnm2** [comment]
Maybe it has to do with my fork somehow?

**Comment by jnm2** [comment]
@rprouse You'll have to take over because I can't manage repo hooks. Can you try https://developercommunity.visualstudio.com/content/problem/346706/azure-devops-github-trigger-stopped-working.html#reply-355525?

**Comment by jnm2** [comment]
Hey, https://github.com/nunit/nunit/pull/3095 triggered it! Did you do the thing?

**Comment by jnm2** [comment]
@rprouse We're now getting:

```
https://nunit.visualstudio.com/NUnit/_build/results?buildId=1243&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=13d8020a-002d-54e1-9310-5e7cabc7fee7&lineStart=13&lineEnd=13&colStart=30&colEnd=185
```

https://nunit.visualstudio.com/NUnit/_build/results?buildId=1243&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=13d8020a-002d-54e1-9310-5e7cabc7fee7&lineStart=13&lineEnd=13&colStart=30&colEnd=185

**Comment by chrisrpatterson** [comment]
@jnm2 sorry to see you are having issues. I will get someone to take a look.

**Comment by yacaovsnc** [comment]
@jnm2 Sorry for the trouble.  Uploading artifact support is rolling out to all customers, but we found a bug and halted that process.  That bug is being patched and we will start rolling out this feature asap.  This feature should be enabled in your account very soon (with in a week) if we don't encounter other issues.

**Comment by jnm2** [comment]
@chrisrpatterson @yacaovsnc Excellent, thank you very much! The thing to do then is to disable the upload for a week if the CI failure confuses folks?

Also, did you get a chance to read over my question at https://github.com/nunit/nunit/issues/3012#issuecomment-441517922? I'm hoping that [hardcoding](https://github.com/nunit/nunit/blob/c8e1a182f664816271cf12e11c003866a77b8e54/azure-pipelines.yml#L16-L56) the [list](https://github.com/nunit/nunit/blob/c8e1a182f664816271cf12e11c003866a77b8e54/azure-pipelines.yml#L75-L115) of [directories](https://github.com/nunit/nunit/blob/master/azure-pipelines.yml#L125-L165) is only a temporary workaround.

**Comment by yacaovsnc** [comment]
@jnm2 you can skip upload artifacts in fork build with this condition:
`condition: and(succeeded(), ne(variables['system.pullrequest.isfork'], true))`

**Comment by yacaovsnc** [comment]
@jnm2 Uploading artifacts from fork build is enabled now.  Can you please give it a try?  Thanks!

**Comment by jnm2** [comment]
@yacaovsnc Looks like it's working: https://nunit.visualstudio.com/NUnit/_build/results?buildId=1274

Thank you!

**Pull request closed without merging**
