### PR TITLE
Added Zero, NotZero, IsPositive, IsNegative to "classic" library

### LINKED ISSUE #1334: Add Assert.Zero and Assert.NotZero
I have been asked by a number of my users if these two forms of Assert could be added to compliment the addition of the Is.Zero and Is.Not.Zero constraints (#1246 and #1248).

It seems reasonable given that we have Assert.Null and Assert.NotNull.

Easy to do, but does this violate some philosophical issue?

### PR DESCRIPTION
**Pull request by jplebre**
Fixes #1334 

DNMY
How to link files to all projects?
How to show partial classes "inside" main partial class file in VS2015?

### CODE REVIEW

**Comment by CharliePoole** [comment]
General notes and questions about this PR...

1. Always add a link to the issue you are fixing in the description or a comment where GitHub will actually find it and close the issue on merge. (I edited)

2. Don't put the issue in the title - it doesn't do anything there. (I edited)

3. We never came to a clear decision about adding Positive and Negative tests. I'm in favor. However, if we do add them, I prefer `Assert.Positive` and `Assert.Negative` to the forms with "Is" It's more consistent with Zero and is the way we have moved over the years. That is, we went from IsNull to Null, IsTrue to True, etc. @nunit/core-team Comments? 

4. I've never seen the abbreviation DNMY before, but it looks like some things you couldn't figure out...

5. You should add (not link) the files to all projects in the solution. If you can open the CF project (requires VS2008) add them there as well. Somebody else can add them where you are not able. Are you working on Windows or Linux?

6. I would put all four asserts in to the existing file Assert.Conditions.cs. It contains asserts that take no expected value but just assert a condition about an actual argument.

**Comment by rprouse** [comment]
@jplebre sorry I did not reply to your email, I was away all weekend. To start, everything that @CharliePoole said :smile: 

To add the files to the other projects, I find that the easiest way is to add it to one project as you have done, then in each of the other projects, 

1. Click on the project,
2. Click on **Show all Files** in the toolbar at the top of Solution Explorer
3. All files in the directory will appear in the solution, your new file will be there but with a grey icon
4. Right click your new file and click **Include in Project**
5. Repeat for each framework specific project

The solution is laid out this way because up until recently there was no good way to target multiple versions of the .NET Framework from one project. We experimented with Shared projects a couple of years ago, but they did not work with Mono at the time. The new xproj/project.json format is promising, but I don't want to do it until the tooling comes out of preview.

image

**Comment by rprouse** [comment]
@jplebre if you click on the details link above, you will find that many unit tests are failing. It is hard to read until you get used to it, but you need to scroll through the console output until you find test errors,

In **Test45**

```
Errors and Failures
1) Failed : NUnit.Framework.Assertions.AssertPolarityTests.AssertPositiveNumbersFailNegativeAssertion
  Expected: <NUnit.Framework.AssertionException>
  But was:  null
at NUnit.Framework.Assertions.AssertPolarityTests.AssertPositiveNumbersFailNegativeAssertion()
2) Failed : NUnit.Framework.Assertions.AssertPolarityTests.ExpectedFailureMessageExistsForIsNegative
  Expected string length 33 but was 44. Strings differ at index 12.
  Expected: "  Expected: 0\r\n  But was:  1234\r\n"
  But was:  "  Expected: greater than 0\r\n  But was:  -1\r\n"
  -----------------------^
at NUnit.Framework.Assertions.AssertPolarityTests.ExpectedFailureMessageExistsForIsNegative()
3) Failed : NUnit.Framework.Assertions.AssertPolarityTests.ExpectedFailureMessageExistsForIsPositive
  Expected string length 33 but was 44. Strings differ at index 12.
  Expected: "  Expected: 0\r\n  But was:  1234\r\n"
  But was:  "  Expected: greater than 0\r\n  But was:  -1\r\n"
  -----------------------^
at NUnit.Framework.Assertions.AssertPolarityTests.ExpectedFailureMessageExistsForIsPositive()
4) Failed : NUnit.Framework.Assertions.AssertPolarityTests.IsNegativeWithMessageOverloadPasses
  Message
  Expected: greater than 0
  But was:  -1
at NUnit.Framework.Assertions.AssertPolarityTests.IsNegativeWithMessageOverloadPasses()
5) Failed : NUnit.Framework.Assertions.AssertPolarityTests.IsPositiveWithMessageOverload
  Expected: <NUnit.Framework.AssertionException> and property Message containing "MESSAGE"
  But was:  no exception thrown
at NUnit.Framework.Assertions.AssertPolarityTests.IsPositiveWithMessageOverload()
6) Failed : NUnit.Framework.Assertions.AssertPolarityTests.NegativeNumbersPassNegativeAssertion
  Expected: greater than 0
  But was:  -1
at NUnit.Framework.Assertions.AssertPolarityTests.NegativeNumbersPassNegativeAssertion()
```

**Comment by jplebre** [comment]
Hey guys, thanks for the comments!
@CharliePoole Thanks for fixing the title and linking the issue. 

DNMY = Do Not Merge Yet :) Yes, wasn't sure how to do the project file linking :)

I'll move the assertions to `Assert.Conditions.cs` as recommended and will rename the conditions to `Positive` and `Negative`

I know the PR is in early stage, but wanted to check I was doing the right thing, thanks @rprouse for the help

Saw the failing tests but things are a bit manic here at work today, hoping I can have a look at it later.

**Comment by CharliePoole** [comment]
No problem, we often do a PR before the work is finished and Mark it do not merge. Post a comment when it's ready for a new review.

**Comment by CharliePoole** [comment]
Looks good to me. Once it passes, we should add it to CF as well and squash out the addition and subsequent removal of Assert files.

**Comment by jplebre** [comment]
About the cf don't actually have vs2008 on my rig

**Comment by CharliePoole** [comment]
Right... but somebody else can do it. I'm just waiting for a second review from an @nunit/core-team member.

**Comment by rprouse** [comment]
Looks good, thanks for the contribution.

**Pull request merged**
