### PR TITLE
Issue 750

### PR DESCRIPTION
**Pull request by CharliePoole**
…Remove all knowledge of Explicit from the filters. Impacts #750.

The first commit establishes an Explicit ResultState, in addition to the Explicit RunState we already have. Filters no longer check for RunState.Explicit. Rather, they expose a new entry point IsExplicitMatch, which is intended to be used at execution time.

While this fix is limited to Explicit tests, it's significant because it explicitly postpones the decision on which child tests to run until run-time. Previously, decisions were made at load-time, except for the special knowledge embedded in the filter, which made explicit tests simply disappear. Consequently, I'd like to get the object design right.

Currently, the knowledge that some tests are explicit lives in two places: CompositeWorkItem and the SkipResult. I think that CompositeWorkItem, which handles Explicit fixtures, is pretty clean. However, to handle Explicit test cases, SImpleWorkItem had to be given a reference to the filter. It passes that filter through to the static CommandBuilder, which decides whether to create a SkipResult or run the test as normal. I'm not 100% satisfied with this and would like input.

All that said, it's cool that the console summary report lines now balance correctly for the first time since I invented Explicit!

### CODE REVIEW

**Comment by CharliePoole** [comment]
@nunit/core-team This needs a code review as well as some input on the next steps to take.

**Comment by rprouse** [comment]
@CharliePoole, I've finally managed to get through this one. I like the approach. I see your concern with passing the filter through the command builder, but isn't that necessary since by definition the decision to run these tests comes through the filters? 

Ideally I would pull this branch down and step through it, but unfortunately, I don't have time right now. Baring that, I am fine with this approach.

**Comment by CharliePoole** [comment]
@rprouse Thanks for the feedback. Maybe I'm just being too anal about my object-orientation. I'll take a final look at the code before I merge it.

**Comment by CharliePoole** [comment]
I did a small refactoring but generally left it alone. The execution of CompositeWorkItems will probably need to be re-addressed in the future, but it's fine for now.

**Pull request merged**
