### PR TITLE
Change default test case name pattern and add console option

### LINKED ISSUE #1549: Changing default behavior for generating test case names
Hello,

Last week I have created issue: https://github.com/nunit/nunit/issues/1537#issuecomment-222730218
It is bigger issue for us, since we have more than ten thousand test cases spread across different visual studio projects. It would be easier for us to actually change the code of NUnit to simply not trim the test case name.
Could this feature be considered in next release?
OR
Can you please point out, which file we will need to change inside the NUnit source code, so that we would "hard code" the maximum value for test case arguments ourselves?

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #1549

### CODE REVIEW

**Comment by CharliePoole** [comment]
Hey @nunit/core-team ! This needs a review to merge it. :-)

**Comment by rprouse** [comment]
Looks good, but do we need an issue in the adapter to set the pattern? Do you need to do the same in the GUI?

**Comment by CharliePoole** [comment]
There's already PR #189 out for review on the V3 adapter.

I don't think the gui will need to do anything but use the default. IMO, any GUI should take  what we give it and reformat it for display. :-)

**Comment by oznetmaster** [comment]
This PR does not update the CommandLineTests in the nunitlitetests project.

**Comment by CharliePoole** [comment]
It wasn't intended to affect nunitlite, so shouldn't have been in command-line options but in console options. Would you create an issue?

**Comment by oznetmaster** [comment]
Why wouldn't it affect nunitlite?  The option is just as useful there as anywhere else.

**Comment by oznetmaster** [comment]
I am already using it in fact.

**Comment by CharliePoole** [comment]
You're right I was thinking of something else. If you feel like putting in a PR with the tests we can merge either before or after the release.

**Comment by oznetmaster** [comment]
The last time this happened, it had been noted that the proper solution might be to put commandlinetests into the common tests.  I thought that was a PR already?

**Comment by CharliePoole** [comment]
Since we're planning on separating the framework and engine+console into different repo, we will need to either eliminate common code or find another approach to it.

**Comment by oznetmaster** [comment]
The problem with that is the fact that nunitlite and console share a lot of common code.  Having to maintain two versions of the same source file is a real pain :(

**Comment by oznetmaster** [comment]
They currently share 14 source files, plus the tests for those classes

**Comment by CharliePoole** [comment]
Yes, we will have to deal with that. See #1589.

**Comment by rprouse** [comment]
@oznetmaster, I agree that it is a pain. There are actually 3 sets of many of these files now with the new .NET Core runner, but I think we need to initially accept the duplication as we separate the runners and the framework into their own repositories. We really want to decouple them and get them on their own release cycles. Once we do that, we can start figuring out ways to reduce the duplication, possibly through a new shared dll?

**Pull request merged**
