### PR TITLE
Lock-free CountdownEvent and lazy ManualResetEventSlim polyfills

### PR DESCRIPTION
**Pull request by jnm2**
Maybe this will help us achieve performance parity for our net35 tests?

### CODE REVIEW

**Comment by jnm2** [comment]
Thrilling. [VSTS's failure](https://github.com/nunit/nunit/blob/09bdce775b46fef62b01c16024c873465830c67a/src/NUnitFramework/tests/Internal/EventQueueTests.cs#L195) is a 30ms timeout. This is the first time this error has happened as far as I can tell.
Going to poke it and see what happens.

**Comment by jnm2** [comment]
This time VSTS is the only one failing again, but it's a new one: `DequeueBlocking_StopTest.DequeueBlocking_Stop`. At face value this seems to be degrading performance.

**Comment by jnm2** [comment]
Actually, the first error is not a new error. It's happening at https://github.com/nunit/nunit/pull/2863#issuecomment-389688796.

**Comment by jnm2** [comment]
@rprouse Would you be interested in this in principle, or meh?

**Comment by rprouse** [comment]
@jnm2 I would be interested, but don't we need more to utilize these new classes in .NET 2.0/3.5?

**Comment by jnm2** [comment]
@rprouse Nope, this is self-contained. I removed overloads that took CancellationToken, for instance.

**Comment by jnm2** [comment]
Was playing around today and have an idea that might fix our hangs. We should not be replacing `Thread.Yield` with `Thread.Sleep(0)` since Sleep(0) often does not yield and allow other threads to get work done. `Thread.Sleep(1)` seems like the best replacement available.

http://joeduffyblog.com/2006/08/22/priorityinduced-starvation-why-sleep1-is-better-than-sleep0-and-the-windows-balance-set-manager/

Going to open a separate PR though, then base this on that.

**Comment by CharliePoole** [comment]
I agree and also have a vague memory of our having decided this some time in the past.

**Comment by jnm2** [comment]
PR: #3019

**Comment by jnm2** [comment]
@oznetmaster Yes, in `EventPump`. See https://github.com/nunit/nunit/pull/3019#issuecomment-421201479. There was already a Sleep(0) in SpinWait at the time.

**Comment by oznetmaster** [comment]
@jnm2 that was the article I quoted three years ago to get all the sleep(0) changed to sleep(1).

The reasoning has not changed, as far as I know.

**Comment by jnm2** [comment]
@oznetmaster Sadly, it's evidently not the cause of the hang. (https://github.com/nunit/nunit/pull/3019#issuecomment-421205698) Gotta start from scratch. Any ideas?

**Comment by jnm2** [comment]
What do you think, should I rebase this and get it in or close?

**Comment by jnm2** [comment]
I don't think net35 is worth investing this amount of code.

**Pull request closed without merging**
