### PR TITLE
Removed the dependency on System.Web.dll

### PR DESCRIPTION
**Pull request by rprouse**
**Do not merge**

I am pushing this pull request for discussion, not merging. Our dependency on System.Web.dll is a problem on all platforms other than Windows. The only reason we take this dependency is for the ICallbackHandler interface and other than in tests we only use the one method.

This PR refactors out that dependency, but doesn't work because it ends up loading the engine into the test's AppDomain, so it fails if the engine is not in the same directory as the test assembly.

I am putting this up for discussion to see what ideas people have to get this or something like it working. Would it be okay to load the engine into the test domain? (I think no.) Is there another interface we could implement that would work just as well? Is there another way to break our dependency on ICallbackHandler? Is there a delegate in a common framework assembly we could use instead?

### CODE REVIEW

**Comment by CharliePoole** [comment]
Can you enlarge on why the use of the interface is a problem? We define it for those framework builds where there is no System.Web.dll and it's available on all plaforms where we run the engine.

If it's actually a problem, we could replace it with a custom interface, provided we created a common assembly referenced by boh the framework and the engine but that's a level of complexity I'd prefer to avoid if possible. I don't think it can be done with a delegate at all.

**Comment by OsirisTerje** [comment]
I am pretty sure we need to remove dependencies on System.Web to support DNX Core.

**Comment by rprouse** [comment]
Our dependency on System.Web means that we cannot run the engine on DNX Core, Android, iOS, Windows 8/8.1/10 runtime, Windows phone, etc. There are other issues, but this is the major stumbling block.

**Comment by CharliePoole** [comment]
So, the reasoning for doing this now is that (1) we want to run the engine on some of those platforms and (2) we prefer not to change the interfaces after the 3.0 release. Is that it?

I see merit in the argument, but I'm not sure if this is the time to make the change. I'm also a bit worried that we'll end up thrashing a bit - making further changes to accomplish the same thing.

My thoughts...

The only thing we use out of System.Web.dll is the ICallbackEventHandler interface. It's used by both the framework and the engine and allows us to report test progress.

In the case of the engine, it is only used by the NUnit3 driver, which happens to be built-in at the moment but could be an addin in the future. In the case of the framework, it's used only by the remoting layer.

An engine driver wraps together two different things:
1. What info needs to be communicated to and from the framework. For example, the progress reports are communicated as Xml strings in a particular format.
2. How that info is transmitted. In the case of the existing NUnit3 driver, this is via remoting.

We only use ICallbackEventHandler in the case of the engine communicating to the framework via remoting. So I think we need to consider whether that's what we will be doing when we use the engine in those platforms that don't support ICallbackEventHandler. If we will use remoting, then it's a problem we should resolve, otherwise there is no issue.

I think it has been clear for some time that we will eventually need to encapsulate the two functions of the driver separately, so that the engine to framework link looks more like this:
                  engine /==/ driver /==/ channel /==/ framework
I was thinking this should be done in the 3.2 (or later) timeframe, when we implement use of a communication channel in place of remoting.

Currently, we build for three framework platforms that don't support ICallbackEventHandler: Portable, Silverlight and Compact Framework. In those builds, we define our own version of the interface. This makes the builds build but we have not exercised the approach because we never call  those framework builds via remoting. I suspect it wouldn't work, but maybe we should try the experiment.

I'd like to figure out where we want to go with this in the future and only make changes right now that we are convinced take us in the right direction and will not need to be reversed.

@rprouse It would help if you could lay out in words how you are proposing to replace the interface. I know it's in the code, but I think some higher-level discussion will help here. We may want to think about what other options there are.

**Comment by CharliePoole** [comment]
Setting aside the broader issues for the moment, here's an idea on replacing ICallbackEventHandler...

My understanding is that remoting of event delegates requires that the two communicating programs reference a common assembly. The failures seem to show that as well. Usually, the same is true with interfaces but one way around this may be to load the interface Type from the framework assembly, for which the driver already has a reference. This may be worth an experiment.

**Comment by rprouse** [comment]
I am going to close this PR. At some point, we need to figure out a way to test across process boundaries for platforms that don't support remoting or System.Web, but it isn't going to happen with the direction of this PR.

**Pull request closed without merging**
