### PR TITLE
Fix Issue #1829

### PR DESCRIPTION
**Pull request by oznetmaster**

### CODE REVIEW

**Comment by oznetmaster** [comment]
AppVeyor screwed up once again.  "No project found".  I cannot restart that ci run :(

**Comment by CharliePoole** [comment]
Final code looks good but the history is messed up with an initial change then a commit to revert it and another to revert the revert. Can you clean it up before merging please?

**Comment by oznetmaster** [comment]
No idea how to do that.

**Comment by ChrisMaddock** [comment]
GitHub has a new "Squash & Merge" button - as a git novice, I find that much simpler.

LGTM - have merged. 👍

**Pull request merged**
