### PR TITLE
WIP: Wrong date format in Ignored TestFixtures

### LINKED ISSUE #2339: Wrong date format in Ignored TestFixtures
@alexamz commented on [Mon Jul 31 2017](https://github.com/nunit/nunit-console/issues/274)

Hi all,

First of all, many thanks to all the contributors to this great and useful project!

We have problems with the start-time and end-time dates in Ignored TestFixtures.
We are using the last version of the NUnit console, the 3.7.0.

This is an example of a test-case header in the xml generated by NUnit Console with a wrong formatted date:

>     <test-case id="0-1071" name="AfterStart_AClientMayConnect" fullname="Port.TCP.UnitTests.TcpServerFactoryTests.AfterStart_AClientMayConnect" methodname="AfterStart_AClientMayConnect" classname="Port.TCP.UnitTests.TcpServerFactoryTests" runstate="Runnable" seed="604943940" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">

On this example we can see that start-time and end-time dates have a wrong date  value "0001-01-01 00:00:00Z ". I would expect to have the date of the execution even if they are skipped. Moreover, if you try to publish these dates to TFS API it will fail because of the date value.

This issue is very easy to reproduce , just adding a [Ignore("some ignore reasons")] on a [TextFixture]. And running Nunit Console to generate the xml result output.

Many thanks!

Have a nice day

---

@ChrisMaddock commented on [Mon Jul 31 2017](https://github.com/nunit/nunit-console/issues/274#issuecomment-319094815)

The code for this lives in the NUnit Framework. I'll move this issue over, and comment further over there. 🙂

### PR DESCRIPTION
**Pull request by Poimen**
Fixes #2339

### CODE REVIEW

**Comment by rprouse** [comment]
Tests are failing,

```
2021-01-06T20:34:56.0486638Z 1) Warning : NUnit.Framework.Assertions.CollectionAssertTest.PerformanceTests(System.Collections.Generic.List`1[System.String])
2021-01-06T20:34:56.0487598Z Elapsed time of 170ms exceeds maximum of 100ms
2021-01-06T20:34:56.0488806Z    at NUnit.Framework.Assertions.CollectionAssertTest.PerformanceTests(IEnumerable values) in D:\a\1\s\src\NUnitFramework\tests\Assertions\CollectionAssertTest.cs:line 185
2021-01-06T20:34:56.0490176Z 
2021-01-06T20:34:56.0490814Z 2) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents
2021-01-06T20:34:56.0491548Z   Expected: 21
2021-01-06T20:34:56.0492106Z   But was:  22
2021-01-06T20:34:56.0493173Z    at NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents() in D:\a\1\s\src\NUnitFramework\tests\Api\TestAssemblyRunnerTests.cs:line 294
2021-01-06T20:34:56.0493903Z 
2021-01-06T20:34:56.0494762Z 3) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents
2021-01-06T20:34:56.0495892Z   Expected: 27
2021-01-06T20:34:56.0496507Z   But was:  24
2021-01-06T20:34:56.0499196Z    at NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents() in D:\a\1\s\src\NUnitFramework\tests\Api\TestAssemblyRunnerTests.cs:line 411
2021-01-06T20:34:56.0500799Z 
```

**Comment by Poimen** [comment]
Yeah, sorry about that - I went and ran the tests locally on the incorrect branch so it looked fine :man_facepalming: 

Some of these count tests are a little strange that they are failing...trying to wrap my head around how it is detecting more suites have been run...

**Comment by rprouse** [comment]
@Poimen I've taken your branch and fixed the unit tests. I can't push to your branch, so I opened a new PR. Because of that, I am closing this one. You will still get contributor credit for the commits you made. I did not change those.

See #3741

**Comment by Poimen** [comment]
@rprouse Thanks for this. Sorry, I had thought I clicked that button...life has gotten away from me. Thanks for taking this over.

**Pull request closed without merging**
