### PR TITLE
Support multiple TestOf attributes per test

### LINKED ISSUE #999: Support multiple TestOf attributes per test
Support multiple TestOn attributes per test

https://github.com/nunit/nunit/wiki/TestOf-Attribute

Note: you can currently only have one TestOf attribute per fixture or test.

### PR DESCRIPTION
**Pull request by sunithapatel**
Closes #999

### CODE REVIEW

**Comment by jnm2** [comment]
@sunithapatel One other thing with PRs: you should edit the top PR comment (not the title) to say "Closes #999" or "Fixes #999" (if it's a bugfix). That way GitHub specially links the PR to the issue and autocloses when the PR is merged. https://help.github.com/articles/closing-issues-using-keywords/

**Comment by sunithapatel** [comment]
I changed the title according to what you suggested. Thank you so much!

**Comment by jnm2** [comment]
@sunithapatel
 
> I changed the title according to what you suggested. Thank you so much!

Sorry, it only works in the top comment, *not* the title.

**Comment by sunithapatel** [comment]
@ChrisMaddock  Thank you so much! So exciting! :)
@jnm2 oops, my bad, now I really read what you said. Hopefully I did it right this time!

**Comment by jnm2** [comment]
@sunithapatel Perfect, thank you! 🎉

**Comment by mikkelbu** [comment]
Kicking Travis again 😞

**Pull request merged**
