### PR TITLE
Add ability to run async tests natively

### LINKED ISSUE #3634: Async tests are not working on Blazor WASM
Hello
This simple async test is not working under blazor wasm runtime.

```
public class Tests {
    [Test]
    public async Task Test1() {
        await Task.Delay(100);
        Assert.Pass();
    }
}
```

**Expected result:**
Test passes.

**Actual result:**
```
Errors, Failures and Warnings

1) Error : BlazorNunit.Pages.Index+Tests.Test1
System.Threading.SynchronizationLockException : Cannot wait on monitors on this runtime.
  at (wrapper managed-to-native) System.Threading.Monitor.Monitor_wait(object,int)
  at System.Threading.Monitor.ObjWait (System.Boolean exitContext, System.Int32 millisecondsTimeout, System.Object obj) <0x31502c8 + 0x00046> in <filename unknown>:0 
  at System.Threading.Monitor.Wait (System.Object obj, System.Int32 millisecondsTimeout, System.Boolean exitContext) <0x3150168 + 0x00022> in <filename unknown>:0 
  at System.Threading.Monitor.Wait (System.Object obj, System.Int32 millisecondsTimeout) <0x31500a0 + 0x0000a> in <filename unknown>:0 
  at System.Threading.ManualResetEventSlim.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) <0x314d828 + 0x001be> in <filename unknown>:0 
  at System.Threading.Tasks.Task.SpinThenBlockingWait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) <0x314c2d8 + 0x00072> in <filename unknown>:0 
  at System.Threading.Tasks.Task.InternalWait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) <0x314bca8 + 0x000ca> in <filename unknown>:0 
  at NUnit.Framework.Internal.TaskAwaitAdapter+GenericAdapter`1[T].BlockUntilCompleted () [0x00000] in C:\projects\nunit\src\NUnitFramework\framework\Internal\TaskAwaitAdapter.cs:95 
  at NUnit.Framework.Internal.MessagePumpStrategy+NoMessagePumpStrategy.WaitForCompletion (NUnit.Framework.Internal.AwaitAdapter awaiter) [0x00001] in C:\projects\nunit\src\NUnitFramework\framework\Internal\MessagePumpStrategy.cs:61 
  at NUnit.Framework.Internal.AsyncToSyncAdapter.Await (System.Func`1[TResult] invoke) [0x00034] in C:\projects\nunit\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:57 
  at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod (NUnit.Framework.Internal.TestExecutionContext context) [0x0002f] in C:\projects\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:81 
  at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute (NUnit.Framework.Internal.TestExecutionContext context) [0x00001] in C:\projects\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:64 
  at NUnit.Framework.Internal.Execution.SimpleWorkItem+<>c__DisplayClass4_0.<PerformWork>b__0 () [0x00000] in C:\projects\nunit\src\NUnitFramework\framework\Internal\Execution\SimpleWorkItem.cs:77 
  at NUnit.Framework.Internal.ContextUtils+<>c__DisplayClass1_0`1[T].<DoIsolated>b__0 (System.Object _) [0x00000] in C:\projects\nunit\src\NUnitFramework\framework\Internal\ContextUtils.cs:40 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x2930b48 + 0x00100> in <filename unknown>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x292dd28 + 0x00010> in <filename unknown>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x3135088 + 0x00050> in <filename unknown>:0 
  at NUnit.Framework.Internal.ContextUtils.DoIsolated (System.Threading.ContextCallback callback, System.Object state) [0x00025] in C:\projects\nunit\src\NUnitFramework\framework\Internal\ContextUtils.cs:55 
  at NUnit.Framework.Internal.ContextUtils.DoIsolated[T] (System.Func`1[TResult] func) [0x0001a] in C:\projects\nunit\src\NUnitFramework\framework\Internal\ContextUtils.cs:40 
  at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork () [0x0001b] in C:\projects\nunit\src\NUnitFramework\framework\Internal\Execution\SimpleWorkItem.cs:77 
```

Test project: [BlazorNunit.zip](https://github.com/nunit/nunit/files/5238060/BlazorNunit.zip)
```
var runner = new NUnitTestAssemblyRunner(new DefaultTestAssemblyBuilder());

var settings = new Dictionary<string, object>() {
    // https://github.com/nunit/nunit/issues/2922
    [FrameworkPackageSettings.NumberOfTestWorkers] = 0,
    [FrameworkPackageSettings.SynchronousEvents] = true,
    [FrameworkPackageSettings.RunOnMainThread] = true
};

runner.Load(typeof(Tests).Assembly, settings);
var res = runner.Run(this, this);
```

Is there any workaround to get this working?

### PR DESCRIPTION
**Pull request by Temtaime**
Fixes #3634
@rprouse

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3640) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3640) before we can accept your contribution.<br/><br/>:x: Temtaime [sign now](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3640)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/nunit?pullRequest=3640) it.</sub>

**Comment by Temtaime** [comment]
Seems that we should duplicate many Command methods in order to make them async-capable. 
Or drop 3.5 net support.
Any thoughts?

**Comment by rprouse** [comment]
I'm on vacation for a week with only a phone. If I don't get back to you next week, please nag me 😉

**Comment by Temtaime** [comment]
@rprouse ping 😊

**Comment by rprouse** [comment]
Have I been back from vacation that long! 😮 

Thanks for nagging me, it took me awhile to get caught up at work but I'm looking at this now. First thing, we'll need to look into the build failures...

**Comment by rprouse** [comment]
Of course the build failures are .NET 3.5 which we unfortunately won't be dropping support for. We tend to be very conservative when dropping support for older versions of frameworks and try to maintain support as long as Microsoft does. For .NET 3.5, that is until 2028!

In order to accept this, it will need to support .NET 3.5 and ideally, it will not change any of our public API which various test runners rely on. You've picked a very difficult and thorny issue for your first contribution! I like what you are attempting to do, but because we are such a widely used framework we need to be very careful when making changes like this.

**Comment by rprouse** [comment]
I'm having trouble thinking of ways we can do this with the constraints we have. @jnm2 you often have good ideas for stuff like this, any thoughts?

**Comment by Temtaime** [comment]
@jnm2 any news ?

**Comment by Temtaime** [comment]
@rprouse @jnm2 
Just want to ping because it seems that this year is slipping away, and our plans are still vague.

In any way happy holidays 😊👀

**Comment by rprouse** [comment]
@Temtaime sorry, but I am not prepared to make a decision on this with a release coming out very soon. Once I get the release out, I'd like to circle back to this discussion and see if we can make a plan to get this working within the constraints that we have. I'm not willing to drop support for .NET 3.5 yet, so we'll need to think about alternatives.

As I said, you picked a very thorny issue 😉

**Comment by rprouse** [comment]
@Temtaime we are discussing dropping .NET 3.5 support for the next release. If we make that decision, we'll likely move forward with this. I'll keep you posted.

**Comment by rprouse** [comment]
@Temtaime PR #3760 removes the .NET 3.5 and 4.0 targets. Once that is merged, I will take a closer look at your changes and see how it fits with our vision.

**Comment by teroneko** [comment]
> I will take a closer look at your changes and see how it fits with our vision.

Any progress towards this? 🙂

**Comment by andersson09** [comment]
Is there an update for this? 

Thanks

**Comment by rprouse** [comment]
I've assigned myself and will look at it as soon as I can.

**Comment by rprouse** [comment]
I've pulled this branch and merged latest from master. I am getting dozens of async warnings compiling, so I think it needs a lot more work and a thorough walkthrough. I've pushed the branch to https://github.com/nunit/nunit/tree/issue/3634 to continue from there, so I am going to close this PR.

**Pull request closed without merging**
