### PR TITLE
Make ConstraintUtils static

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Adds the missing static keyword @jnm2 spotted.

### CODE REVIEW

**Comment by jnm2** [comment]
Ooh can we make it `Utils` too? I know we have a `Util` but it's outnumbered by plural forms in our various projects.

**Comment by ChrisMaddock** [comment]
We can, but I'll need to pull it down for that - I did this on the web UI. Will get back to it. 😄

**Comment by jnm2** [comment]
Can I do it? Easy where I'm at.

**Comment by jnm2** [comment]
Wondered why you were so fast! :D

**Comment by jnm2** [comment]
I went ahead and did it so see how well VS Code refactors. Faster than opening full VS. You can drop the commit if you don't want to rename, but I figured I may as well not waste it.

**Comment by ChrisMaddock** [comment]
That's a great help - thanks! 😄

**Pull request merged**
