### PR TITLE
Fix for #4255, InternalTrace Initialize crash

### PR DESCRIPTION
**Pull request by OsirisTerje**
See #4255

### CODE REVIEW

**Review by CharliePoole — COMMENTED** [review]
This seems to work for your particular use case in the adapter but changes the nature of the check previously made from ensuring that Initialization is only done once to ensuring that initialization is only done once with a level > `Off`.

I think the original intent (don't initialize twice) is what should be done but that the code error causing the exception should be removed. Possibly, the `TraceWriter` should not be initialized at all in this method, but that would require more work.

**Comment by CharliePoole** [comment]
It seems to me that any code (whether the adapter or the engine) that calls `InitializeTrace` more than once is in error. While the exception should be fixed, it should not, in my view, keep us from figuring out why that call is made twice and fixing it.

**Comment by OsirisTerje** [comment]
As mentioned for the issue, the adapter is actually calling the assembly twice in its own testing.  You can check this by running the red tests in the adapter, branch Fixtmppath. 

I can't see that the change really "changes the nature" of this.  If the method is called twice, the else clause simply ignores the call, just as it did before.

**Comment by CharliePoole** [comment]
@OsirisTerje I can see your point. The change you made is very small, I agree, but it's a small change in the semantics of the check being made. If I were re-doing this, I think I'd just throw an exception on the second initialization.

**Review by rprouse — APPROVED** [review]

**Pull request merged**
