### PR TITLE
Drop netstandard1.4 and stop testing on end-of-life versions of .NET Core

### PR DESCRIPTION
**Pull request by jnm2**
Related to https://github.com/nunit/nunit/issues/3320.

The.NET Standard 1.4 build is gone and the .NET Standard 2.0 build is no longer tested on .NET Core 2.0 which is out of support. Instead, it is tested on .NET Core 2.1, 2.2, *and* 3.0.

### CODE REVIEW

**Comment by jnm2** [comment]
@rprouse Did you remove the Travis validation build, or is Travis maybe not responding to webhooks right now? I started getting only four checks in the last few updates to this PR, but I can start builds manually.

**Comment by jnm2** [comment]
I actually cannot figure out how to get Ubuntu on Travis to work without a large amount of further effort.

> ```
> Tool 'cake.tool' (version '0.35.0') was successfully installed.
> dotnet-cake: command not found
> ```

@rprouse Can you confirm whether we are dropping Travis? If so, I may as well delete the yaml because it won't run in its current state in this branch.

**Comment by CharliePoole** [comment]
I use the cake tool for my Travis builds of TestCentric. My script allows for the fact that the tool is installed in a hidden subdirectory of your home directory.

See... https://github.com/TestCentric/testcentric-gui/blob/master/.travis.yml#L18

**Comment by jnm2** [comment]
That's the same line I started with, I think. Can you see a difference, excluding the latest commit?

**Comment by CharliePoole** [comment]
Looks the same to me except for versions.

**Comment by rprouse** [comment]
I removed Travis as a required build, but I don't think I removed it completely. I'm not sure why it isn't showing up. I'd be fine with dropping it though since we are building Linux on Azure DevOps and that has been much more reliable than Travis.

**Comment by jnm2** [comment]
@rprouse I deleted the Travis file like I mentioned above because leaving it alone would have still left it broken, but I can do something else if you prefer!

**Pull request merged**
