### PR TITLE
Update BUILDING.md

### PR DESCRIPTION
**Pull request by leongjiameng**
Create link text for Cake

### CODE REVIEW

**Comment by mikkelbu** [comment]
Look good to me 👍

**Comment by leongjiameng** [comment]
May I know when will the PR be merged?

**Comment by mikkelbu** [comment]
Hi @leongjiameng. In order to merge a PR from a non-team member we need two members to approve of the PR, so currently we are waiting for the second review 😄

**Comment by ChrisMaddock** [comment]
Thanks for the contribution! 😊

**Pull request merged**
