### PR TITLE
AndConstraint should log additional information from failed constraint

### LINKED ISSUE #3233: AndConstraint should write additional information from failed constraint
```
Assert.That(new[]{ 1,2 }, Is.Ordered & Is.EquivalentTo(new[] { 1, 2, 3 }));
```

Expected message:
```
  Expected: collection ordered and equivalent to < 1, 2, 3 >
  But was:  < 1, 2 >
  Missing (1): < 3 >
```

Actual message:
```
  Expected: collection ordered and equivalent to < 1, 2, 3 >
  But was:  < 1, 2 >
```

### PR DESCRIPTION
**Pull request by Dreamescaper**
Fix #3233

### CODE REVIEW

**Comment by Dreamescaper** [comment]
@jnm2
Will as tests a bit later.
Not sure if that's applicable for NotConstraint and OrConstraint though.

NotConstraint fails when inner constraint passes, and they do not write additional info when passed.

With OrConstraint situation is different. Both left and right constraint have to be failed. What should be written then? Additional info from both of them, left then right?

**Comment by CharliePoole** [comment]
There's no reason to add similar but different work to treasure issue. I'd say create s new issue no matter who will do the work.

**Comment by jnm2** [comment]
Sounds good, let's keep it separate. https://github.com/nunit/nunit/issues/3235

**Comment by Dreamescaper** [comment]
Added tests

**Pull request merged**
