### PR TITLE
Release/3.6

### PR DESCRIPTION
**Pull request by rprouse**
**Do not merge** This branch remains open. I will create a merge branch to merge these changes back to master once the release is done.

@CharliePoole and @ChrisMaddock can you review? I am going to try to get the release out tonight.

### CODE REVIEW

**Comment by JustinRChou** [comment]
Just something minor but #1758 was left out in Issues Resolved.

**Comment by rprouse** [comment]
@JustinRChou thank, I will add it. I missed adding the milestone to it, so it didn't get generated. @CharliePoole added the milestone, thanks. I just did a quick scan and don't see any others without a milestone.

**Comment by CharliePoole** [comment]
I found and added the following to the milestone: #406 #1743 #890 #1828 #1380

**Comment by rprouse** [comment]
@CharliePoole thanks for that, I'm not sure how I missed them. Another weird thing, you said you set the milestone, but it wasn't set on any of them. I've gone and added it. I will update the CHANGES.txt.

**Comment by rprouse** [comment]
The release is done, so I am closing this PR.

**Pull request closed without merging**
