### PR TITLE
Fix NuGet package to add C# file to C# projects, VB file to VB projects

### LINKED ISSUE #565: NUnitLite Nuget package adds Program.cs to a VB Project.
whups ... enter key ...

Firstly, congratulations on the Beta release. :)

To reproduce - using https://github.com/CADbloke/CADtest - I upgraded the Nuget packages from Alpha 5 to beta 1(a?). See also https://github.com/nunit/nunit/issues/564 for details of other problems I had with this.

The Nuget upgrade added Program.cs to the VB project in that solution. It builds (once I change `Call New NUnitLite.Runner.TextUI().Execute(nunitArgs)`) but I think it will frighten them.

### PR DESCRIPTION
**Pull request by CharliePoole**
This fixes #565.

A vb main program is added now in addition to a C# program. A powershell script then deletes the one that doesn't apply. This seems like the simplest way to do it but I'm open to changes.

Since I generally avoid both VB and powershell, both my VB and my powershell should be looked at very carefully!!!

### CODE REVIEW

**Comment by rprouse** [comment]
Looks good to me, but my VB and PS foo is no stronger than yours :smile: 

If you've tested the changes and they work, feel free to merge.

**Comment by CharliePoole** [comment]
I've tested the Powershell - I really hate PS! - but I'm unsure if the vb main is as a VB person would most likely want it. Would a module be better? @CADbloke tell us what you think.

**Comment by CharliePoole** [comment]
Actually, I was tempted to just drop the cs file and rely on docs entirely but I decided to give this a shot.

**Comment by CharliePoole** [comment]
@CADbloke Waiting for your review of the VB main before merging.

**Comment by CADbloke** [comment]
@CharliePoole Where I come from VB is a [beer, and not a good one](http://en.wikipedia.org/wiki/Victoria_Bitter) so I don't really have anything constructive to add here, sorry. It looks good to me.

**Comment by CharliePoole** [comment]
@CADbloke Ah well... since it was your issue, I figured... never mind then.

I'll close it as is. The VBistas can file an issue if they find fault. :-)

**Comment by CADbloke** [comment]
I swore off both kinds of VB years ago, it keeps popping up because a lot of AutoCAD coders are VBA refugees (poor buggers) so they still use it. That, and [AutoLisp](http://en.wikipedia.org/wiki/AutoLISP) which is a whole different (affliction(())((()))( :(

**Pull request merged**
