### PR TITLE
remove redundant array type

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
thoughts on this one?

**Review by stevenaw — APPROVED** [review]
Nice simplifications.
macos build is failing from that timeout again on LargeStringCollection, almost certainly unrelated to these changes

**Comment by stevenaw** [comment]
@SimonCropp Thanks for all these clean-up PRs. This one looks good to merge. Can you please check out the merge conflict? Hopefully pushing that changeset will also kickoff a successful CI run

**Comment by SimonCropp** [comment]
conflict resolved

**Comment by stevenaw** [comment]
Thanks!

**Pull request merged**
