### PR TITLE
Proposal: Better generated code defaults, better diagnostic signal-to-noise ratio

### PR DESCRIPTION
**Pull request by jnm2**
Commit 1: adds IDE defaults for generated code to use underscores for private fields *without* adding any new diagnostic noise. Let's do at least this.

Commit 2: Enable the IDE to provide error-level diagnostics for *some* things (externally-visible API surface) while staying with suggestions or silence for non-visible things.

Commit 3: With these error-level diagnostics, make sure that nunit.framework and nunitlite do not show contributors any errors in the error list. This means fixing a handful of things and annotating a handful of others where backwards compatibility prevents a fix.

Commit 4: Same as commit 3, but for the test assemblies. This is the iffy one (it's a large commit). It's either this, or never show error feedback for externally visible surface area in any project (for ReSharper), or live with IDE errors showing up all over our tests.

### CODE REVIEW

**Comment by jnm2** [comment]
This is one of those tasks I can do while watching Build 2018. 😃

**Comment by jnm2** [comment]
@rprouse VSTS is failing at the 'Publish Artifact: drop' step with "'TF400813: The user '0de7c0cc-4788-4aa7-a5d1-963778911bd6' is not authorized to access this resource.'.".

**Comment by jnm2** [comment]
@nunit/framework-team Would this be a decent time to merge?

**Comment by ChrisMaddock** [comment]
I don't think there's ever going to be a good time! 😆

I've just been through and checked the labels on PRs - there's currently 5 that are awaiting review. 😱 I'm not totally keen on making the contributors of all of these that are 'ready to go' rebase over this - can we see if we can get some/most of these merged, and then go for this one?

Sorry - I know I've not been keeping up with reviewing lately!

**Comment by jnm2** [comment]
Okay! Let's see if we can get to zero open PRs, for real! That would be cool.

**Comment by jnm2** [comment]
Okay! Let's see if we can get to zero open PRs, for real! That would be cool.
I say that as one of the biggest open-PR offenders... 🤔

**Comment by ChrisMaddock** [comment]
Haha - I think zero open PRs may be a little ambitious! But it would be good to merge those that are just waiting on review, I think! 😄

**Comment by ChrisMaddock** [comment]
@jnm2 - as robs just merged in a load of open PRs, do you think this might be a good time to get this one in?

**Comment by rprouse** [comment]
The four merge conflicts look fairly easy to resolve if you want to get this done...

**Comment by jnm2** [comment]
@ChrisMaddock @rprouse Alright, rebased!

**Comment by ChrisMaddock** [comment]
There's a single conflict that I've resolved, and after CI, this looks good to merge to me. 🙂

**Pull request merged**
