### PR TITLE
Backport PR #4014 to fix Issue #3964 (DictionaryContainsKeyValuePairConstraint supports generic IDictionary)

### LINKED ISSUE #3964: DictionaryContainsKeyValuePairConstraint doesn't work with `IDictionary<TKey, TValue>`
`DictionaryContainsKeyValuePairConstraint` fails when actual object implements only `IDictionary<TKey, TValue>`, but not `IDictionary`:

```csharp
[Test]
void Test()
{
    var dictionary = new TestDictionary();
    Assert.That(dictionary, new DictionaryContainsKeyValuePairConstraint(1, "hello"));
}

class TestDictionary : IDictionary<int, string>
{
    // Dictionary implementation
}

// Test fails with next error:
// 1) Error : NUnit.Framework.Constraints.DictionaryContainsKeyValuePairConstraintTests.ShouldCallContainsKeysMethodOnDictionary
// System.ArgumentException : Expected: IDictionary But was: TestDictionary (Parameter 'actual')
```

**NUnit version:** 3.13.2
**Runner:** NUnit3TestAdapter

It looks like the bug is here: https://github.com/nunit/nunit/blob/2c21bff1d8891c2df3cad1f5ed34551e1c4edb9e/src/NUnitFramework/framework/Constraints/DictionaryContainsKeyValuePairConstraint.cs#L43

### PR DESCRIPTION
**Pull request by stevenaw**
A backport of PR #4014 to fix #3964 in v3.13.
Unit tests passed locally for me.

### CODE REVIEW

**Review by mikkelbu — APPROVED** [review]
I diffed this change with the original PR and they are the same. So LGTM

**Comment by stevenaw** [comment]
Thanks @mikkelbu . The failures on Azure DevOps appear .NET 5-related. It looks like the SDK isn't installed (https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#net-core-tools)

**Comment by rprouse** [comment]
It looks like all recent PRs are failing the same way. I am going to override and merge.

**Comment by stevenaw** [comment]
Thanks @rprouse 
You're right.

> ##[error]Unable to process command '##vso[results.publish type=NUnit;mergeResults=true;config=Release;runTitle='net5.0/Windows';publishRunAttachments=true;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)

**Pull request merged**
