### PR TITLE
add opencover

### PR DESCRIPTION
**Pull request by dicko2**
Creating pull request to test the build on travis and appveyor, this is not complete yet

Relates to #423

### CODE REVIEW

**Comment by dicko2** [comment]
Running open cover appears to have tripled the build time. Running on other projects I haven't seen such a large growth (10 to 30% increase  max). I wonder if it's something to do with cake  implementation possibly. I'll do some more testing tomorrow and see if I can pin it down.

**Comment by CharliePoole** [comment]
Travis is failing due to a problem with log4net initialization.

There is a Cake extension for OpenCover.

Once you get this working happily, we should decide whether we want it to run all the time or only for certain builds.

**Comment by dicko2** [comment]
I'll have another look today, should be able to get it going i reckon. 

Have a look at this https://github.com/integrations/codecov 

They have a browser extension that allows you to review the code coverage on the pull request in GitHub. I think this is good as it allows the code coverage to easily be a part of the discussion around the code review.

Also you can fail build base on coverage of pull request, unlike traditional code coverage systems that measure cover by area or entire code base, its measured on the patch of the Pull Request

To take advantage of this we would need to have it running on the CI build. What do you think @CharliePoole  ?

**Comment by dicko2** [comment]
I Recommend squashing on merge, commits are getting a bit messy from testing on appveyor.

**Comment by dicko2** [comment]
I cant get Cake Curl to not error on the Travis linux agents. I think its got something to do with the add-in support in cake. Error I am getting is about the NETstandard libraries, so i think we need a mono version of the addin in order to run it maybe? 

The only other option i can see is s separate powershell script that only executes on appveyor, which is not elegant (would be nice to do it all in cake), but seems to be the only solution, so ill try this road.

**Comment by rprouse** [comment]
Do you think updating Cake to the latest release would help? Or running with the `--experimental` flag?

**Comment by rprouse** [comment]
@dicko2 I know tracking down build errors on the Travis builds is a pain, but are you going to pick this up again? It might be easier to test using the docker container support, see `build-mono-docker.ps1`

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you pick this up again, we will reopen.

**Pull request closed without merging**
