### PR TITLE
Issue 988b

### PR DESCRIPTION
**Pull request by CharliePoole**
Some added changes I had done when looking at 988. If they look OK, merge them in - otherwise we can wait.

This doesn't really add any new capability, but it does give the driver factory access to a reference to the framework.

### CODE REVIEW

**Comment by rprouse** [comment]
I can't merge this into the release branch unless we want to pull in all recent changes on master which is against the point of this release experiment. When you created your branch, you should have created it off of the release branch, not off of master. Because you created it off master, but are trying to merge into release, it contains all of the latest checkins to master.

I am going to try to figure out a way with Git to merge just your one commit into the release branch. I am going to leave this open for now, **but do not merge**.

**Comment by CharliePoole** [comment]
I didn't think of that or I would have started over with a new branch off
of rd2. I could still do that, of course.

**Comment by rprouse** [comment]
I have cherry picked the one commit into a new branch off the RC2 branch, checked it and will create a pull request. I will review and merge that, then delete this PR and branch once it looks good.

**Comment by CharliePoole** [comment]
Ok thanks.

**Comment by rprouse** [comment]
This makes the experiment we are doing worthwhile. It didn't cross my mind that we should branch off of the release branch if we want to include those changes in the release, not have them as work in progress on master. It is obvious when you think about it, but I didn't :smile: 

The other pull request went well and I learned how to use `git cherry-pick`, so a good day...

**Comment by rprouse** [comment]
Closing this PR, it is now in #1007.

**Pull request closed without merging**
