### PR TITLE
Modifications to package version

### LINKED ISSUE #1236: Make Appveyor NuGet feed more useable
Because the nuget feed uses the AppVeyor build number, you have to look on AppVeyor to figure out the nature of each artifact. You can't just take the latest one.

We don't want to have multiple feeds, so we need to encode more information in the extended version number, after the existing 3.1.0-CI-nnnn

* For pull requests, append -PR- plus the PR # Normally, folks don't want these.

* For merges into master (builds of master that are not PRs), add an identifying suffix. This could be -MASTER or something shorter that won't be confused with anything else. Folks who want the "latest" build should take the most recent of these.

* For builds of other branches, we could append the branch name just as for master. The only problem is that we may run into problems if the version tag exceeds some maximum length. I've seen this happen in some experiments. In that case, we should truncate.

### PR DESCRIPTION
**Pull request by CharliePoole**
This fixes #1236 labelling artifacts more completely. See issue for details.

### CODE REVIEW

**Comment by rprouse** [comment]
Looks like we may have introduced another timing related failure with the test stop run changes? I am rerunning the build because it is unrelated to this. 

Error in the build;

```
1) Failed : NUnit.Framework.Attributes.TimeoutTests.TestWithTimeoutRunsOnSeparateThread
Test exceeded Timeout value of 50ms
```

**Comment by oznetmaster** [comment]
Not sure how.  The code for a test with a timeout has effectively not changed.  I think this may be something else entirely.

**Comment by rprouse** [comment]
@oznetmaster, it could easily be something else, that was just the first thing that I thought of that has changed recently. It could also just be a weird glitch that we won't see again, but at least it is documented now.

**Comment by CharliePoole** [comment]
Looks good. We got one build marked 3.1.0-CI-2090-issue-1236 and another 3.1.0-CI-2093-PR-1237. We should see 3.1.0-CI-xxxx-master when I merge.

**Pull request merged**
