### PR TITLE
Issue 784 Part 2 - Add ability to package on Linux

### PR DESCRIPTION
**Pull request by rprouse**
This updates issue #784 to include packaging on Linux. I have updated NUnit.proj to build and test portable as part of BuildAll and TestAll on Linux. I want to see if it passes on Travis, thus the separate pull request.

It still isn't able to package though. It looks like missing assemblies for the MSBuild community tasks that we are using to Zip.

```
	Target PackageSource:
		******************************************************************
		* Creating the source code package as NUnit-3.0.0-beta-4-src.zip)
		******************************************************************
		Executing: git archive -o "/home/rob/src/nunit/package/NUnit-3.0.0-beta-4-src.zip" HEAD
	Target PackageBinaries:
		******************************************************************
		* Creating the binary Release package as NUnit-3.0.0-beta-4.zip
		******************************************************************
: error : Error initializing task Zip: Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

We may need to include that assembly in with the community tasks, but I am not sure we can redistribute it. Maybe now that MSBuild is opensource?

### CODE REVIEW

**Comment by rprouse** [comment]
Mono latest builds are working on Travis, but the Mono 3.2.8 portable build is failing with 

    /usr/lib/mono/4.5/Microsoft.Common.targets: error : PCL Reference Assemblies not installed.

**Comment by CharliePoole** [comment]
If you want to wait on this, I can test it on my own Ubuntu system when I'm back home next week.

**Comment by rprouse** [comment]
I would like to merge this, but remove the portable build from Travis until it is properly supported there. @CharliePoole, if this sounds good to you, I will make the change and push it up.

**Comment by CharliePoole** [comment]
That sounds good to me. Go ahead and merge when it's ready.

**Comment by rprouse** [comment]
I removed the portable build from Travis CI. It works for the latest version of mono, but not for the 3.x version.

**Pull request merged**
