### PR TITLE
Properly distinguish between .NET 4.0 and 4.5

### LINKED ISSUE #237: System.Uri .ctor works not properly under Nunit
.NET Version 4.5, Nunit version 2.6.2 and 2.6.3 (same behavior)
Reproduced under ReSharper, from GUI-Runner, from NUnit-Console

Tested on :

Win 7 Pro, all updates, Ru-ru locale - reproduced

Win Server 2012, all updates En-us locale - reproduced

Try this:

	[TestFixture(Description = "Uri .ctors under Nunit must work exactly as no under Nunit")]
	public class InvalidUriCtorUnderNnit
	{
		[Test]
		public void PathsWithDotsMustBeParsedWell()
		{
			const string urlWithDots = "http://host.com/path./";
			Assert.AreEqual(urlWithDots, new Uri(urlWithDots).ToString());
		}
	}
	
EXPECTED:

Uri not changed and "http://host.com/path./" returned

ACTUAL:

Cropped "http://host.com/path/" returned

NOTES: 
1) This behavior never occured in production and cannot be catched except under NUNIT run.
2) Have compared all loaded assemblies versions and codebase - all exactly match with production
3) Have tested Internet on this issue - nothing

Wish you could reproduce.

### LINKED ISSUE #244: NUnit should properly distinguish between .NET 4.0 and 4.5
This issue came up in discussing #237. See comments there.

The problem:

NUnit-console is normally compiled to target .NET 2.0 and when it sees an assembly built with .NET 4.0/4.5 it runs tests in another process. This worked well through .NET 4.0 but 4.5 and subsequent releases introduced several problems, which we'd like to resolve in this issue. All these problems are basically caused by the fact that 4.5 is a _replacement_ for 4.0 on any machine where it is installed, as opposed to being installed side by side. (That's a Good Thing because side-by-side has it's own problems, but it is the root of the problems we are seeing.)

1. When examining the assembly, NUnit only looks at the version of the framework that it targets. Because 4.0 and 4.5 use the same version number, it treats everything as 4.0.

2. When NUnit looks for what runtimes are installed on a machine, it is able to detect 4.5. (This appears to work correctly, but should be verified. If it sees 4.5, then it offers (in the Gui menu) to run the tests under either 4.0 or 4.5. If it only sees 4.0, then it only offers 4.0. (This also seems to work correctly, but should be verified)

3. When creating a process in which to invoke nunit-agent, NUnit uses an environment variable to ask for a runtime using the version number. If only 4.0 is installed on the machine, we get 4.0 behavior If 4.5 is installed, we get 4.5 behavior. That's a problem when 4.5 is installed and the user has asked to target 4.0. Either we should not promise 4.0 behavior in item 2 above, or we should issue a warning, or we should give the user true 4.0 behavior.

We didn't deal with this in the past, primarily because it didn't come up as an issue, but also because it was thought that there is no way to give 4.0 behavior once 4.5 is installed. Rob's research on #237 indicates that there is a way to tell the 4.5 assemblies - or at least some classes - to emulate 4.0 behavior at the time the AppDomain is created. We should do that to the extent possible and also document to what extent it is possible.

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #244 and fixes #237.

The code is complicated a bit by the fact that `AppDomain.TargetFrameworkName` and `TargetFrameworkAttribute` only exist if .NET 4.5 is installed, thus the need for reflection. 

I am not happy with the tests for this since they test the original issue, #237, not the actual code, but this code is very dependent on what version of the .NET Framework is installed on the test machine. In addition to the two tests, I stepped through the code in each version of the .NET framework. Suggestions are welcome.

### CODE REVIEW

**Comment by rprouse** [comment]
Interesting, based on the Travis CI failure, it looks like Mono runs with the 4.5 behavior even for an assembly that targets 4.0. I will add a platform attribute to exclude that test.

**Comment by jcansdale** [comment]
Hi Rob,

I've made a few tweaks in code below:

1) I'm using CreateInstanceFromAndUnwrap instead of CreateInstanceAndUnwrap. App domains take their default base directory from the EXE rather than the current app domain. This can make CreateInstanceAndUnwrap fail when running inside a test app domain.

2) I'm finding the TargetFrameworkAttribute and requesting it specifically using GetCustomAttributes(attrType, false). This stops it from loading assemblies and constructing type objects that we aren't actually using.

3) I'd using GetProperty("TargetFrameworkName"), because the property is public and we can use the default flags.

        // .NET versions greater than v4.0 report as v4.0, so look at
        // the TargetFrameworkAttribute on the assembly if it exists
        private static void SetTargetFramework(string assemblyPath, AppDomainSetup setup)
        {
            var property = typeof(AppDomainSetup).GetProperty("TargetFrameworkName");

            // If property is null, .NET 4.5+ is not installed, so there is no need
            if (property != null)
            {
                var domain = AppDomain.CreateDomain("TargetFrameworkDomain");
                try
                {
                    var agentType = typeof(TargetFrameworkAgent);
                    var agent = domain.CreateInstanceFromAndUnwrap(agentType.Assembly.CodeBase, agentType.FullName) as TargetFrameworkAgent;
                    var targetFramework = agent.GetTargetFrameworkName(assemblyPath);
                    if(!string.IsNullOrEmpty(targetFramework))
                    {
                        property.SetValue(setup, targetFramework, null);
                    }
                }
                finally
                {
                    AppDomain.Unload(domain);
                }
            }
        }

        private class TargetFrameworkAgent : MarshalByRefObject
        {
            public string GetTargetFrameworkName(string assemblyPath)
            {
                // You can't get custom attributes when the assembly is loaded reflection only
                var testAssembly = Assembly.LoadFrom(assemblyPath);

                // This type exists on .NET 4.0+
                var attrType = typeof(object).Assembly.GetType("System.Runtime.Versioning.TargetFrameworkAttribute");

                var attrs = testAssembly.GetCustomAttributes(attrType, false);
                if (attrs.Length > 0)
                {
                    var attr = attrs[0];
                    var type = attr.GetType();
                    var property = type.GetProperty("FrameworkName");
                    if (property != null)
                    {
                        return property.GetValue(attr, null) as string;
                    }
                }

                return null;
            }
        }

Let me know your thoughts and if that makes sense.

Regards,
Jamie.

**Comment by CharliePoole** [comment]
It looks OK to me, but take Jamie's comments into account please.

**Comment by rprouse** [comment]
I am going to update based on Jamie's comments tonight.

**Comment by rprouse** [comment]
I have updated based on Jamie's code. This should be ready to merge once CI passes.

**Comment by rprouse** [comment]
Travis build failure is the unrelated issue #544. This is ready to merge.

**Pull request merged**
