### PR TITLE
Assert on Dictionary Content #24

### PR DESCRIPTION
**Pull request by constructor-igor**
Assert on Dictionary Content #24 (https://github.com/nunit/nunit/issues/24)

### CODE REVIEW

**Comment by CharliePoole** [comment]
No need to put a URL in the title. Just using #24 in the description does the job. If you say "Fixes #24" it the issue will be closed when this is merged. You can put that in the PR and/or in the commit comment.

All this is just logistics though. No worries.

**Comment by rprouse** [comment]
Looks good to me. The two new files will need to be added to CF. Should @oznetmaster do that separately, or should someone add to the PR?

**Comment by CharliePoole** [comment]
The actual code changes look good to me and I would merge them online except that I wonder about the large number of changes shown for the .csproj files. They seem to be line ending changes. You should check your git config --list output for the value of core.autocrlf, which should be true. I could be worrying about nothing here but I'll try merging this manually myself to see what happens and because of the other change that's needed (below).

You haven't added the new class to the CF build, which is understandable. Sometimes we add things and then follow up only later with the addition to CF. This one is so small that I'd as soon add it at the same time. Don't worry about this - lots of the developers leave CF for somebody else to take care of. :-)

**Comment by CharliePoole** [comment]
@rprouse I see we crossed each other in the mail. :-) I'll go ahead and add it to CF as part of the merge since it looks trivial. Are you also surprised at the large number of diff changes to the csproj files?

**Comment by rprouse** [comment]
I was also surprised, but I couldn't look at the line endings in GitHub
without pulling the branch. @constructor-igor, did you use Visual Studio
for these changes?

On 21 April 2015 at 14:34, CharliePoole <notifications@github.com> wrote:

> @rprouse <https://github.com/rprouse> I see we crossed each other in the
> mail. :-) I'll go ahead and add it to CF as part of the merge since it
> looks trivial. Are you also surprised at the large number of diff changes
> to the csproj files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/pull/604#issuecomment-94898272>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by CharliePoole** [comment]
It isn't a big deal, of course, but let's help Igor get set up right for NUnit! :-)

**Comment by CharliePoole** [comment]
@constructor-igor I have invited you to join a new group I created as a part of the NUnit organization. If it works the way the docs describe, I'll be able to assign things to you directly. Let's test this and see how it works since there is really a need to be able to assign things to contributors.

**Comment by rprouse** [comment]
>It isn't a big deal, of course, but let's help Igor get set up right for NUnit! :-)

I think you are right. I just got latest and the two files that @constructor-igor added for the last PR are showing up as modified for me even though they have not changed.

@constructor-igor, can you check your global `.gitconfig` file. It should contain the following on Windows,

```
[core]
	autocrlf = true
	safecrlf = true
```

**Comment by rprouse** [comment]
I pushed the line ending fixes for the two files directly to master. Not directly related to this PR, but since we are discussing it here :smile:

**Comment by CharliePoole** [comment]
I give up on fixing the line endings manually. I'm merging online and we can fix anything as a next step.

**Comment by rprouse** [comment]
I just did a pull and now have 13 modified files. I will see if I can fix them and push them back up.

**Comment by rprouse** [comment]
Changes pushed to master. @CharliePoole, can you pull latest and see if it is clean for you?

**Comment by CharliePoole** [comment]
I also pulled and have the changed files. I'll reset and try again.

**Comment by CharliePoole** [comment]
Looks OK... now for CF.

**Comment by CharliePoole** [comment]
I added the two new files to CF and tested. Pushed directly to master.

**Comment by CharliePoole** [comment]
@constructor-igor As you can see, it's a pita for us if your line endings aren't right!

**Comment by constructor-igor** [comment]
>The two new files will need to be added to CF

Please, could you add more details about the issue? What it does mean?

I use VS2013 and make commit via Tortoise Subversion.
I understand problem with "end of line" and I am going to search a solution.

**Comment by CharliePoole** [comment]
See my last commit to master. I added the two new files to the .NET compact framework 3.5 build, which is done using VS2008. As I said, it's pretty normal to have changes that don't get into that build right away, so you shouldn't worry about it. Generally, either Neil or I takes care of it so long as there isn't code that won't build under CF 3.5. If there had been any code like that, I would have pointed it out in the code review.

**Comment by CharliePoole** [comment]
If you're using Subversion, then do you mean you don't have a local Git repository? That sounds like a difficult way to work and I wonder if the translation through Subversion is messing up your settings.

**Pull request merged**
