### PR TITLE
Release 3.4.1

### PR DESCRIPTION
**Pull request by rprouse**
@CharliePoole I am going to leave this branch/PR for you to do the release from. **Do not merge** this PR, just use it to track the work.

I have cherry picked and rebased the three pull requests that I think we need. Please review and ensure everything that should be included is included and that I have not pulled in anything extra. Once you do that, you will need to add to `CHANGES.txt` and update the version in the normal places. Push those changes to this branch then do the release based on this branch, tagging this branch in the GitHub release.

If you could, check in the changes to CHANGES.txt in a separate commit so that I can cherry pick it back into master and not pull in the 3.4.1 version changes.

After the release, I will make sure any changes to this branch make it back into master.

I need to start getting ready to leave now. I am a bit late :smile: I will check back here quickly before I leave if you have any questions.

Thanks for taking this on. :+1:

### CODE REVIEW

**Comment by CharliePoole** [comment]
Backed out the change to the DirectoryFinderTests - it was needed at a certain point only because of the order in which we were applying commits.

**Comment by CharliePoole** [comment]
I released but wasn't able to do the nuget release due to lack of permission. Unfortunately, NUnit.Console did get out there but not its dependencies.

**Comment by CharliePoole** [comment]
@rprouse Is there any reason not to close this PR? I know we want a release branch, so we should determine which of the release branches is to be kept.

**Comment by CharliePoole** [comment]
@rprouse Waiting for your answer.

**Comment by rprouse** [comment]
@CharliePoole sorry, no reason to leave it open. I had originally left it open to remind us to merge any changes you made back into master, but that is already done.

**Pull request closed without merging**
