### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by jnm2**

### CODE REVIEW

**Comment by jnm2** [comment]
Oh! How hard would it be to replace unsupported chars with `-` when creating the package version string?

**Comment by ChrisMaddock** [comment]
@jnm2 - we already make modifications for length, we should just do the same for special chars. I was just about to log an issue - shall I leave it with you instead? 🙂 

https://github.com/nunit/nunit/blob/master/build.cake#L157

**Comment by jnm2** [comment]
>  I was just about to log an issue - shall I leave it with you instead?

Makes no difference to me.

**Comment by jnm2** [comment]
@ChrisMaddock https://github.com/nunit/nunit/issues/2186

**Comment by ChrisMaddock** [comment]
Thanks!

**Pull request merged**
