### PR TITLE
Fix TestOutput XML serialization with invalid characters

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes https://github.com/nunit/nunit/issues/4144

See the comment https://github.com/nunit/nunit/issues/4144#issuecomment-1193183959 about more investigation notes.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=4145) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=4145) before we can accept your contribution.<br/><br/>:x: mxschmitt [sign now](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=4145)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/nunit?pullRequest=4145) it.</sub>

**Comment by mxschmitt** [comment]
@CharliePoole might be a good candidate for the review since he worked on related stuff in the past.

Thanks!

**Review by rprouse — APPROVED** [review]
Looks good, thanks.

Not sure why the MacOS build is failing, it looks like a timing error, so I reran the tests.

```
1) Failed : NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean
  Expected: True after 500 milliseconds delay
  But was:  False
   at NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean() in /Users/runner/work/nunit/nunit/src/NUnitFramework/tests/Constraints/DelayedConstraintTests.cs:line 93
```

**Comment by mxschmitt** [comment]
> Looks good, thanks.
> 
> Not sure why the MacOS build is failing, it looks like a timing error, so I reran the tests.
> 
> ```
> 1) Failed : NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean
>   Expected: True after 500 milliseconds delay
>   But was:  False
>    at NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean() in /Users/runner/work/nunit/nunit/src/NUnitFramework/tests/Constraints/DelayedConstraintTests.cs:line 93
> ```

Passing now, looked like it was flaky.

**Comment by mxschmitt** [comment]
@rprouse can we merge this? I'd then open another PR which backports the fix into the v3.13-dev branch so its included in the next patch release as well.

**Review by stevenaw — APPROVED** [review]
Thanks for your contribution @mxschmitt ! We usually like to have two sets of reviews, but this looks good to me as well. LGTM 🚀

@rprouse I understand we're not backporting everything, but should this be backported to 3.x ?

**Pull request merged**
