### PR TITLE
#610 Add integration/regression tests to ensure compatibility with TeamCity

### LINKED ISSUE #610: Add integration/regression tests to ensure compatibility with TeamCity
Tests to ensure nunit sends suitable service messages for general usage scenarios.

### PR DESCRIPTION
**Pull request by NikolayPianikov**
Project _'src\NUnitIntegration\nunit.integration.mocks'_ contains mocks of tests for specific scenarios of integration. Project _'src\NUnitIntegration\nunit.integration.tests'_ contains a logic to check integration scenarios, it is assumed that all integration tests, including other products, will be located here.

Output directory for these tests is _'bin\IntegrationTests'_. It contains subfolders for each version of NUnit related to specific Net Framework.

The integration tests run _'nunit-console.exe'_ using specific command line arguments and analyze output to check integration scenarios. 

Each integration scenario use some subset of tests (mocks of tests) to be checked.
These mocks of tests are located in the _'nunit.integration.mocks'_. Integration scenarios are linked to the certain mocks of tests using _'CategoryAttribute'_.

Integration tests for TeamCity are located in the _'src\NUnitIntegration\nunit.integration.tests\TeamCity\TeamCityIntegrationTests.cs'_. These tests are run for each scenario from _'src\NUnitIntegration\nunit.integration.tests\TeamCity\CaseLists.cs'_ and for each .Net Framework (also for some other combinations such as using _'--teamcity'_ command line argument or _'TEAMCITY_PROJECT_NAME'_ env variable).

Some points:
* We could use this approach for other integration tests.
* We could use these integration tests in the CI.
* **We should exclude all mocks of tests from the testing - Category("MockTests").**
* Now these tests are working just for Windows_NT.
* In the future I am going to reuse these integration tests as some "certification core"  and I am planning to add other integration tests here.
* Should we group tests output by assembly, by namespace, by test class name or by something other using: ##teamcity[testSuiteStarted name='suiteName'] and ##teamcity[testSuiteFinished name='suiteName']? See [Build Script Interaction with TeamCity](https://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingTests)

I can add explanations if are needed.

What do you think about it. Could your share your opinions?

Fixes #610

### CODE REVIEW

**Comment by NikolayPianikov** [comment]
I've added integration tests to CI

**Comment by CharliePoole** [comment]
Thanks for this. I wanted to reply quickly, before going through all the details of the changes, to say I've been working at setting up some integration tests, so this is timely. That said, it may take us a while to digest such a large PR.

A few preliminary comments:

* NUnit has generally been using NSubstitute for mocking - we even distributed it with the NUnit 2.x tests. Introducing Moq isn't impossible for 3.0, but there would need to be a darned good reason. FWIW, we used Moq before we switched to NSubstitute. Is this because you already have various TC mocks defined using Moq? If so, we could probably just isolate this change.

* We try to keep NUnit pretty "pure" in terms of using NUnit alone to test NUnit. We don't even use our own VS adapter. What benefit do you see from adding Shouldly? Again, if these are tests you use generally, we can simply isolate it.

* I gather that these tests work whether we run under TC, on the desktop or on another CI server. Do they run on Linux / Mono?

(Lots) more comments to come I'm sure. :-)

**Comment by NikolayPianikov** [comment]
I've removed dependencies on Moq and Shouldly

**Comment by rprouse** [comment]
@NikolayPianikov, have you made any progress getting these tests to run under Linux? Do you still want to continue contributing to this PR? 

If you want to carry on work on this, then I think you should probably merge in latest from master first to ensure that this branch stays mergable. As @CharliePoole said, this is a fairly large pull request to digest all at once and very hard to review as a series of diffs, so I will probably pull down the branch and review it that way. Before I do that, I just wanted to make sure that you are planning on continuing with this :smile:

**Comment by CharliePoole** [comment]
Basically, this PR has two things in it:

1. A structure to be used for integration tests generally.
2. A set of TeamCity integration tests.

This is something we have needed for a while, but which I for one never found time to do. I'd like to separate out the structure and get it in place. Then we can review the TC integration tests more closely. @NikolayPianikov does that make sense to you? @rprouse ?

So, here's how I understand the overall structure. @NikolayPianikov please confirm whether I have got it right!

* Integration tests are contained in one assembly. We could expand this to have multiple assemblies for different types of integration tests.

* Integration tests use the console runner to run a variety of tests. These are second-level tests, similar to those in our testdata assemblies. They may fail or pass. The actual first-level tests know what is expected and check for it.

@NikolayPianikov You call these second-level tests "mocks." I think this is a bit confusing for those of us who have spent a lot of time arguing about the meaning of mocks versus stubs etc. In my view they are not "mock tests" but real tests at a second level. You indicate that a category should be used to avoid running them, but this doesn't seem necessary. In the case of NUnit unit tests, we simply don't run those tests directly so we never see the output. That's why they are in a separate assembly. Is there some special consideration when running under TC that makes you say this?

* Integration tests are running as a part of the CI build. We have to decide whether that's what we want. That is: should the CI fail if integration tests fail? Do we need a way to indicate that a particular test may not pass in some circumstances? Or that it may not pass yet because work is in progress?

I can see us going with this general approach. I think the TC tests should be one assembly. We will add others. Eventually,we should have tests of the GUI as well.

If we can agree on this, I think the following steps are needed...

1. Rebase this PR on the latest master and correct any issues. Either @NikolayPianikov or one of us can do that, but if it's one of us we'll have to create a branch in NUnit to do it.
2. Merge this PR into a branch under nunit and remove all the TC tests so only the structure remains. We can add one dummy test in order to test it. I can do this.
3. Rease this PR (again) based on the master. It should only contain the TC test additions, which we can then review separately.

Thoughts guys?

**Comment by CharliePoole** [comment]
@rprouse @NikolayPianikov I made a proposal for moving this PR ahead two weeks ago but neither of you has commented on it. See steps 1 to 3 at the end of the previous comment.

**Comment by NikolayPianikov** [comment]
Sorry for delay.

1. Could we create some new repository, may be, as a test stand to for all versions of NUnit to check base scenarios?  

2. Could we allow to test external addins or tools there? I mean TeamCity service message addin, MSBuild community NUnit task and so on. 

3. Also I would like to have ability to share groups of test for different CI, for example, we are interested in the integration tests for TeamCity service messages, and we can run a this part of tests on our side too.

The main directions are:
- base scenarios
- to check integration: list of arguments, exit codes, addins and external tools
- the running on the other platforms (Mono)
- the reporting (number of failed, ignored, successful tests)
- the running in several threads
- exception handling for serious errors (OutOfMemory, StackOverflow, AppDomainUnload)
- also we are interested in scenarios when we get a list of tests and run them using 2 steps: 1 - to run tests which were failed on the previous run, 2 - to run others

How we can achieve these goals:
We could create DSL over NUnit as abstraction and could create implementations for different versions of NUnit
We could have a set of acceptance criteria (using Gherkin for example)

What do you think?

**Comment by CharliePoole** [comment]
@rprouse Waiting to hear from you re my proposed approach to this (above).

**Comment by rprouse** [comment]
@CharliePoole, I dropped the ball on this PR. Your proposed approach sounds reasonable. Would you like me to pick it up if @NikolayPianikov doesn't have time?

**Comment by CharliePoole** [comment]
Well, we both did and I haven't been treating #610  as a high priority. I think we need to have a framework for integration tests and I'm sure @NikolayPianikov will be willing to create a new PR specifically for the teamcity tests once we have it.

By this time, rebasing the current PR may not be such a good idea though. The framework can probably be more easily created from scratch.

**Comment by NikolayPianikov** [comment]
I agree with all of you, we should make it simpler. I am going to suggest simple version and integrate it into CI. I have yet another counter-offer. What do you think about following: the NUnit will use the teamcity.jetbrains.com as the main (and may be the only) build server? We are ready to help to configure the CI. We will have the stable and free CI and we will have the excellent project on the JetBrains's build server :) What do you think?

**Comment by CharliePoole** [comment]
Once upon a time, we had teamcity as our only build server. Even with a lot
of help from folks at Jetbrains, we never got it to work well.
Configuration is quite complex as compared to the CI builders we now use:
Travis for Linux and Appveyor for .NET. Recently, somebody new took over
maintaining the TeamCity build but it tends to fail when we make build
script changes.

I would hesitate to drop what works for just the chance of something
better. OTOH, if you're volunteering to work on our existing TC build,
which we use as a secondary CI and to verify that we work with TC, we can
use all the help we can get.

**Comment by CharliePoole** [comment]
Regarding the integration tests. That has to be done even prior to CI
integration. That is, we need it in the build script we use as developers.

**Comment by NikolayPianikov** [comment]
@CharliePoole Regarding the integration tests - yes of course

**Comment by rprouse** [comment]
@NikolayPianikov, is this PR superseded by #857? Can we close this one?

**Comment by NikolayPianikov** [comment]
Yes, I closed it

**Pull request closed without merging**
