### PR TITLE
Support filtering project when nunit3-console is used with a solution…

### PR DESCRIPTION
**Pull request by pcalin**
…. See issue #668

### CODE REVIEW

**Comment by CharliePoole** [comment]
I see a few top-level problems with this, so I'm not doing line by line comments right now.

1. IProject is an extensibility interface. Changing it affects all three NUnit bundled project loader extensions as well as any user extensions.

2. The filtering only makes sense for solution files, but you have applied it to NUnit projects as well. Of course, you had to do that once you changed the extensibility interface. In fact, user-defined projects would need to support a filter as well, whether they need one or not.

3. It seems as if this could be done in a more localized way, following some of the suggestions on issue #668.

I'd like to see us resolve this issue, but preferably in a way that doesn't impact every project loader we have or which may be written in the future. Ideally, we don't want to change the extensibility interfaces or the overall API if it can be avoided.

**Comment by CharliePoole** [comment]
What if we supported `assembly==...` and `assembly~=...` in our test selection language used by the `--where` option?

The parsing would be simple enough. The trick would be to apply this particular filter in the engine, before loading the assembly, rather than passing it on to the framework for handling.

**Comment by pcalin** [comment]
Awesome. I'll look into passing the where options.

**Comment by pcalin** [comment]
A simpler option would be to implement the filter in the MasterTestRunner.ExpandProjects. Basically apply the filter after the expansion.

**Comment by CharliePoole** [comment]
I agree it might be simpler to implement in MasterTestRunner, particularly if we did it in conjunction with analyzing the assemblies. We may end up doing this but it seems to me that the ideal solution would be that the loader only returns test projects.

The reason I say that is because IProject and IProjectLoader are not intended to be general ways of working with VS or any other kind of project. They are supposed to represent collections of test assemblies. So, if it's at all possible for the VSProjectLoader to determine which projects are really test projects, I think it should do so. If it's not possible - or even too messy - then we can fall back to filtering the list of projects after the fact.

**Comment by pcalin** [comment]
I implemented checks in VSSolution to verify the project references nunit.framework. Should be enough for most needs and easy to document/understand.

**Comment by CharliePoole** [comment]
This certainly seems to fix it for the nunit framework, but takes us down a path where the project loader extension has to know what frameworks we support. Of course it's the logical outcome of what I asked for - in order to only return test assemblies, the loader has to know all possible test framework names! @rprouse What do you think? Is this the right direction or do we need to filter test projects out external to the VS Project loader?

**Comment by rprouse** [comment]
I think this is a decent solution for now since we only support nunit at the moment. 

@CharliePoole, can we use the `IDriverService` from a plugin? We could extend `IDriverService` with something like `IEnumerable<string> GetSupportedTestFrameworkAssemblies()` that queries each of the driver factories and yield returns the supported assembly names and use that list instead of the hard coded assembly name. We would also extend IDriverFactory with the same method, enumerable in case a future driver supports multiple frameworks.

**Comment by CharliePoole** [comment]
Yes, that's the sort of thing I was thinking of. The VS project loader could make use of the service to find out the names of frameworks that indicate tests.

I agree that we can do this later, however. Merging.

**Pull request merged**
