### PR TITLE
Removing appveyor #4504

### PR DESCRIPTION
**Pull request by OsirisTerje**

### CODE REVIEW

**Review by stevenaw — APPROVED** [review]
Thanks @OsirisTerje !

**Comment by mikkelbu** [comment]
@OsirisTerje, @stevenaw Was it on purpose that the `appveyor.yml` file was not removed? Also I've remove some parts of the cake script that is no longer used - https://github.com/nunit/nunit/pull/4508

**Comment by OsirisTerje** [comment]
I did remove the appveyor.yml and the cake scipt parts referring to appveyor

**Comment by mikkelbu** [comment]
I already made a PR for it and also clean up the cake script some more

**Pull request merged**
