### PR TITLE
Release alpha 5

### PR DESCRIPTION
**Pull request by CharliePoole**
Final changes for the alpha 5 release. Ready to merge.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Hang on... I'm going to change LevelOfParallelization...

**Comment by CharliePoole** [comment]
OK... ready to merge again... please review.

**Comment by oznetmaster** [comment]
Sorry I am not anywhere I can build this and test it.  Looks ok, but someone else should review it before it is merged.

**Comment by CharliePoole** [comment]
That's cool! Just seeing your name reminded me I had not changed the file
name in CF.

**Comment by CharliePoole** [comment]
@rprouse I'll wait for you to review

**Comment by rprouse** [comment]
Looks good, ship it :)

**Pull request merged**
