### PR TITLE
Issue #403

### PR DESCRIPTION
**Pull request by oznetmaster**
This is a first pass at implementing issue #403.  It compile in all builds, and works in my limited local tests.

### CODE REVIEW

**Comment by oznetmaster** [comment]
So are you indicating that the  PARALLEL condition should be put back, on both the option and the command line test for it?

**Comment by CharliePoole** [comment]
I can't answer about the PARALLEL in any simple way without downloading the branch - which I will do later tonight. When you change a file and move it in the same PR (Options.cs) the online display is pretty useless,  so I have to get it onto a local system where I can compare using my own tools.

WRT the --workers option, I think there's a design choice to be made. In non-parallel builds, it should either not be an option or we should issue a warning message that we are ignoring it. The warning message is the friendliest but would have to be in the reporting part of the NUnitLite runner.

Best bet here I think is to wait for an  actual review from me. :-(

BTW, is it 2015 for you already?

**Comment by oznetmaster** [comment]
Yes. 12 hours ago.

**Comment by CharliePoole** [comment]
Three and a half more hours to go here. :-)

**Comment by CharliePoole** [comment]
Comparing the original Options.cs with the current one, I see a lot of unnecessary changes, mostly with regard to formatting. However, these changes were made a while back, not in this merge.

One question... did you try leaving the classes in the NUnit.Common namespace as I suggested? If so, where did the conflicts arise? I imagined that would be possible in this case because I couldn't think of any situation where a class would reference both nunit-console and nunitlite.

None of this prevents merging, however.

**Comment by oznetmaster** [comment]
I am not sure what you are asking: “did you try leaving the classes in the NUnit.Common namespace as I suggested”?  We never discussed that.  The classes are where they have always been.  I changed nothing.

**Comment by CharliePoole** [comment]
No problem, I'll take a look at it myself. For the earlier discussion, see my comment here: https://github.com/nunit/nunit/issues/403#issuecomment-68189501

**Pull request merged**
