### PR TITLE
#1140 - Equals/ReferenceEquals methods exception

### PR DESCRIPTION
**Pull request by mjedrzejek**
Initial PR, waiting for review

### CODE REVIEW

**Comment by CharliePoole** [comment]
Looks good to me. Thanks for doing it.

We'll wait for one more committer to OK it and then merge.

**Comment by rprouse** [comment]
This looks good to me too, but I would like to see unit tests.

We currently don't have unit tests for this functionality, but this would be a good opportunity to add some. @mjedrzejek would you mind adding quick `Assert.That(..., Throws)` tests for this change to `AssertEqualsTest.cs`, `AssumeThatTests.cs`, `FileAssertTests`, etc.?

**Comment by mjedrzejek** [comment]
No problem, I will add some tests

**Comment by rprouse** [comment]
I see unit tests for Assume.Equals. Am I missing the tests for the other changes?

**Comment by mjedrzejek** [comment]
Yes, there were missing. Now tests for all changes are included

**Comment by rprouse** [comment]
Thanks for the contribution.

**Pull request merged**
