### PR TITLE
Limit throws to exception types. For both TypeOf and InstanceOf.

### PR DESCRIPTION
**Pull request by WdeBruin**
See the discussion in the issue topic for detailed info.

### CODE REVIEW

**Comment by CharliePoole** [comment]
What you have looks good but I think you also need to look at `Throws.TypeOf`` and `Throws.InstanceOf`.

**Comment by CharliePoole** [comment]
@jnm2 `Assert.Throws` already uses a constraint.

**Comment by jnm2** [comment]
> liiks liek 

😆 Guess I'm abusing the single-line "dismiss review" textbox– hard to proofread typos!

**Comment by rprouse** [comment]
This looks good to me. @CharliePoole are you saying he should make changes to the non-generic `TypeOf` and `InstanceOf` too? If so, are you proposing a guard clause to check the type passed in?

**Comment by CharliePoole** [comment]
@rprouse I misspoke (typed)! Comes from trying to review on the phone. 😕 

I got it backwards. He has changed the generic Throws methods but not the constructor, which I think should also be changed since it can be used independently.

**Comment by WdeBruin** [comment]
Thanks for the feedback. But what exactly do you mean with the ThrowsExceptionConstraint constructor?@CharliePoole 
That class doesn't have a constructor override as far as I can see. The ThrowsExceptionConstraintResult is already taking an Exception as parameter.

**Comment by CharliePoole** [comment]
@WdeBruin You're right. I was looking at local experimental code.

**Pull request merged**
