### PR TITLE
chore: Add badges to README file

### LINKED ISSUE #3290: 'Good first issue' or 'help wanted' issue count badge
What do you think of the idea of adding one of these badges to our readme?

[GitHub issues by-label](https://github.com/nunit/nunit/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)

Or

[GitHub issues by-label](https://github.com/nunit/nunit/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

### PR DESCRIPTION
**Pull request by mikkelbu**
Fixes #3290

### CODE REVIEW

**Review by jnm2 — COMMENTED** [review]
Excellent!

That's a lot of rows. Are the build badges useful?

**Review by jnm2 — APPROVED** [review]

**Comment by mikkelbu** [comment]
@jnm2 Personally, I use the build badges from time to time. As an alternative we could move the new badges to the last row and place them after the "mailing list" badge?

**Comment by jnm2** [comment]
Sure! The way it is is fine with me too. Whatever seems to balance where we want the attention of the reader with the convenience for the team, if we know what that is.

**Review by jnm2 — APPROVED** [review]
Ooh, I like this.

**Comment by mikkelbu** [comment]
Thanks for the review Joseph 👍

**Pull request merged**
