### PR TITLE
Issue 3390: Do not prefilter relevant SetUpFixtures

### PR DESCRIPTION
**Pull request by gleb-osokin**
Addresses #3390 and #3454

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3679) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3679) before we can accept your contribution.<br/><br/>:x: gleb-osokin [sign now](https://cla.dotnetfoundation.org/nunit/nunit?pullRequest=3679)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/nunit?pullRequest=3679) it.</sub>

**Comment by rprouse** [comment]
@gleb-osokin thanks for the PR and sorry for responding so late, I've been concentrating on the 3.13 release. I'll get this reviewed and make a call if it will be included in the release soon. I am going to temporarily mark this with the 3.13 milestone for tracking. I may remove the milestone once I review.

**Review by rprouse — APPROVED** [review]
Thanks for your help, this looks great. I've pulled locally and tested against the reported issues and it works great.

**Comment by nkastratovic** [comment]
When is the release date for 3.13 version?

**Pull request merged**
